### ISSUE TITLE
Track shards that have data (instead of MaxShard)

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1008]
### Description
Currently Pilosa tracks `MaxSlice` by index, and all operations are performed by iterating through slices 0 to MaxSlice. We should consider instead keeping track of which slices per index contain data such that actions performed on all slices can be done via a generator.

There are some things to consider however:

This problem occurs because it's possible to set column values out of order and effectively skip slices. If this were not possible (i.e. if all writes went through a key translator such that this skipping of slices didn't happen) then this change would not be required.  There is a related discussion in #593.

An implementation of this would require that nodes share slice-data information with the cluster (as they do with MaxSlice now). It may also be necessary to persist the slice-data to disk for restarts. A similar issue for MaxSlice is at #916.

A case where this could have been useful was in cluster resizing. If one creates a one-node cluster with data on slices 0 and 2, and then adds a node to the cluster, then the new node will try to retrieve slice 1 from the original node and receive an `ErrFragmentNotFound`. This is actually not an error, but it's difficult to determine that without knowing which slices are expected to contain data.

**Comment by codysoyland** [comment]
Modified the title, but several references to "slice" above. For those who might not know, "slice" was renamed to "shard."

**Comment by codysoyland** [comment]
Fixed in #1600
