### ISSUE TITLE
Modify /version endpoint to support semantic versioning

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1034]
### Description

Currently the `/version` endpoint returns a payload such as: `{"version":"v0.8.0-127-g2772daa"}`. The version in the `version` field starts with `v` which doesn't conform to the [semver spec](https://semver.org). Dropping the `v` from the version string makes it parseable for the libraries I've tried.

### Success criteria (What criteria will consider this ticket closeable?)

`/version` endpoint returns semver compatible version strings, such as: `"0.8.0-127-g2772daa"`.

**Comment by jaffee** [comment]
Seems like a good idea to me.

I'm not aware of any tooling we have currently that expects this to start with 'v'... anyone else?

**Comment by travisturner** [comment]
i don't see any problem with removing the `v`

**Comment by yuce** [comment]
We will have to do some version sniffing in the clients later. It would be more robust to parse the version with a semver package. It's trivial to remove the `v` in the client, so this ticket isn't a priority; but it would be useful to make other software use our version endpoint.
