### ISSUE TITLE
Still not possible to have range enabled frames with cache

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1037]
### Expected behavior
A frame can both have fields and have a cache of it's non-field rows.

### Actual behavior
Setting both a cache type and range enabling in frame options is rejected

### Steps to reproduce the behavior
Try to create a frame with both.

The following patch to index.go seems to address the issue, but I have not tested extensively.
```go
@@ -440,8 +440,6 @@ func (i *Index) createFrame(name string, opt FrameOptions) (*Frame, error) {
 	if opt.RangeEnabled {
 		if opt.InverseEnabled {
 			return nil, ErrInverseRangeNotAllowed
-		} else if opt.CacheType != "" && opt.CacheType != CacheTypeNone {
-			return nil, ErrRangeCacheNotAllowed
 		}
 	} else {
 		if len(opt.Fields) > 0 {

```

**Comment by travisturner** [comment]
@jaffee we had discussed moving fields into a hidden frame so that fields could simply be applied to the index without needing to specify `RangeEnabled`. I'm not opposed to applying a patch like this, but do you think there's a reason to keep fields associated to a user-defined frame?

**Comment by jaffee** [comment]
ah, yes, I remember that conversation now. 

I do like the hidden frame approach - that way, one doesn't have to specify field and frame when querying which was usually redundant.

Having frames associated to fields might have some merit - I can imagine some kind of frame based field caching similar to how we cache rows now, but I'm not sure I have a concrete use case. The use case I do have is ingesting weird data that might have an integer associated with a key sometimes and a string other times - having the ability to have frames and fields makes the generic ingestion code a bit more natural.

I suppose we could do both... if you set a field without specifying a frame it goes into the hidden field - we probably wouldn't want to deprecate the current approach right away anyhow.

**Comment by travisturner** [comment]
@jaffee this restriction was removed from `cluster-resize` in #935

**Comment by travisturner** [comment]
Unless you think we should backport this to `v0.8`, we can probably close this.
