### ISSUE TITLE
Need a broadcast message for CreateView event

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1072]
### Expected behavior
When a `view` is created on a node in a multi-node cluster, we need the `CreateView` event to be broadcast via `SendSync` to the other nodes in the cluster. When testing `FrameRestore`, the remote cluster is asking the source cluster for a list of views and is getting back an empty list (depending on which node is asked).

### Actual behavior
Other nodes aren't aware of the new `view`.

### Steps to reproduce the behavior
intermittent failures in  `TestMain_FrameRestore`

**Comment by yuce** [comment]
Can we close this?

**Comment by travisturner** [comment]
fixed by #1073 in `cluster-resize` branch
