### ISSUE TITLE
Getting Started stargazer import fails

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1085]
### Expected behavior
The Getting Started guide works without error.

### Actual behavior
The Getting Started instruction to import data from `stargazer.csv` fails because the csv contains timestamp data, but the `stargazer` frame is not configured to handle timestamps.

Running the command:
```
pilosa import -i repository -f stargazer stargazer.csv
```
results in the error:
```
err=time quantum not set in either index or frame
```

### Steps to reproduce the behavior
Follow the Getting Started up until `pilosa import -i repository -f stargazer stargazer.csv`

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
MacOSX

**Comment by travisturner** [comment]
@yuce commit ab19576dbba6c8d1a8183dcb7efc0cdcba4ddac2 removes frame options from the Getting Started guide. Was there a reason for removing the `timeQuantum` portion of frame options? Is there any reason why we shouldn't add that back?

**Comment by travisturner** [comment]
@yuce @jaffee see PR #1007

**Comment by yuce** [comment]
@travisturner There is no query in the guide that makes use of time quantums. Ideally we should have some interesting queries which uses time quantums, otherwise we need to remove time quantums from the sample data.

**Comment by travisturner** [comment]
There is an example query here that references time quantums: https://www.pilosa.com/docs/latest/query-language/#range-queries

**Comment by travisturner** [comment]
I suggest we change that frame creation instruction to:
```
curl localhost:10101/index/repository/frame/stargazer \
     -X POST \
     -d '{"options": {"timeQuantum": "YMD"}}'
```
I'll submit a PR for this and let you review.

**Comment by yuce** [comment]
@travisturner I've just submitted https://github.com/pilosa/pilosa/pull/1086

**Comment by yuce** [comment]
Removed `inverseEnabled` option.
