### ISSUE TITLE
Invert Attr store dependency

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1096]
See #1093 

This one might be a bit more difficult as the API is not so straightforward (transactions, etc.) and is highly performance sensitive. We'd want to maintain performance, but not make the interface so specific that swapping out a different implementation (other than bolt) is overly difficult.

**Comment by gedw99** [comment]
I am going to embed on mobiles and desktops  Whar DB are you planning to provide implementations of the interface for ?

Some I use:

Boltdb 
Badger 
Memory ( for testing )

**Comment by travisturner** [comment]
Currently we just have the `boltdb` implementation (in #1169). I think we should add a `memory` implementation for testing and replace the `boltdb` import in `test/attr.go`.

**Comment by gedw99** [comment]
sounds perfect. Will be easy to ad others later.
