### ISSUE TITLE
Wrong Range Result

### ISSUE THREAD

**Issue by FerrariHuang** [pilosa/pilosa#1103]
For bugs, please provide the following:

### Expected behavior
I created a frame with same named field. And then I imported the CSV file. I was sure that there is no field=0 in the CSV. So I should not gotten the result with field=0.
### Actual behavior
But I queried and got hundreds results with field=0. As I checked carefully, The real field value of them should bi field=32/64/96/128. And I can still got them in within the right results
### Steps to reproduce the behavior
curl localhost:10101/index/repository/frame/test -X POST -d '{"options":{"rangeEnabled":true,"fields":[{"name":"test","type":"int","min":-200,"max":2000}]}}'
I tried some names. Not every name will met the same issue. And I'm not quit sure whether it will related with the machine. Please use index=repository, frame=test, field=test to reproduce the behavior.
I will send you a mail with the CSV file.
### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
The issue happened in two different Linux OS and both cluster and solo.
### Success criteria (What criteria will consider this ticket closeable?)
Please just fix the issue ASAP and mail me. It has already impacted our go-live.

**Comment by FerrariHuang** [comment]
![same_bit_two_values](https://user-images.githubusercontent.com/21277977/36009473-2f1f68f2-0d87-11e8-94f0-86c76b2417dd.png)
Here I attached the screenshot to show the two result sets. The bit=1720652 is in both right and wrong result set.

**Comment by FerrariHuang** [comment]
Update: the bug is not caused by the same name of frame and field. Even if I changed the field name, I will still got the wrong result set. And the wrong value would not just =0 but also =others. And I got different wrong result set while I changed the frame name.
 An other typical issue is:
1. I queried value=3/4/5 separately and all got more results than the correct number.
2. I queried value><[3,5] and got more results than the summery of value=3/4/5.

The query result of value=3:
![field3](https://user-images.githubusercontent.com/21277977/36011638-b8f1539a-0d93-11e8-86f6-9506a40f8e95.png)
The query result of value=4:
![field4](https://user-images.githubusercontent.com/21277977/36011639-b91b600e-0d93-11e8-884c-b02528e1ea66.png)
The query result of value=5:
![field5](https://user-images.githubusercontent.com/21277977/36011641-b943645a-0d93-11e8-9c20-6ddf21001ffc.png)
The query result of value><[3,4,5]:
![field345](https://user-images.githubusercontent.com/21277977/36011642-b96f416a-0d93-11e8-8d9b-ab6ea8dd5541.png)

**Comment by travisturner** [comment]
@FerrariHuang thanks for the detailed bug report. That was very helpful.

We found the bug causing this issue and pushed a fix for it. This fix is contained in the latest release: [v0.8.6](https://github.com/pilosa/pilosa/releases/tag/v0.8.6)

Let me know if you're still experiencing any problems.

**Comment by FerrariHuang** [comment]
@travisturner Thank you for your quick feedback. I will try it tomorrow and will response it after testing.

**Comment by FerrariHuang** [comment]
![wrong_number_-9_-11](https://user-images.githubusercontent.com/21277977/36073965-eb5a3f5e-0f73-11e8-9473-fd91324dc571.png)
@travisturner v0.8.6 has the right results of value=0. But the results of value=-9 and value=-11 is still wrong. The wrong numbers are both one more than the right numbers.

**Comment by travisturner** [comment]
Thanks again @FerrariHuang. I submitted a fix for this in #1110. Once we get that reviewed and merged we'll cut another release.

**Comment by travisturner** [comment]
@FerrariHuang The latest fix is in https://github.com/pilosa/pilosa/releases/tag/v0.8.7

**Comment by FerrariHuang** [comment]
![wrong_range](https://user-images.githubusercontent.com/21277977/36154093-4beb8038-110b-11e8-81a9-a680da2c4f9f.png)
@travisturner Thank you for your response. But the range operator >< still get the wrong results. Actually, the correct summery between [-11,-1] should be 62879. But I queried and got two different wrong numbers.

**Comment by FerrariHuang** [comment]
@travisturner Chinese New Year Holiday is coming. Sorry that I will not response you in the next days. I will go back to the office on Feb 22. Hope to see your next release version at that time. Thanks.

**Comment by travisturner** [comment]
@FerrariHuang Thanks again for the feedback and bug report. We added more test coverage to our roaring implementation and found a few bugs related to this issue. I verified that one of the bug fixes addresses the problem you were seeing. You can see that work in #1115. We pushed out a new release containing the bug fixes: [v0.8.8](https://github.com/pilosa/pilosa/releases/tag/v0.8.8)

**Comment by FerrariHuang** [comment]
@travisturner Thank you for your hard work. I cannot find any more issue now.
