### ISSUE TITLE
Kubernetes Pilosa

### ISSUE THREAD

**Issue by tgruben** [pilosa/pilosa#1113]
Explore 
running pilosa in a kubernetes cluster 
horizontal pod autoscalling. 
determine what is involved in making pilosa available via helm

**Comment by jaffee** [comment]
blocked on #896

**Comment by bruth** [comment]
This no longer blocked?

**Comment by travisturner** [comment]
This is no longer blocked by #896, but there are some issues with the way Pilosa binds to external addresses which need to be addressed before it will work with Kubernetes. Issues #1129 and #1590 are related.

**Comment by jaffee** [comment]
see also github.com/pilosa/infrastructure/issues/34

**Comment by yuce** [comment]
Closing this, since we support Kubernetes and have a Helm chart.
