### ISSUE TITLE
Don't use StatusInternalServerError for valid responses

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1126]
In a multi-node cluster, a query like `Count(Range(frame=f, invalidField<0))` where `invalidField` does not exist, the remote nodes are returning a `QueryResponse` in the body having `Err: "field not found"` and an http status code `http.StatusInternalServerError`. The problem with this is that the internal client is assuming that any response with status code `StatusInternalServerError` has an unstructured response body. Details below:

In `handler.go` method `handlePostQuery()`, if the response error `resp.Err` is not nil, then we set the status code to `http.StatusInternalServerError`. Then in `client.go` method `ExecuteQuery()`, if the `resp.StatusCode` is anything but `200` we assume that the payload is not structured and just return the body as the error. That's where the errant return character is coming from.

It seems to me that we could be a little more specific with our status codes. If we're returning a valid response (i.e. a valid `QueryResponse`, even if it contains an error), we should handle that and unmarshal it correctly and not necessarily treat is as a `StatusInternalServerError`.

I don't know if we should return a `StatusOK` (200) in this case, or some other error code. Or perhaps continue to use the same error code (500) but try to unmarshal the body either way.

**Comment by travisturner** [comment]
One thing I considered doing was to reorganize the logic in `client.ExecuteQuery()` so that we try to unmarshal the response body to an `internal.QueryResponse{}` before we check the http StatusCode, but I realized that this pattern of returning the http body on error occurs throughout the client code, so I'm going to think about it a bit more.

**Comment by jaffee** [comment]
@alanbernstein I think this relates to some work you've been doing. We definitely want to ensure that we've got our status code ducks in a row before 1.0

**Comment by jaffee** [comment]
has anyone done work on this? seems like we still might return InternalServerError from a query in a lot of cases.

**Comment by travisturner** [comment]
I added some error codes in the `http` package, but we haven't addressed this yet.
