### ISSUE TITLE
Proposal: deprecate input definition

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1157]
### Description
As part of our API shrinking initiative in the march to 1.0, I think we should deprecate the input definition functionality.

It's fairly limited in its capability (compared to automatic indexing in the PDK), and hasn't been widely used. The API is also fairly complicated which I think hinders adoption, and the performance is largely untested.

Components:
- Code (pilosa/pilosa)
- clients?
- docs
- blog post

**Comment by travisturner** [comment]
I support this.

**Comment by alanbernstein** [comment]
Added deprecation warnings to two blog posts in https://github.com/pilosa/www/pull/223. I suggest we delete the input definition blog post, but not just yet, since it has had a few views recently.
