### ISSUE TITLE
Failure to connect to gossip seed with default config on single-node cluster (no route to host)

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#1172]
### Expected behavior

Starting "pilosa server" with no arguments should bring up a running single-node cluster without logged errors.

### Actual behavior

Since default gossip seed is localhost:14000, it tries to connect to that even with a single node cluster. The following error is logged (does not seem to affect performance):
```
...
2018/03/19 15:00:04 [DEBUG] memberlist: Failed to join fe80::1: dial tcp [fe80::1]:14000: connect: no route to host
...
```
### Steps to reproduce the behavior

Run `pilosa server` with no config.

**Comment by travisturner** [comment]
This is caused by memberlist doing `net.LookupIP("localhost")`, which will return 
```
[
    ::1,
    fe80::1,
    127.0.0.1,
]
```
based on a typical macOS `/etc/hosts` file:
```
127.0.0.1   localhost
255.255.255.255 broadcasthost
::1             localhost
fe80::1%lo0 localhost
```
That `fe80::1` is an [IPv6 link-local address](https://superuser.com/questions/241642/what-is-the-relevance-of-fe801lo0-localhost-in-etc-hosts) which has no route.

**Comment by travisturner** [comment]
@codysoyland do you think it's worth trying to address this in some way?

**Comment by codysoyland** [comment]
Yeah, I understand that `fe80::1` is localhost and that there is not a memberlist listener on that port at that point in the initialization. I just don't understand why a single-node configuration would need a gossip seed.

The way this default works is if pilosa is started with no seeds -- the default in fact -- more explicitly: `pilosa server --gossip.seeds=`, then the value of `Seeds` will be replaced with "localhost:14000" in `NewGossipMemberSetWithTransport`:
```go
    if len(cfg.Gossip.Seeds) == 0 {
        g.config.gossipSeeds = []string{fmt.Sprintf("%s:%d", host, port)}
    }
```
This causes the error, which while innocuous, is annoying and can be misinterpreted. Does the code above need to exist for any reason?

**Comment by yuce** [comment]
Related: https://github.com/pilosa/pilosa/issues/870
