### ISSUE TITLE
remove RangeEnabled entirely

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1194]
### Description
What's the point of having a boolean option on frames for whether or not they're allowed to have BSI fields?

I may be wrong, but as far as I can tell, it adds complexity to the API and codebase for no benefit - please discuss.

1. (pre v0.9) Deprecate RangeEnabled. This includes making the option do nothing, adding deprecation warnings when it is used (in clients, etc.), and giving notice in the docs that it's being removed.

2. (post v0.9) Remove RangedEnabled from the API and update all structs and protobuf definitions to completely expunge it (breaking change).

### Success criteria (What criteria will consider this ticket closeable?)
If there are no clear drawbacks, remove the RangeEnabled option entirely from the codebase and API.

**Comment by yuce** [comment]
A frame may be created without range fields and they can be added later. If a frame doesn't have `rangeEnabled=true` it is not possible to add range fields later. As far as I know, that's the only reason that option is required.

**Comment by jaffee** [comment]
Thanks @yuce. Just to be clear, what I'm proposing is allow any frame to have fields added at any time with no way of restricting which frames can or can't have fields.

**Comment by jaffee** [comment]
As there seems to be no dissent, I'm going to start deprecating rangeEnabled. We can remove it after the 0.9 release.
