### ISSUE TITLE
deprecate rangeEnabled in non-pilosa repos

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1206]
### Description
Remove unnecessary references to RangeEnabled, and add deprecation warnings to clients when RangeEnabled is used. This will definitely include the clients, and PDK. Let's check through through other public and private repos as well.

Creating this issue in github.com/pilosa/pilosa to avoid creating 8 other issues in disparate repos.

Blocked on #1205 - once that's merged, this should proceed.

**Comment by yuce** [comment]
Python and Java clients have this on their `master`.
Implemented for the Go client in PR: https://github.com/pilosa/go-pilosa/pull/129
We need to update PDK deps to use the latest master of Go client when the PR ^ is merged.

**Comment by yuce** [comment]
This is implemented in all clients. Closing.
