### ISSUE TITLE
Proposal: remove cpu profiling config options

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1217]
### Description
I don't think we use the cpu profiling config options (profile.cpu and profile.cpu-time) enough to justify their existence. They are really only useful for profiling on startup since the /debug/pprof endpoint is registered if you need a profile while running. I personally have never used them as far as I can remember. Removing them simplifies our configuration, our docs, and the command code which starts pilosa.

Please add feedback.

**Comment by travisturner** [comment]
I don't use them.
@tgruben may have better feedback.

**Comment by tgruben** [comment]
wack it, i only use the endpoint
