### ISSUE TITLE
fix table in pdk docs

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1227]
per comment on https://github.com/pilosa/pilosa/pull/1213

**Comment by jaffee** [comment]
@alanbernstein did you do this already?

**Comment by alanbernstein** [comment]
Yes, the updated version is live now, with more columns rather than an additional table. It's better than it was, but still might be confusing to a newcomer.

**Comment by jaffee** [comment]
ok, I'm gonna close this
