### ISSUE TITLE
Clients should get slice width from cluster instead of hardcoding.

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1232]
### Description

It is sometimes useful to recompile Pilosa with a different slice width (which is defined as a constant, perhaps unnecessarily for performance). This breaks imports with clients which use the slice width, however. Clients should ask Pilosa for the slice width and use that rather than relying on a hardcoded value.

It's possible that slice width info needs to be added to the Pilosa status or schema endpoint (or wherever makes sense).

### Success criteria (What criteria will consider this ticket closeable?)
A stock Pilosa client can be used with a Pilosa which has been custom compiled with a different slice width.

**Comment by yuce** [comment]
Go and Java clients support setting the slice width manually (but not currently exposed publicly) but I agree that they should get this (and other similar settings) from the server. Ideally, the clients would read all relevant settings from a server endpoint when they are created (or before their first use).
