### ISSUE TITLE
/id, /hosts and /status endpoints return the same information

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1235]
For feature requests, please provide the following:

### Description

We can remove `/id` and `/hosts` endpoints without losing any functionality, `/status` endpoint is sufficient, if we add a `localID` key to it:
```
$ curl localhost:10101/status
{"state":"NORMAL","nodes":[{"id":"c0010bfb-6bd0-47ca-8f10-72cfd812f152","uri":{"scheme":"http","host":"localhost","port":10101},"isCoordinator":true}]}
$ curl localhost:10101/hosts
[{"id":"c0010bfb-6bd0-47ca-8f10-72cfd812f152","uri":{"scheme":"http","host":"localhost","port":10101},"isCoordinator":true}]
$ curl localhost:10101/id
c0010bfb-6bd0-47ca-8f10-72cfd812f152
```

### Success criteria (What criteria will consider this ticket closeable?)

`/id` and `/hosts` endpoints are removed. `/status` endpoint contains the `localID` of the node.

**Comment by jaffee** [comment]
This seems like a pretty good idea - where are /id and /hosts currently used?

**Comment by yuce** [comment]
Internal has the `NodeID` function which loads `/id`, but as far as I see that function is not used anywhere. There are some tests and some doc that uses/refers to the `/id` endpoint. `/hosts` is referenced in a few docs, but not used anywhere.

**Comment by jaffee** [comment]
sounds good to me - let's nuke it!
