### ISSUE TITLE
Handle Node failure/restart

### ISSUE THREAD

**Issue by tgruben** [pilosa/pilosa#1249]
A single node of a cluster fails as a result of OOM and restarts.  The cluster status remained at NORMAL, during the startup of the failed node.  Once the node was completely up, queries work as expected.

### Expected behavior
cluster status would change to something not normal until the node has returned to the cluster
### Actual behavior
cluster status stays at NORMAL during the whole window of node failure

**Comment by jaffee** [comment]
If replication > 1, then I would expect cluster status to stay NORMAL. I agree though that if replication == 1, then the cluster should not be serving queries.

**Comment by jaffee** [comment]
I think there are some other issues related to this - I've seen situations where one node in the cluster is stuck in state "STARTING" while the others are in "NORMAL". I think if a node dissapears from the cluster, we need to put everything into state "STARTING" (or similar) until it rejoins.

**Comment by jaffee** [comment]
Digging into this found another related issue which is that memberlist won't allow a node to leave the cluster and then rejoin again with a different address but the same ID/Name. I've filed a ticket with them [here](https://github.com/hashicorp/memberlist/issues/157)
