### ISSUE TITLE
Fix help in web gui for 0.9.0

### ISSUE THREAD

**Issue by addos** [pilosa/pilosa#1277]
### Expected behavior
It looks like in pilosa 0.9.0 that rowID is now row, and columnID is now col.
The webui has a ? in it with hints of what the parameters should be. Those should show the different functions with col= and row= to avoid having people be confused about what the parameter should be.

### Actual behavior
Instead the help shows rowID and columnID

### Steps to reproduce the behavior
Click the ? in the webui

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Pilosa 0.9.0

**Comment by codysoyland** [comment]
Thanks for reporting, @addos! Sorry for the confusion -- we evidently missed that.
