### ISSUE TITLE
Proposal: make HTTP responses more clear and consistent

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#1280]
### Description
Some of our responses could stand to be updated.

Successfully creating an index or a frame returns `{}`, which is strange, and when the entity already exists, the response is a non-json string. One alternative is to change this to match the response from SetBit/ClearBit, summarized in this table:

| request | result | current response | proposed response |
| ------------- | ------------- |------------- |------------- |
| create index | create | `{}` | `{"results":[true]}` |
| create index | already exists | `creating index: index already exists` | `{"results":[false]}` |
| create frame | create | `{}` | `{"results":[true]}` |
| create frame | already exists | `creating frame: frame already exists` | `{"results":[false]}` |

More sensibly: 

| request | result | current response | proposed response |
| ------------- | ------------- |------------- |------------- |
| create index | create | `{}` | `{"success":true}` |
| create index | already exists | `creating index: index already exists` | `{"success":false, "error":"creating index: index already exists"}` |
| create frame | create | `{}` | `{"success":true}` |
| create frame | already exists | `creating frame: frame already exists` | `{"success":false, "error":"creating frame: frame already exists"}` |
| delete index | delete | `{}` | `{"success":true}` |
| delete index | not found | `{}` | `{"success":false, "error": "index not found}` |
| get index schema | not found | `index not found` | `{"success":false, "error": "index not found"}` |
| delete frame | delete | `{}` | `{"success":true}` |
| delete frame | not found | `{}` | `{"success":false, "error": "frame not found}` |
| create field | create | `{}` | `{"success":true}` |
| create field | already exists | `creating field: field already exists` | `{"success":false, "error": "creating field: field already exists"}` |
| id | get | `40a891fa-243b-4d71-ae24-4f5c78a0f4b1` | `{"id": `40a891fa-243b-4d71-ae24-4f5c78a0f4b1"}` |

Of course, some of these responses might be more convenient as plain text for whatever reason. If that's the case, we can make exceptions.

Perhaps a simpler option is to replace all `{}` responses with empty responses, and ensure that the HTTP response codes are appropriate. For example, POST to `/index/indexname` returns `200 OK`, but might return `201 CREATED` instead.

### Success criteria (What criteria will consider this ticket closeable?)
HTTP responses are as clear and consistent as possible.

**Comment by travisturner** [comment]
I like the idea of being consistent with the query result format, but it's a bit odd to have a `create index` response be plural and contain a list.

I also think we lose information going from `creating index: index already exists` to `{"results":[false]}`. Perhaps an alternative is to ensure that everything is a json response with a useful message as one of the json values. In other words, if the result of the index creation is `false` it might also be useful to understand why.

**Comment by alanbernstein** [comment]
I added another version that makes a little more sense.

**Comment by travisturner** [comment]
Currently `delete index` does not return an "index not found" error when deleting an index that does not exist. This means that all delete index request come back as `{"success": true"}`. Is there any reason why we shouldn't modify the API methods to return an error on non-existent indexes (and fields)?

**Comment by travisturner** [comment]
It seems we no longer have the `/id` endpoint, so I'm not addressing that in #1433.

I'm not exactly sure which endpoint "get index schema" is referring to. Is that `/index/{index}`?
Currently that endpoint returns:
```
{"name":"i","fields":[{"name":"f","options":{"type":"set","cacheType":"ranked","cacheSize":50000}}]}
```
Does it make sense to incorporate `"success":true` into that? Does it only apply when index is not found?
