### ISSUE TITLE
Metalinting meta ticket

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1287]
### Description
There are a number of automated checks we can take advantage of to improve our codebase. The [gometalinter](https://github.com/alecthomas/gometalinter) tool will run lots of these concurrently and report its findings. This includes things like dead code, unecessary if statements, redundant arguments, unchecked errors, etc. Gometalinter can run with a configuration file which tells it which checks to run.

I propose that we run each check, and fix everything that makes sense to fix. Once we have a particular check running cleanly on all of Pilosa, we can add it to gometalinter's config in CI, so that we catch any regressions immediately. We'll need:

1. a ticket to set up gometalinter in CI (#1288)
2. a ticket to identify all checks which should be running continuously. (#1288)
3. breakout tickets for each check identified in (2) to fix all the issues, and add the check to CI

### Success criteria (What criteria will consider this ticket closeable?)
Gometalinter runs automatically in CI, and any checks which are reasonable to run (generate no false positives) are running, and we've fixed all problems identified by these checks.

**Comment by codysoyland** [comment]
The majority of the metalinter checks are now in place (tickets tagged `metalinter`), and additional checks are ticketed, so I would consider this ticket done.
