### ISSUE TITLE
Run gometalinter in CI

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1288]
### Description

As mentioned in #1287, set up [gometalinter](https://github.com/alecthomas/gometalinter) to run in CI, with configuration such that we can add new checks as we fix issues and get them to run cleanly.

### Success criteria (What criteria will consider this ticket closeable?)
gometalinter is run automatically by CI with no checks enabled initially

**Comment by codysoyland** [comment]
Fixed in #1504
