### ISSUE TITLE
List gometalinter checks which can run continuously

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1289]
### Description

As described in #1287, we'd like to run gometalinter in CI. We need to identify which checks we can run automatically that won't generate false positives. We'll list these checks here and create breakout tickets for each of them to (a) fix all the issues identified by the check and (b) add the check to CI.

### Success criteria (What criteria will consider this ticket closeable?)
We'll close this ticket at the same time as #1287 once all checks are identified and in CI.

**Comment by codysoyland** [comment]
The following linters have errors (annotated with number of errors):

- deadcode: 16
- dupl: 619
- errcheck: 99
- gas: 34
- gochecknoglobals: 48
- gochecknoinits: 20
- goconst: 19
- gocyclo: 178
- gofmt: 8
- goimports: 1
- golint: 195
- gosimple: 0
- ineffassign: 8
- interfacer: 3
- lll: 1856
- maligned: 7
- megacheck: 76
- misspell: 4
- nakedret: 14
- staticcheck: 0
- structcheck: 3
- unconvert: 60
- unparam: 52
- unused: 83
- varcheck: 4
- vet: 53
- vetshadow: 46

Note that `megacheck` combines the following linters into one:

- gosimple
- unused
- staticcheck

This is not applicable:

- safesql

These linters pass:

- gotype
- gotypex

**Comment by codysoyland** [comment]
There are still a few remaining metalinter tickets, but most of the linters are now in CI and enabled. See #1504 and tickets with label `metalinter`.
