### ISSUE TITLE
Broadcast/Messaging simplification and unification

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1317]
### Description
Pilosa currently employs several, very similar, interfaces to send/receive/handle messages among nodes in the cluster. We should combine these into a single interface which manages inter-node messaging.

### Success criteria (What criteria will consider this ticket closeable?)
There is a single, obvious method by which a node sends and receives messages.

**Comment by jaffee** [comment]
Related to #1247 - can we combine these?

**Comment by travisturner** [comment]
closing as a duplicate of #1247
