### ISSUE TITLE
PQL Simplification

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1318]
### Description
The goal here is to simplify PQL and ensure that it lines up with the internal data structure. This should be informed by #1208, #1144, #1315, and #1314.

```
Current                                                                   Proposed
Bitmap(frame=aaa, row=10)                                                 Row(aaa=10)
Range(frame=bbb, fld > 20)                                                Row(bbb > 20)
SetBit(frame=aaa, row=10, col=100)                                        Set(aaa=10, col=100)
SetFieldValue(frame=bbb, col=200, fld=8)                                  Set(bbb=8, col=200)

Count(Bitmap(frame=aaa, row=10))                                          Count(Row(aaa=10))
Union(Bitmap(frame=aaa, row=10), Bitmap(frame=aaa, row=11))               Union(Row(aaa=10), Row(aaa=11))
Union(Bitmap(frame=aaa, row=10), Range(frame=bbb, bsi < 30))              Union(Row(aaa=10), Row(bbb<30))

TopN(frame=aaa, n=25)                                                     TopN(field=aaa, n=25)
TopN(Bitmap(frame=aaa, row=10), frame=aaa, n=25)                          TopN(Row(aaa=10), field=aaa, n=25)

Range(frame=ts, row=1, start="2010-01-01T00:00", end="2017-03-02T03:00")  Row(ts=1, start="2010-01-01T00:00", end="2017-03-02T03:00")
```

### Success criteria (What criteria will consider this ticket closeable?)
PQL no longer refers to `bitmap`, and the frame specification is simplified. It's possible that `Row()` shouldn't be overloaded to handle `Bitmap()`, `Range() (time)`, and `Range() (bsi)` queries. That can be decided during implementation. If leaving `Range()` in place makes the most sense then that's ok.

**Comment by alanbernstein** [comment]
Other considerations in simplifying PQL:

- BETWEEN syntax should be updated from `x >< [10, 20]` to `10 < x < 20`
- If `Row` is overloaded to handle both `Bitmap` and `Range`, then there appears to be a missing feature where `Row(aaa > 10)` (for a non-BSI frame) looks like it should work, but doesn't. We should at least support that syntax, or alternatively, go through with some version of https://github.com/pilosa/pilosa/pull/1122

**Comment by alanbernstein** [comment]
The `SetBit(frame=aaa, row=10, col=100)` -> `Set(aaa=10, col=100)` changes introduce a keyword conflict. Currently, any frame name that matches `^[a-z][a-z0-9_-]{0,63}$` is valid. With the change, a frame named `col` is a problem. I think there is a simple fix for this in the parser:

```
		// Add key/value pair to arguments.
-               args[key] = value
+               if _, ok := keywords[key]; ok {
+                       args[key] = value
+               } else {
+                       // Unknown keyword -> frame key
+                       args["frame"] = key
+                       args["row"] = value
+               }
```

This requires forbidding all keywords as frame names.

**Comment by alanbernstein** [comment]
Some discussion with @travisturner and @jaffee:

`frame`, `row` will no longer be needed after these changes. We've already discussed deprecating `tanimotoThreshold`. `col` can be eliminated by changing the `Set` query to `Set(100, aaa=10)`, with the added benefit that we can do `Set(100, aaa=10, bbb=20, ...)` to set multiple bits in a column. If we could make other simple syntax adjustments to eliminate ALL the other keywords, we could make the "frames as keywords" change with minimal trouble. This might be challenging:

```
ids
field
filters
timestamp
n
threshold
start
end
```

Another approach is something like `TopN(field=aaa, Options(n=10))`, which is a bit clunky, but might be preferable to forbidding reserved frame names.

**Comment by travisturner** [comment]
It doesn't seem like there's a problem with any of the `TopN` related arguments, because `TopN` doesn't specify a field as an argument; it explicitly uses `field=f`. So that would remove `field`, `n`, `ids`, and `filters`.

`threshold` should be deprecated with Tanimoto

That leaves:
```
# SetBit()
timestamp

#Range()
start
end
```

**Comment by travisturner** [comment]
Also, we should recognize that the format `Set(100, aaa=10, bbb=20, ...)` wouldn't support `time` fields, which is the need for the `timestamp` argument.

**Comment by alanbernstein** [comment]
I believe Tanimoto is controlled with just `tanimotoThreshold`, and `threshold` provides a distinct function of filtering by minimum count. I don't know if that's documented anywhere.

**Comment by travisturner** [comment]
Ah, you're right. I forgot about that option.

**Comment by alanbernstein** [comment]
What's the use case for `threshold`? We could deprecate that as well

**Comment by jaffee** [comment]
@alanbernstein can you update the description with where we actually landed on all these changes?

I know that Set is becoming `Set(<col>, <frame>=<rowid>..., <timestamp>?)`, but I'm not sure about most of the others._

**Comment by jaffee** [comment]
this is done, right?

**Comment by alanbernstein** [comment]
Yep
