### ISSUE TITLE
Remove Backup/Restore endpoints

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1319]
### Description
The current implementation of backup/restore is really more similar to "dump" in various databases. For now we want to remove these endpoints so that we don't have to provide support for what is likely an unnecessary feature. The goal is to follow up this removal with a well planned backup/restore feature that is cluster-aware and adheres to acceptable backup strategies.

### Success criteria (What criteria will consider this ticket closeable?)
The backup/restore endpoints (and internal handlers) are removed, and ideally a new issue is created to plan/propose a true backup/recovery feature.

**Comment by alanbernstein** [comment]
Starting over on backup/restore functionality will allow us to consider https://github.com/pilosa/pilosa/issues/725 and other proposals.
