### ISSUE TITLE
Update Documentation for v1.0

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1320]
This is really a placeholder ticket for all documentation updates needed to support the 1.0 release.
We can use this ticket as an umbrella ticket, and create breakout tickets for individual tasks.

Some example areas likely requiring updates:
- Examples
- Tutorials
- Client READMEs

**Comment by alanbernstein** [comment]
Client readmes have been reviewed and updated recently, so should only need editing to reflect further updates/API changes.

We could do with more examples, but also the chemical similarity section in particular needs to be substantially rewritten.

The architecture docs page is nearly empty, I think that page should have more content or be removed.

https://github.com/pilosa/www/issues/227
