### ISSUE TITLE
Update client libraries to support v1.0

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1321]
This is a placeholder ticket, and likely requires individual tickets in each of the respective client libraries. Once created, those can be referenced and tracked here.

**Comment by yuce** [comment]
Individual client library issues:
* https://github.com/pilosa/python-pilosa/issues/102
* https://github.com/pilosa/go-pilosa/issues/139
* https://github.com/pilosa/java-pilosa/issues/98

**Comment by travisturner** [comment]
The lua issue is still open, but I'm going to close this placeholder ticket since we're tracking that in the `lua-pilosa` repo.
