### ISSUE TITLE
Modify Field (prev. Frame) creation options

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1345]
With #1314 changing `Frame` to `Field`, and with `bsiGroup` (prev. `field`) becoming an internal implementation where a `Field` of type `int` contains a single `bsiGroup`, I'm proposing that `Field` creation options be the following (you can see what they currently are [here](https://www.pilosa.com/docs/latest/api-reference/#create-frame)):
```
CREATE field type='default', cacheType='ranked', cacheSize=10000
CREATE field type='int', min=0, max=1023
CREATE field type='time', quantum='YMD'
```
I'm not sure what `default` should be. Originally I had written `enum`, but I don't think that really represents what it is.

Anyone have any better ideas, or feedback on the suggestions above?

**Comment by jaffee** [comment]
This is making me realize that I'm not sure I understand how frames using time quantums work with TopN.

For field type 'default', how do we feel about 'set' since the rows describe a set of items that the columns may or may not be associated with.

**Comment by travisturner** [comment]
I don't think time quantum frames should work with TopN at the moment. Really what I think you would expect would be the equivalent of `TopN(Range(frame="t", start=??, end=??), frame="set", n=20)`.  That would require maintaining a `field type='set', cacheType='ranked', cacheSize=10000` Frame in addition to the `time` Frame. We could do this internally, but then we'd need to modify `TopN()` to also take `start` and `end`. We currently don't support `TopN` on `int` Frames either, although I think it would be fairly straight forward to copy/modify `Max()` in a way that it returns columns based on the largest values.

**Comment by yuce** [comment]
I've added a couple of tickets to the Go client (need to create it for other clients as well) labeled with "1345" regarding the chages in this ticket and the related PR. I will add more, but feel free to add more issues regarding this ticket to the Go client and/or other clients.
