### ISSUE TITLE
remove views from API responses

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1349]
### Description

Several API endpoints have view names in their responses. (like /schema, /slices/max). Since we're removing views from exposure in the API, it is probably confusing to refer to them in API responses, so I think we should modify the responses to not include views.

### Success criteria (What criteria will consider this ticket closeable?)

API responses don't reference views either explicitly or implicitly.

**Comment by travisturner** [comment]
I started to look into this and realized that `Holder.SyncHolder()` uses `Schema` (and hence, views). We'll need to come up with an alternative for internal, inter-node functions like sync.

**Comment by travisturner** [comment]
this can be addressed with #1371 by using an `/internal` endpoint.

**Comment by jaffee** [comment]
blocked by #1371 - this ticket will involve creating an /internal/schema endpoint so that we don't have to rewrite the syncer
