### ISSUE TITLE
Improve validation and representation of FieldOptions

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1361]
### Description
Based on the work from #1345 where `FieldOptions` were defined as:
```
CREATE field type='default', cacheType='ranked', cacheSize=10000
CREATE field type='int', min=0, max=1023
CREATE field type='time', quantum='YMD'
```
We need to decide how best to validate options on field creation.
For example, should the following raise an error:
```
{"options":{"type":"int", "cacheType": "ranked"}}
```
Field type `int` doesn't take a `cacheType`. Currently, we just ignore this, but perhaps we should raise an error.

Also, when fields are displayed in the `schema`, it can look like this:
```
"options":{"type":"int","cacheType":"none","max":10000}
```
Two issues here: 
1. `cacheType`, even though it's none, doesn't apply to `int` fields
2. `min` is excluded because it is 0

### Success criteria (What criteria will consider this ticket closeable?)
We have defined and implemented how best to validate and display field options.

**Comment by jaffee** [comment]
Probably the easiest thing would be to have separate options structs for each field type - then we can use `Decoder.DisallowUnknownFields` and not use `omitempty` to get the behavior we want.
