### ISSUE TITLE
Crash on value overwrite

### ISSUE THREAD

**Issue by tgruben** [pilosa/pilosa#1400]
### Expected behavior
import the a new bsi value for the same column and the value is replaced
### Actual behavior
server crashes with dump
`unexpected fault address 0x4cfe028
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x4cfe028 pc=0x4396cdf]

goroutine 72 [running]:
runtime.throw(0x4735c84, 0x5)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81 fp=0xc42030cfe0 sp=0xc42030cfc0 pc=0x402d2a1
runtime.sigpanic()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/signal_unix.go:385 +0x273 fp=0xc42030d030 sp=0xc42030cfe0 pc=0x4042df3
github.com/pilosa/pilosa/roaring.(*Container).arrayAdd(0xc4201462a0, 0xc4201b0000, 0xc42030d280)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/roaring/roaring.go:1214 +0x2bf fp=0xc42030d110 sp=0xc42030d030 pc=0x4396cdf
github.com/pilosa/pilosa/roaring.(*Container).add(0xc4201462a0, 0x0, 0xc4201462a0)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/roaring/roaring.go:1179 +0x94 fp=0xc42030d138 sp=0xc42030d110 pc=0x4396a04
github.com/pilosa/pilosa/roaring.(*Bitmap).add(0xc4202cc480, 0x0, 0x89)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/roaring/roaring.go:169 +0x59 fp=0xc42030d160 sp=0xc42030d138 pc=0x4391539
github.com/pilosa/pilosa/roaring.(*op).apply(0xc42030d1f8, 0xc4202cc480, 0x0)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/roaring/roaring.go:2909 +0x73 fp=0xc42030d1c8 sp=0xc42030d160 pc=0x43a2663
github.com/pilosa/pilosa/roaring.(*Bitmap).Add(0xc4202cc480, 0xc42030d270, 0x1, 0x1, 0x0, 0x0, 0xc42003c070)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/roaring/roaring.go:158 +0x3f fp=0xc42030d218 sp=0xc42030d1c8 pc=0x439143f
github.com/pilosa/pilosa.(*Fragment).importSetValue(0xc4201c2240, 0x0, 0x20, 0x13, 0xc400000008, 0xc4202e2380, 0x4064c0d)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/fragment.go:531 +0xe3 fp=0xc42030d288 sp=0xc42030d218 pc=0x43d6e73
github.com/pilosa/pilosa.(*Fragment).importValue.func1(0xc429c360c0, 0x1, 0x1, 0xc429c360d0, 0x1, 0x1, 0xc4201c2240, 0x20, 0xc4202e2380, 0x4064c0d)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/fragment.go:1382 +0x89 fp=0xc42030d2d8 sp=0xc42030d288 pc=0x4401249
github.com/pilosa/pilosa.(*Fragment).importValue(0xc4201c2240, 0xc429c360c0, 0x1, 0x1, 0xc429c360d0, 0x1, 0x1, 0x20, 0x0, 0x0)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/fragment.go:1388 +0x117 fp=0xc42030d378 sp=0xc42030d2d8 pc=0x43db407
github.com/pilosa/pilosa.(*Field).ImportValue(0xc4202ea300, 0xc429c36068, 0x1, 0x1, 0xc429c36090, 0x1, 0x1, 0x0, 0x0)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/field.go:998 +0x7b0 fp=0xc42030d880 sp=0xc42030d378 pc=0x43d3550
github.com/pilosa/pilosa.(*API).ImportValue(0xc4202379d0, 0x47bac00, 0xc4201f7200, 0xc429c36064, 0x1, 0xc429c36065, 0x1, 0x0, 0xc429c36068, 0x1, ...)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/api.go:668 +0x2e1 fp=0xc42030d970 sp=0xc42030d880 pc=0x43aba81
github.com/pilosa/pilosa/http.(*Handler).handlePostImportValue(0xc4200ae7d0, 0x47ba0c0, 0xc4200c60e0, 0xc420144800)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/http/handler.go:811 +0x2c7 fp=0xc42030da70 sp=0xc42030d970 pc=0x445f537
github.com/pilosa/pilosa/http.(*Handler).(github.com/pilosa/pilosa/http.handlePostImportValue)-fm(0x47ba0c0, 0xc4200c60e0, 0xc420144800)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/http/handler.go:187 +0x48 fp=0xc42030daa0 sp=0xc42030da70 pc=0x4465078
net/http.HandlerFunc.ServeHTTP(0xc420216360, 0x47ba0c0, 0xc4200c60e0, 0xc420144800)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44 fp=0xc42030dac8 sp=0xc42030daa0 pc=0x4356c24
github.com/pilosa/pilosa/http.(*Handler).queryArgValidator.func1(0x47ba0c0, 0xc4200c60e0, 0xc420144800)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/http/handler.go:159 +0xcb fp=0xc42030db40 sp=0xc42030dac8 pc=0x44642db
net/http.HandlerFunc.ServeHTTP(0xc4202ee100, 0x47ba0c0, 0xc4200c60e0, 0xc420144800)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44 fp=0xc42030db68 sp=0xc42030db40 pc=0x4356c24
github.com/pilosa/pilosa/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201f3ce0, 0x47ba0c0, 0xc4200c60e0, 0xc420144800)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/vendor/github.com/gorilla/mux/mux.go:159 +0xed fp=0xc42030dc68 sp=0xc42030db68 pc=0x4443aad
github.com/pilosa/pilosa/http.(*Handler).ServeHTTP(0xc4200ae7d0, 0x47ba0c0, 0xc4200c60e0, 0xc420144600)
	/Users/toddgruben/go/src/github.com/pilosa/pilosa/http/handler.go:229 +0xde fp=0xc42030dd58 sp=0xc42030dc68 pc=0x4459b7e
net/http.serverHandler.ServeHTTP(0xc4200a5d40, 0x47ba0c0, 0xc4200c60e0, 0xc420144600)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2694 +0xbc fp=0xc42030dd88 sp=0xc42030dd58 pc=0x435993c
net/http.(*conn).serve(0xc4200d6780, 0x47bab40, 0xc4201876c0)`

**Comment by jaffee** [comment]
were you able to replicate this with a test within pilosa? would be nice to have a regression test

**Comment by tgruben** [comment]
yes, i added the test  TestImportCommand_BugOverwriteValue which would reproduce
