### ISSUE TITLE
[develop] Specifying field names with dash or quotes in Set queries results in parser error

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1414]
For bugs, please provide the following:

### Expected behavior

Field names can have dashes in them and/or they can be quoted with single or double quotes. E.g., `Set(1000, my-frame=100)` or `Set(1000, "myframe"=100)`

### Actual behavior

The server returns parser errors when fields have dashes in them (although those are valid field names). Quoting field names returns a different parse error.

### Steps to reproduce the behavior

```
$ curl localhost:10101/index/my-index -d '' -H "Accept: application/json"
{}
$ curl localhost:10101/index/my-index/field/my-frame -d '' -H "Accept: application/json"
{}
$ curl localhost:10101/index/my-index/query -d 'Set(1000, my-frame=100)' -H "Accept: application/json"
{"error":"parsing: parsing: \nparse error near fieldExpr (line 1 symbol 11 - line 1 symbol 13):\n\"my\"\n"}
$ curl localhost:10101/index/my-index/query -d 'Set(1000, "my-frame"=100)' -H "Accept: application/json"
{"error":"parsing: parsing: \nparse error near whitesp (line 1 symbol 10 - line 1 symbol 11):\n\" \"\n"}
```

**Comment by jaffee** [comment]
I'm not actually sure we want to allow quotes... especially before the equals sign. I guess it probably doesn't matter too much either way. 

Any opinions?

**Comment by yuce** [comment]
We used to allow it before, like: `field="foo-bar"` but probably we don't need need to support it anymore unless we will support spaces in field names.

**Comment by jaffee** [comment]
yeah, it feels a bit weird now that fields often come before an '='. Can't think why it'd make a difference though.
