### ISSUE TITLE
data races in TranslateFile

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1422]
### Steps to reproduce the behavior

`make test TESTFLAGS=-race` on current develop - from at least a5f9236f3a5918a77 through f59452a7e7e 

Seems to be the monitorReplication goroutine conflicting with normal usage of translator.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

OSX

**Comment by codysoyland** [comment]
Fixed in #1423
