### ISSUE TITLE
32-bit int overflow in TranslateFile MapSize

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#1430]
### Expected behavior

32-bit compiles

### Actual behavior

```./translate.go:94:10: constant 10737418240 overflows int```

### Steps to reproduce the behavior

`make release-build GOOS=linux GOARCH=386`

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Mac OS

**Comment by jaffee** [comment]
unfortunately, this has to be an int because it gets passed to syscall.Mmap which takes an int.

I guess you can't mmap more than 4GB on a 32 bit system.

We can define that constant separately in two files - one for 386, and one for everything else.
