### ISSUE TITLE
Update PQL parser to allow for line feeds

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1445]
The PQL parser is not allowing for line feeds:

```
curl localhost:10101/index/repository/query \
     -X POST \
     -d 'Intersect(
            Row(stargazer=14),
            Row(stargazer=19)
        )'

{"error":"parsing: parsing: \nparse error near open (line 1 symbol 10 - line 2 symbol 0):\n\"(\"\n"}
```

Without the line feeds however, the query works:
```
curl localhost:10101/index/repository/query
     -X POST
     -d 'Intersect(Row(stargazer=14),Row(stargazer=19))'
{"results":[{"attrs":{},"columns":[2,3,362,396,416,461,464,466,470,486]}]}
```

**Comment by travisturner** [comment]
What seems to fix this is the following change in `pql.peg`:
```
-sp <- ( ' ' / '\t' )*
+sp <- ( ' ' / '\t' / '\n')*
```
What I'm not sure about, however, is that this change makes `sp` the same as `whitesp`. Is there a reason that those are separate rules?

**Comment by jaffee** [comment]
I think that's fine - it will allow you to do weird ish things like: 
```
Row(blah
>=
3)
```
but that's probably fine. Just add a few test cases to the existing ones in pqlpeg_test.go
