### ISSUE TITLE
Shutdown gossip on pilosa.server.Close()

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1479]
### Expected behavior
Memberlist isn't releasing the file handles for TCP and UDP on server.Close(). 
This isn't really an issue except during tests where the same process is opening/closing multiple clusters. In that case, every cluster that is opened holds 2 file handles.

### Actual behavior
We should call [Memberlist.Shutdown](https://godoc.org/github.com/hashicorp/memberlist#Memberlist.Shutdown) on server.Close(). Currently, we're not storing a reference to `gossipMemberSet` in `server/server.go`, so we can't call `Shutdown()` on it. We may need to store a reference to `gossipMemberSet` in `Command`, but that would require exporting `gossip.gossipMemberSet`.

### Steps to reproduce the behavior
```
ulimit -n 100
go test -run TestExecutor_Execute_SetValue -count=1000
```

**Comment by jaffee** [comment]
notes from discussion:

store gossipMemberSet on server.Command as an io.Closer, and rename gossipMemberSet to memberSet since it's in the gossip package.

call memberset.Leave with a timeout and then call shutdown to try to leave the cluster cleanly.
