### ISSUE TITLE
imports supporting string keys for rows/cols

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1488]
### Description

Our current import endpoints don't support key/id mapping functionality. We'd like to have some support for high rate ingest of keyed data. Not sure at this point how it will work, but this ticket should be updated when there is more clarity.

### Success criteria (What criteria will consider this ticket closeable?)
Ingesting keyed data is supported at a reasonably high rate (e.g. not through PQL)

**Comment by travisturner** [comment]
This is still open due to the issue described in #1577
