### ISSUE TITLE
Consider adding field type "bool"

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1498]
### Description
It may be useful to support a field type `bool`. This field would basically maintain two rows: 0 = false, 1 = true. 

This field type would support a `Set()` query on the bool field `vip` like:
```
Set(100, vip=true)
```
Internally, Pilosa would do the equivalent of:
```
// vip=true
Clear(100, vip=0)  // clear the false bit
Set(100, vip=1)  // set the true bit

// vip=false
Set(100, vip=0)  // set the false bit
Clear(100, vip=1)  // clear the true bit

// query for vip=true
Row(vip=1)

// query for vip=false
Row(vip=0)
```
Alternatively, the `bool` field could maintain only a true row along with a not-null row. That would look like this:
```
// vip=true
Set(100, vip=0)  // set the not-null
Set(100, vip=1)  // set the true bit

// vip=false
Set(100, vip=0)  // set the not-null bit
Clear(100, vip=1)  // clear the true bit

// query for vip=true
Row(vip=1)

// query for vip=false
Difference(Row(vip=0), Row(vip=1))
```

As an additional thought, the `bool` field is really a sub-set of a mutually exclusive `enum` field, so we may consider how the implementation of an `enum` field and/or a mutually exclusive field fits in as well.

**Comment by alanbernstein** [comment]
Old but related: https://github.com/pilosa/pilosa/issues/434

**Comment by yuce** [comment]
Isn't `Set(vip=100)` equivalent to `Set(100, vip=0)` and `Clear(vip=100)` to `Set(100, vip=0)` ? Having a single row would eliminate the need for a mutex field.

**Comment by travisturner** [comment]
@yuce if you use a single row (in your example, row=0) to indicate true/false, then you don't know which columns are actually false, and which just have never had a value set. So in your example, if the use case allows for the two conditions "true" and "false or not set", then your example definitely works.
