### ISSUE TITLE
Explore GroupBy

### ISSUE THREAD

**Issue by tgruben** [pilosa/pilosa#1500]
Add the ability provided a list of fields, return group count results

`GroupBy(fields=[cab_type,year], limit=100)`
### Expected behavior
Output:
{ fields:[yellow, 2010], total:193484}
{ fields:[green, 2010], total:3723}
{ fields:[yellow, 2011], total:4892845}
{ fields:[green, 2011], total:32003}

**Comment by travisturner** [comment]
See #1496 for exploration work.
