### ISSUE TITLE
Review remoteMaxSlice logic

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#153]
In `db.go` we use `remoteMaxSlice` to hold the DB's max slice according to `this` node.
The value represents the highest slice for DB reported by any node via `server.monitorMaxSlices()` which runs every `60 seconds`.

On every query execution, we distribute the query to all slices based on the maximum slice as it is understood by `this` node. MaxSlice is determined by taking the highest value of:
- remoteMaxSlice
- maximum slice for DB on `this` node
This logic is encapsulated by `db.MaxSlice()`.

We might consider changing `remoteMaxSlice` to be `globalMaxSlice` and update it via  both `server.monitorMaxSlices()` and locally as slices are added to DB. This would allow us to simply reference `db.globalMaxSlice` instead of looking through all the frames as is currently done in `db.MaxSlice()`. We could keep `db.MaxSlice()` to do a deep lookup based on the schema, but use `db.GlobalMaxSlice()` as a cached lookup.

**Comment by jaffee** [comment]
this is very old and many things have changed - there are a number of tickets related to this that I think cover anything that was a consideration here, so I'm closing. For reference, those tickets are 

#593 #916 #1008
