### ISSUE TITLE
The `.keys` file is limited to only 10gb of string keys

### ISSUE THREAD

**Issue by mikejdorm** [pilosa/pilosa#1546]
### Description
The size of the `.keys` file is currently set by a `const` in [`translate_mapsize_all64bitsystems.go`](https://github.com/pilosa/pilosa/blob/7538562713aff7f561fc49911897e7ea233cb4e0/translate_mapsize_all64bitsystems.go#L8) which limits the size to 10gb. If you import, or write, a set of string keys greater than the 10gb limit, the following error is logged by the Pilosa server. 

```
2018/07/20 23:51:05 PANIC: runtime error: slice bounds out of range
goroutine 31046 [running]:
runtime/debug.Stack(0xc4daeff0a0, 0x1f4, 0xf9d2e0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/pilosa/pilosa/http.(*Handler).ServeHTTP.func1(0xc3f6e0, 0xc4daeff0a0, 0xc42007c4e0)
        /go/src/github.com/pilosa/pilosa/http/handler.go:241 +0x91
panic(0xae57c0, 0xf9d2e0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/pilosa/pilosa.(*index).lookupKey(0xc42018e7e0, 0x2e355253e, 0x411e69, 0x0, 0x0)
        /go/src/github.com/pilosa/pilosa/translate.go:854 +0xed
github.com/pilosa/pilosa.(*index).insertIDbyOffset(0xc42018e7e0, 0x2e355253e, 0x5d1eb64, 0xc636eee2c0)
```

It would be great to have this const exposed as a configurable property for the server, or update the translation code so that it automatically increases the size of the translation map as keys are written. 

A more descriptive error message would also be valuable within the [`/go/src/github.com/pilosa/pilosa/translate.go`](https://github.com/pilosa/pilosa/blob/master/translate.go) file. 

### Success criteria
More than 10gb of string keys can be persisted to Pilosa without any errors.

**Comment by codysoyland** [comment]
@mikejdorm: Thanks for reporting! This has been made configurable on master and will be released in Pilosa 1.2. Here is a link to the documentation: https://www.pilosa.com/docs/master/configuration/#translation-map-size
