### ISSUE TITLE
Whether reverse queries are supported ？

### ISSUE THREAD

**Issue by Giant1** [pilosa/pilosa#1549]
###  
From the example of the official website, we can inquire which books are borrowed by each person. Can we query the people who borrowed these books at the same time?

**Comment by travisturner** [comment]
@Giant1, Pilosa queries are most performant when the items of interest (in this example, books) are represented as columns. Pilosa's sharding strategy, and hence concurrency, is around groups of columns.

We are currently working on query support for rows (i.e. the list of people for a book), but it likely won't be quite as performant. In the mean time, if you want to perform the inverse query, you would need to maintain a second index where people are placed in columns, and books are the rows of a field.
