### ISSUE TITLE
SetRowAttrs error with string key row

### ISSUE THREAD

**Issue by zhyhang** [pilosa/pilosa#1554]
curl 127.0.0.1:10101/index/test1 -d '{"options": {"keys": true}}' -X POST
curl 127.0.0.1:10101/index/test1/field/daat -d '{"options": {"keys": true}}' -X POST
curl 127.0.0.1:10101/index/test1/query -d 'Set("user001",daat="tag00001")' -X POST
curl 127.0.0.1:10101/index/test1/query -d "SetRowAttrs(daat,'tag00001',active=true)" -X POST

throw error message:
{"error":"parsing: parsing: \nparse error near comma (line 1 symbol 17 - line 1 symbol 18):\n\",\"\n"}

using id column/row is OK.

**Comment by jaffee** [comment]
Thanks for the report @zhyhang!

I've reproduced the issue, and the problem is in `pql/pql.peg` line 10:
```
       / 'SetRowAttrs' {p.startCall("SetRowAttrs")} open posfield comma uintrow comma args close {p.endCall()}
```
The parser is incorrectly set to only accept an unsigned integer as the row value. We'll have a fix for this soon.
