### ISSUE TITLE
pilosa import --create doesn't use --string-keys

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1570]
For bugs, please provide the following:

### Expected behavior

`./pilosa import --create --string-keys --index i1 --field f1 CSV_FILE` should create `i1` and `f1` with `keys=true`.

### Actual behavior

Running the following:
```
curl localhost:10101/index/i1/query -d 'Row(f1="foo")'
```

Results in:
```
{"error":"executing: string 'row' value not allowed unless field 'keys' option enabled"}
```
### Steps to reproduce the behavior
```
./pilosa import --create --index i1 --field f1 --string-keys 1.csv
```
With the following CSV:
```
foo,bar
```
Then:
```
curl localhost:10101/index/i1/query -d 'Row(f1="foo")'
```

**Comment by travisturner** [comment]
Good catch. I want to add that having `string-keys` apply to both the index and the field is not ideal, since it's possible to have string keys for one and not the other. We should think about how (and whether) we handle index and field options on the pilosa CLI command.

**Comment by jaffee** [comment]
Let's do an `--index.keys` boolean and a `field.keys` boolean. As we add more options to indexes and fields, they will follow naturally as flags in this fashion
