### ISSUE TITLE
Importing values with column keys is not supported for int fields

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1593]
### Description

There is no support for importing values with column keys to int fields. We should add `Field.importK`  and `Fragment.importK` functions or make `{Field,Fragment}.import` functions to work with keys. `API.Import` needs to be modified to recognize int fields with column keys and use `Fragment.import` or `Fragment.importK`.

### Success criteria (What criteria will consider this ticket closeable?)

Importing values with column keys into int fields is supported.

**Comment by yuce** [comment]
@travisturner No, that PR makes the tests pass.

**Comment by travisturner** [comment]
I believe the work in #1599 and #1601 address this.
@yuce if that's not the case feel free to re-open this issue.
