### ISSUE TITLE
Merge string keys import support commit

### ISSUE THREAD

**Issue by zhyhang** [pilosa/pilosa#1597]
I found that neither command line nor http endpoint support string keys import on master branch.
When master merge the commit [Support keys on import CLI.](https://github.com/pilosa/pilosa/commit/214c667181f8cb4239244c4f88e9509bfd87ea4a) on develop branch?

**Comment by travisturner** [comment]
@zhyhang you can track this in #1599. It's awaiting review, but should be on master later today.

**Comment by travisturner** [comment]
@zhyhang this has been merged.
There is a follow up PR #1601 related to importing with keys into integer fields.

**Comment by travisturner** [comment]
#1601 has been merged as well.
