### ISSUE TITLE
move pilosa/internal/public.proto into separate external package

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1617]
### Description

go-pilosa imports pilosa, but also redefines Pilosa protobufs separately. This causes a bunch of warnings to be spewed out and may break more seriously in the future. If we make Pilosa's public proto definitions importable from other packages, we can fix this issue.

### Success criteria (What criteria will consider this ticket closeable?)

Public protobuf definitions can be imported from other projects.

**Comment by travisturner** [comment]
We addressed this in `go-pilosa`, but it still needs to be addressed for pilosa core.

**Comment by jaffee** [comment]
I think we decided not to do this since other languages would still need a separate copy of the .proto file it makes sense for that to be the way in which the API gets shared.
