### ISSUE TITLE
Check for license headers in CI

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#1633]
CI should ensure license headers exist on all Go files.

[This tool](https://github.com/palantir/godel) claims to be able to programmatically add license headers: `./godelw license applies a specified license header to all Go files in a project`

This can be as simple as running the tool in CI and failing the build if there is a diff.

I would probably run this directly after `gometalinter` in the linter job.

Other tools are also worthy of consideration -- this tool was found easily.

**Comment by travisturner** [comment]
@codysoyland  to determine if it's worth adding this to CI or just make it part of the release instructions.

**Comment by jaffee** [comment]
let's try using this as part of the 2019Valentine release to at least verify that things are in order.
