### ISSUE TITLE
[proposal] enable trackExistence by default

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1637]
### Description

I think that we should seriously consider enabling trackExistence by default for new indexes before we cut a new release. This won't strictly be a breaking change, but will reduce performance somewhat for imports. My concern is that new users will create an index with the default option, and then get frustrated when the `Not` query, and any other functionality which depends on existence is not available to them. I also have an inkling more functionality will depend on existence in the future, and existing users won't be able to take advantage of it unless they've specifically enabled it in the past whether they needed it at the time or not.

### Success criteria (What criteria will consider this ticket closeable?)
We've discussed enabling trackExistence by default, made a decision, and implemented it.

**Comment by alanbernstein** [comment]
I think I agree that the default behavior should be unsurprising to an unfamiliar user (that is, `Not` should work). 

Related: https://github.com/pilosa/pilosa/issues/1639
