### ISSUE TITLE
Consider moving from metalinter to staticcheck

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1640]
### Description

The next release of @dominikh's [staticcheck](https://github.com/dominikh/go-tools) tool looks very promising:
http://next.staticcheck.io/changes/2018.1

gometalinter, which we're currently, using has significant performance drawbacks, and the complexity of its installation and configuration is also non-trivial. These problems are mostly due to it being a runner of other tools, which staticcheck looks to be solving in its next release. 

If we do end up doing this, let's look into contributing financially to the project - either through sponsorship or purchasing a support package.

### Success Criteria

We should have much faster builds/checks both locally and in CI - possible that we'll also get *better* checks which are consistently updated and added to without us having to manually enable, disable, or configure individual checks.

**Comment by codysoyland** [comment]
I don't think this replaces `gometalinter`. It looks like this is just a restructuring of the same linters that were included in `megacheck` (gosimple, unused, and staticcheck), which is included in our enabled linters in `gometalinter`. Until this new `staticcheck` supports all the functionality we get through the other linters, I would recommend continuing to use gometalinter in CI.

Also note that the linter now runs in parallel with the test runners in CircleCI, so the runtime in CI is not as important as it was on TravisCI. We can also choose to pay a fee for a more beefy CI environment if performance is a productivity blocker.

**Comment by jaffee** [comment]
#1924
