### ISSUE TITLE
Implement Inverse Imports

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1657]
### Description

We currently only support importing data into Pilosa to mass `Set` bits. It should be easy to support mass `Clear`ing bits using the same import mechanisms.

### Success criteria (What criteria will consider this ticket closeable?)

* Add `inverse` parameter to `API.Import` and `API.ImportRoaring` functions. When set to `true`, `Clear` bits instead of `Set`ting them.
* Add `inverse` query argument to `/import` and `/import-roaring` HTTP endpoints.
* Update client libraries to support inverse imports.

**Comment by travisturner** [comment]
I'm not sure that `inverse` is the best name for this operation. Inverse, to me, implies setting the inverse of the bits provided (i.e. setting `1100` when given `0011`), as opposed to clearing the bits provided. Perhaps the flag `--clear` is explicit enough.

**Comment by mikejdorm** [comment]
+1 on this feature. This would help us out a lot.

**Comment by alanbernstein** [comment]
Hi @mikejdorm, we're still considering how to approach this. Would you mind describing here your use case that would benefit from this feature?

Some things we're thinking about: 

- Batching `Set`s and `Clear`s separately, versus combining both into a single request/format.
- How to update client APIs and CSV file format to support new import options.
- Support for streaming ingest, since `/import` is the best option for that kind of usage, but wasn't exactly designed for it.

**Comment by mikejdorm** [comment]
@alanbernstein We're currently processing streaming traffic and importing the Set operations through the `/import` endpoint using the Java client. We would like to follow a similar process with clearing bits. We shouldn't require any CSV support - really all we need is an endpoint we can use to process a list of Row IDs and Column Keys. Note: clearing column keys support would also be an important requirement for us. 

As far as implementation. I was thinking the existing `ImportRequest` payload would work fine and we would just send that payload to a separate `clear` endpoint (or something along those lines). We wouldn't really want to mix the `Clears` and `Sets` into a single request - however, we can if that is easier for you. My preference would be to send the clear payloads separate from the import payloads.

**Comment by mikejdorm** [comment]
I'll defer to all of you in terms of the implementation. I don't really have a strong opinion on any of the choices listed in the comment above. From a java-client perspective it should be simple to implement any of the scenarios you have listed. 

Thanks for taking a look at this. The performance from the `/import` endpoint has been working well, but the `Clear` batch pql queries we execute tend to slow down processing times. They also appear to increase the load on the Pilosa servers - I'm guessing this is from the server having to parse these larger batch queries.

**Comment by travisturner** [comment]
@mikejdorm the `--clear` flag is supported on all imports now on master. Let me know if you have any problems with it.

**Comment by mikejdorm** [comment]
Thanks! We'll check it out
