### ISSUE TITLE
Add field type protection to import-roaring

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1660]
### Description

Currently import-roaring merges the imported data to the given field regardless of field type. This could easily corrupt data in mutex fields, int fields, and other field types which have restrictions on how the data can look. We need to disallow roaring-import into these fields or add protections which will reject the import if the data is corrupt.

### Success criteria (What criteria will consider this ticket closeable?)

It's impossible to create invalid data using the roaring-import endpoint. Invalid meaning a mutex field which has more than one bit set in the same column, or an int field with the not-null bit unset, but has integer data, or has integer data outside the configured range. This is not meant to be an exhaustive description of all ways data could be invalid.

**Comment by travisturner** [comment]
To start, let's whitelist the field types which support this. For now this is just `set` fields.
