### ISSUE TITLE
Discuss omitting `id` from columnAttrs JSON output

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1682]
### Description
When requesting `columnAttrs` in the case where column keys are used, the output returns both the column key and the id with value `0`. For example:
```
  "columnAttrs": [
    {
      "id": 0,
      "key": "one",
      "attrs": {
        "name": "To Kill a Mockingbird",
        "year": 1960
      }
    },
    {
      "id": 0,
      "key": "two",
      "attrs": {
        "name": "No Name in the Street",
        "year": 1972
      }
    }
    }
  ]
```
PR #1677 adds an `omitempty` to the json tag, but I think this may omit valid `0` columns in the case where column keys are *not* used.

Decide if it makes sense to write a custom JSON marshaler for columnAttrs to include either id or key depending on `index.Keys()`.

**Comment by yuce** [comment]
How about starting the id counter from 1? Would that break anything?
