### ISSUE TITLE
System fields (or indexes) should use a different namespace than regular fields/indexes

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1691]
### Description

Pilosa creates the `exists` field when `trackExistence=true`. Since it is a system field, putting them in the same namespace with regular fields causes the following problems:
* They are returned from the /schema endpoint so they should be explicitly ignored by client libraries
* Users can access it so they may be inadvertently manipulated.
* And most importantly, we may have other reserved/system fields/indexes in the future, which may break users' access if they are using those fields.

Because of those reasons, we should use a different namespace for system fields/indexes. A quick way of accomplishing is, prefixing system fields/indexes with a character not available to the regular ones, such as `$`. So `exists` and `$exists` are two different fields.

### Success criteria (What criteria will consider this ticket closeable?)

Reserved/system fields/indexes use a different namespace than regular fields/indexes.

**Comment by travisturner** [comment]
Originally, we were going to call the field `_exists` (prefixed, as you said), but then it was suggested that a user might want to query the `_exists` field. Currently, querying a field called `_exists` returns an invalid field name error.

I'm fine with adding a prefix to reserved fields, but we need to decide if we want to allow users to directly query them. Also, I think there was an issue with anti-entropy; it needs to know about all fields, and so if `_exists` is suppressed from `Schema()`, then we need to have another way for AE to get the full schema. Basically I'm saying that the logic becomes a bit more complicated to support "invalid" field names. So let's decide exactly how we want it to work.

**Comment by yuce** [comment]
I think we shouldn't allow the users directly query system indexes/fields (at least no write queries), since they are implementation details. We may change how they work in the future, and it will break for users who rely on them. Even if we want to allow read queries, I think it would be better to have another PQL call, like `Exists`.

**Comment by travisturner** [comment]
The latest release `v1.1.0` does not contain the `trackExistence` functionality, so we need to address this change before cutting the next release.
