### ISSUE TITLE
Make Pilosa Go module

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#1721]
### Description

Go 1.11 includes support for [Go modules](https://github.com/golang/go/wiki/Modules). We should add support for Pilosa and deprecate (eventually remove) dep support.

Initial support has been implemented in #1616, but gometalinter was failing, so it has not been merged. This needs to be investigated more.

### Success criteria (What criteria will consider this ticket closeable?)

Pilosa is usable as a Go module and all tests and CI jobs pass.

**Comment by codysoyland** [comment]
Not in a hurry to finish this ticket, as some of our tooling (notably gometalinter) does not play nicely with modules. We should "snooze" on this for a couple of months and return to see how our tooling plays sometime early in 2019.

**Comment by jaffee** [comment]
This is pretty well done unless I'm totally out of my gourd.
