### ISSUE TITLE
add filter to Group By

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1726]
### Description

It should be possible to apply an arbitrary filter to Group By queries. I think the fact that it isn't there is basically an oversight on my part. If I'm thinking about this correctly, it should be possible to Intersect the filter with each value of the first field in the group by, and basically add almost no overhead.

Difficult question will be designing the API. We could make the filter a keyword arg.
`GroupBy(Rows(field=blah), Rows(field=blah2), limit=10, filter=Row(field=bar, id=2))`

Or an optional first positional arg:
`GroupBy(Row(field=bar, id=2), Rows(field=blah), Rows(field=blah2), limit=10)`

which would require a little extra care in processing to check if the first query is a bitmap type query or a rows type query, and might be a bit more bug prone. Also somewhat more confusing, although follows how TopN works...

### Success criteria (What criteria will consider this ticket closeable?)
Group By with filter (basically a `WHERE... GROUP BY ...` ) is implemented.

**Comment by travisturner** [comment]
Just to clarify, I understand this to be like a (WHERE ... GROUP BY ...), not a (GROUP BY ... HAVING ...)

**Comment by jaffee** [comment]
I think so, but TBH, I'm going to have to brush up my SQL again.
