### ISSUE TITLE
Move Range (time) functionality to Row call and support UNIX timestamps

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1757]
### Description

In a previous ticket https://github.com/pilosa/pilosa/issues/1318 it was proposed to move `Range(<FIELD>=<ROW>, <DATE_TIME>, <DATE_TIME>)` call to `Row(<FIELD>=<ROW>, start=<TIMESTAMP>, end=<TIMESTAMP>)` call but that was never realized.

Overloading the `Row` call with the time range has the following advantages:
* One less call name to remember.
* `Row` becomes more symmetrical with `Set` which can set the timestamp of the column.
* It becomes possible to leave one of `start` (to get all columns after the start) or `end` (to get all columns up to the end). If both `start` and `end` are left out, `Row` calls behaves as usual.

On top of that, it would be desirable to be able to specify UNIX timestamps in the time range. Currently used timestamp format is fine for manually running queries, but it is more common and easier to specify UNIX timestamp in code.

### Success criteria (What criteria will consider this ticket closable?)

* `Row` call supports `start` and `end` parameters to specify the time range.
* `start` and `end` parameters supports UNIX timestamps.
* `Range` (time) call is marked deprecated.

**Comment by jaffee** [comment]
how about `from` and `to` or `until`. `start` and `end` are used in the `Rows` call to refer to row ids rather than times.
