### ISSUE TITLE
ID import on keyed fields

### ISSUE THREAD

**Issue by tgruben** [pilosa/pilosa#1758]
### Description
Current keyed fields will not allow id imports.  For performance reasons and the addition of the key-id enpoint , we should allow id imports into keyed fields given the assumption that the user is responsible pre-allocating the ids.  

### Success criteria (What criteria will consider this ticket closeable?)
import endpoint should work with ids into keyed fields

**Comment by yuce** [comment]
Java client implementation: https://github.com/pilosa/java-pilosa/pull/140
