### ISSUE TITLE
NoStandardView not respected in Roaring import

### ISSUE THREAD

**Issue by dmibor** [pilosa/pilosa#1768]
For bugs, please provide the following:

### Expected behavior
Roaring import endpoint should respect NoStandardView option
### Actual behavior
It does not, still see standard view when importing roaring 

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

**Comment by yuce** [comment]
Roaring import for time fields is handled by the Go client, but it doesn't yet support `NoStandardView` option. I've created the ticket: https://github.com/pilosa/go-pilosa/issues/205

**Comment by yuce** [comment]
Closing this ticket, since it was resolved here: https://github.com/pilosa/go-pilosa/issues/205
