### ISSUE TITLE
BenchmarkFragment_Blocks intermittent failure

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#1791]
### Expected behavior

Benchmark runs

### Actual behavior

Occasionally,

```
--- FAIL: BenchmarkFragment_Blocks
    fragment_internal_test.go:1151: no blocks in fragment
```

### Steps to reproduce the behavior

```go test -timeout=30m -bench=. github.com/pilosa/pilosa```

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Ubuntu Linux (64-bit)

**Comment by jaffee** [comment]
I keep seeing this
