### ISSUE TITLE
Fragment benchmarks modify testdata

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#1792]
### Expected behavior

Benchmarks do not modify testdata

### Actual behavior

File `testdata/sample_view/0` is modified.

### Steps to reproduce the behavior

`go test -timeout=30m -bench=. github.com/pilosa/pilosa`

Notice that two benchmarks use the file. See `fragment_internal_test.go`.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Both Mac OS and Linux

**Comment by travisturner** [comment]
possibly fixed by #1827

**Comment by travisturner** [comment]
fixed by #1827
