### ISSUE TITLE
Executing an empty query doesn't return an error

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1840]
### What's going wrong?

Executing an empty query (posting a blank string) to Pilosa doesn't return an error.

### What was expected?

We should probably return an error in that case.

### Steps to reproduce the behavior

1. Create an index:
  ```
  $ curl localhost:10101/index/i1/query -d ''
  ```

2. Execute an empty query:
  ```
  $ curl -v localhost:10101/index/i1/query -d ''
  ```
  Returns:
  ```
< HTTP/1.1 200 OK
< Date: Thu, 24 Jan 2019 17:58:33 GMT
< Content-Length: 3
< Content-Type: text/plain; charset=utf-8
< 
{}

  ```

**Comment by alanbernstein** [comment]
Empty object is not a good response, an empty result set would also be an acceptable alternative.
