### ISSUE TITLE
Range query failing

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1843]
For bugs, please provide the following:

### What's going wrong?

Range query generated from go-pilosa is failing on post 1.2 Pilosa

```
curl 10.180.97.100:10101/index/myindex/query \
     -X POST \
     -d 'Count(Range(is_registered=1,2019-01-01T00:00,2019-01-15T00:00))'
```

Getting this 400 response:

```
{"error":"parsing: parsing: \nparse error near PegText (line 1 symbol 29 - line 1 symbol 33):\n\"2019\"\n"}
```

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Pilosa v1.2.0-41-g63255315

**Comment by yuce** [comment]
We should support the old `Range` call, but the preferred way of creating time range queries with Go client is using `field.RowRange`.
