### ISSUE TITLE
GroupBy should return an error for fields with noStandardView

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1845]
### What's going wrong?

`Rows` call is not supported for fields with `noStandardView`, so those fields cannot be used with `GroupBy` queries either. No error is returned if a field in a `GroupBy` query has `noStandardView`.

### What was expected?

An error is returned if one of the fields in a `GroupBy` query has `noStandardView`.

### Steps to reproduce the behavior

```
$ curl localhost:10101/index/i1 -d ''
$ localhost:10101/index/i1/field/f3 -d '{"options":{"type":"time", "timeQuantum":"YMD","noStandardView":true}}'
$ curl localhost:10101/index/i1/query -d 'Rows(f3)'
{"error":"executing: Rows() query on time field with no standard view is not currently supported"}
$ curl localhost:10101/index/i1/query -d 'GroupBy(Rows(f3))'
{"results":[[]]}
```

**Comment by travisturner** [comment]
For reference, here's the related `Rows` issue and PR: #1783, #1826

**Comment by yuce** [comment]
That's cool. Closing the ticket.
