### ISSUE TITLE
Proposal: Paging through IDs of any <ROW_CALL>

### ISSUE THREAD

**Issue by dmibor** [pilosa/pilosa#1852]
For feature requests, please provide the following:

### Description
Noticed in my tests that Pilosa uses a lot of memory when I try to request a lot of IDs from it which leads to almost certain OOMs for big queries. Think to get a handle on this - ability to page through returned IDs would be very useful.
### Success criteria (What criteria will consider this ticket closeable?)
Requesting a lot of IDs won't lead to OOM

**Comment by melgenek** [comment]
@dmibor hi! Did you managed to solve this issue?
