### ISSUE TITLE
Count(Options(Row())) - does not work 

### ISSUE THREAD

**Issue by dmibor** [pilosa/pilosa#1853]
For bugs, please provide the following:

### What's going wrong?

Getting error when trying to execute Count query on Row for specific shards
```
$ curl localhost:10101/index/test_index/query -X POST -d 'Count(Options(Row(from="2018-07-01T00:00", f1=0, to="2018-08-01T00:00"), shards=[0,7,14,21,28,35,42,49,56]))'
{"error":"executing: unknown call: Options"}
```
### What was expected?
Number of bits set for the row 0 of field f1 in provided shards.

**Comment by yuce** [comment]
`Options` can be used only as the outermost call. Could you try:
```
Options(Count(Row(from="2018-07-01T00:00", f1=0, to="2018-08-01T00:00"), shards=[0,7,14,21,28,35,42,49,56]))
```

**Comment by dmibor** [comment]
Works! that should do it, thank you @yuce , couldn't guess a bit counter-intuitive to me
