### ISSUE TITLE
translate store buffer exceeded max size: pilosa: translate read target is undersized

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1860]
### Description
This error occurs when an import into an index or field using key translation has keys which exceed the maximum size of a translation replication entry (set to 4MB at time of writing).

Currently the pilosa.translateFileReader is limited to reading an entire LogEntry at once. The LogEntry is created by a single call to (e.g.) `TranslateColumnsToUint64` which can contain an arbitrary number of keys to be translated (and I think each key can be of arbitrary size). 

There are a few possible avenues to fixing this. Breaking up LogEntries automatically is one, but it would probably be better to improve the translateFileReader.Read implementation to be more flexible (not need to read an entire entry at once), and then basically ioutil.Copy that directly to the ResponseWriter in handler.GetTranslateData.

### Success criteria (What criteria will consider this ticket closeable?)

Large import requests should not be able to cause errors with key translation replication just because there is a maximum read buffer size.

**Comment by Giant1** [comment]
I've encountered the same bug, Which made import requests blocking, is there a more detailed solution?

**Comment by Giant1** [comment]
19/02/23 11:44:13 INFO RetryExec: Retrying request to {}->http://172.30.1.5:10103
19/02/23 11:44:14 INFO RetryExec: I/O exception (java.net.SocketException) caught when processing request to {}->http://172.30.1.5:10103: Broken pipe (Write failed)

**Comment by Giant1** [comment]
19/02/23 11:44:13 INFO RetryExec: Retrying request to {}->http://172.30.1.5:10103
19/02/23 11:44:14 INFO RetryExec: I/O exception (java.net.SocketException) caught when processing request to {}->http://172.30.1.5:10103: Broken pipe (Write failed)

**Comment by Giant1** [comment]
@jaffee Below is the pilosa-client log
19/02/23 11:44:13 INFO RetryExec: Retrying request to {}->http://172.30.1.5:10103
19/02/23 11:44:14 INFO RetryExec: I/O exception (java.net.SocketException) caught when processing request to {}->http://172.30.1.5:10103: Broken pipe (Write failed)
