### ISSUE TITLE
feat: bulk create fields/mappings?

### ISSUE THREAD

**Issue by MaxOrelus** [pilosa/pilosa#1872]
### Description

`POST /index/<index-name>/field/<field-name>`

After reviewing the documentation I've only been able to find one way of creating fields via REST, which is the endpoint shown above. I wanted to know if the feature already exists or could be added, where I can bulk create all the fields I need for a specific index. For example:

```
POST /index/<index-name>/fields
{
    "field1": {
        "options": {
            "type": "set",
            "cacheType": "ranked",
            "cacheSize": 100000,
            "keys": true
        }
    },
    "field2": {
        "options": {
            "type": "set",
            "cacheType": "ranked",
            "cacheSize": 100000,
            "keys": true
        }
    },
    "field3": {
        "options": {
            "type": "set",
            "cacheType": "ranked",
            "cacheSize": 100000,
            "keys": true
        }
    }
}
```

**Comment by travisturner** [comment]
@MaxOrelus I understand how this convenience function could be useful, but implementing it introduces a bit more complexity. For example, if in your example the field creation of `field2` fails, we would need to back out the field creation of `field1` and `field3` and return an error. That's not impossible, but it may not be worth the added complexity.

Is there a use case that you can describe where adding one field at a time is unreasonable?

**Comment by MaxOrelus** [comment]
No, it's just a convenience. I'll continue to use what's in the API.
