### ISSUE TITLE
add ShardWidth to index info

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1880]
### Description

Client libraries sometimes need to know shard width for things like imports. It would be great instead of being hard-coded if the client's interrogated the Pilosa server to get this information.

Currently ShardWidth is a constant in Pilosa's code, but there's no reason this has to always be the case. One could imagine choosing different shard width's per index depending on the data and particular tradeoffs one is interested in. 

I think that ShardWidth should be part of the response to a schema request - specifically in the IndexInfo so that client's are ready to consider ShardWidth as a per-index thing even if it's still a constant in Pilosa for now.

### Success criteria (What criteria will consider this ticket closeable?)

ShardWidth can be changed server side and client's work without update or change to configuration.

**Comment by yuce** [comment]
I've pushed a fix for this, but this may be problematic when an `Index` instance is created on the client-side. `syncSchema` is optional to call when the schema is exist on the server-side, so it is possible that an `Index` wouldn't know what the slice width is before an import. A possible workaround is, the client-side import code may call the schema endpoint to get the slice width if it is not already known.
