### ISSUE TITLE
Don't fail when mmaps are exhausted

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1888]
### Description

With lots of fragments - especially when time quantums are being used, we see errors like `creating fragment: opening fragment: opening storage: mmap: cannot allocate memory` this could be due to the actual memory available being insufficient, but it can also be due to vm.max_map_count being too low which can be queried by `sysctl vm.max_map_count`. (This is in `fragment.openStorage`)

In case of mmap failing, it should be possible to fall back to reading the file into memory normally (e.g. ioutil.ReadAll), and proceeding from there as usual. Some state will need to be kept so that when the fragment is closed it doesn't try to unmap the file.

Note:
There is a lot of potential follow-on work to this - handling file handle exhaustion more gracefully, keeping only "hot" fragments mapped or in-memory, while others get read in on-demand, etc. This ticket is not for that work, though we should keep it in mind.

### Success criteria (What criteria will consider this ticket closeable?)
When max_map_count is reached and the mmap call throws an error, Pilosa should log a warning and then continue by reading the file into memory the old fashioned way. Insufficient max_map_count should not cause Pilosa to misbehave or fail to make progress.

**Comment by tgruben** [comment]
if actual memory is insufficient for a mmap why do you think there would be memory available for just "reading"

**Comment by jaffee** [comment]
in the case we've actually seen this happen, there was sufficient memory, but there is a kernel param called `vm.max_map_count` which limits the number of active memory maps you can have. This seems to be what was exhausted.

**Comment by jaffee** [comment]
fixed by #1903
