### ISSUE TITLE
Pilosa import doesn't support track existence option for index

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1898]
### Success criteria (What criteria will consider this ticket closeable?)

`pilosa import` supports `--index-track-existence` flag. Specifying this flag enables `trackExistence` option for the given index.

**Comment by jaffee** [comment]
let's deprecate `pilosa import` and use PDK to support this kind of thing. Pilosa import is confusing since it's not the canonical high performance way to do imports and really only used for getting started and such.
