### ISSUE TITLE
fragment.openStorage returns invalid argument for field.Import

### ISSUE THREAD

**Issue by kuba--** [pilosa/pilosa#1914]
Our scenario is pretty unique. Pilosa runs inside a docker container on windows with mounted directory.
When we call `err = fld.Import(rows,cols, nil)` we get an error "invalid argument" (which comes from `fragment.openStorage`).
Following code may help to reproduce the error:
```go
package main

import "github.com/pilosa/pilosa"

func main() {
        // `/mounted/pilosa` is mapped to `C:\Users\MyUser\tmp`
        idx, err := pilosa.NewIndex("/mounted/pilosa", "idx-win")
        if err != nil {
                panic(err)
        }

        fld, err := idx.CreateField("fld-win", pilosa.OptFieldTypeDefault())
        if err != nil {
                panic(err)
        }
        rows := []uint64{1, 2, 1, 2, 1, 2, 1, 2, 1}
        cols := []uint64{1, 2, 3, 4, 5, 6, 7, 8, 9}

      // Following code works fine
     /*
       for i:= 0; i < len(rows); i++ {
            fld.SetBit(rows[i], cols[i], nil)
       }
     */

       // here we get "invalid argument"
        err = fld.Import(rows,cols, nil)
        if err != nil {
                panic(err)
        }
}
```

After deep dive, looks that the second call to `fragment.openStorage` returns `invalid argument` error in following line:
```go
	// Open the data file to be mmap'd and used as an ops log.
	file, err := os.OpenFile(f.path, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
	if err != nil {
		return fmt.Errorf("open file: %s", err)
	}
```

Of course direct call `os.OpenFile` works fine (even for mounted volumes), so it has to be some combination of syscalls when index opens/closes hierarchy of files (`/index/field/view/fragment/storage,cache`)

**Comment by jaffee** [comment]
Hey Kuba... sorry to be so delayed in responding to this. I tried to reproduce this (just in docker, not with windows) and wasn't able to.

Could you add a bit more instrumentation to the code, so we can dig into that error a bit more? I'm interested in learning the path that was passed to OpenFile when that error occurs.

**Comment by kuba--** [comment]
@jaffee - I think the key point here is _windows + docker_. If you run docker on windows then the combination of different file system + syscalls (`Mmap`, `Flock`,` Munmap`, ...) can be problematic.

So, in my case I run a docker container on Win10 where I mounted `/mounted/pilosa` on`C:\Users\Windows10\tmpindex`, where I ran the code above (`Import` failed, `SetBit` succeeded).
Just in case - my docker image based on `golang:1.11-alpine`. I think it's a locking problem caused by cascade of syscalls triggered by `Import` function.

**Comment by kuba--** [comment]
Any progress with that?

**Comment by jaffee** [comment]
@kuba-- sorry this hasn't been a high priority since we don't officially support windows... I would like to get it fixed though, and I think @yuce was able to reproduce it, so he may be able to add some more color if he gets time.

One thing you could try... we've recently added the ability to limit the number of active mmaps in Pilosa—it's a new config option, but you can look at the `github.com/pilosa/pilosa/syswrap` package to see how to interact with it directly. If you call `syswrap.SetMaxMapCount(0)` that might help?

I would still like to know the file name which is being passed the the `OpenFile` call which is failing though.

**Comment by kuba--** [comment]
@jaffee - 
`f.path` in `fragment.go` - `openStorage` function is:
`/mounted/pilosa/fld-win/views/standard/fragments/0`

So, the panic which I get for above code is:
```
panic: open storage: open file: open /mounted/pilosa/fld-win/views/standard/fragments/0: invalid argument
```

Also I tested `syswrap`. With following setting, the problem is gone.
```
import "github.com/pilosa/pilosa/syswrap"
func init() {
        syswrap.SetMaxMapCount(0)
}
...
```

I'm not sure if this workaround will work for us in a long term, but so far it requires to switch to the master branch.

**Comment by kuba--** [comment]
`syswrap.SetMaxMapCount(0)` helps on windows so, I'm closing the issue.
