### ISSUE TITLE
/fingerprint endpoint

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1926]
### Description

When working with Pilosa, it's often useful to be able to figure things about about the data. 

- How many shards on each host?
- How much data per host?
- How much data per field/view?
- Total number of set bits per field/view.
- Cardinality of each field?
- Number of containers per field/view?
- Breakdown of container types per field/view?
- Statistics on containers, avg size in bytes of array and rle containers (per field/view).
- max column ID per index.
- available shards.

Probably other things.

This will help with debugging, capacity planning, reproducing certain workloads and performance problems, etc.

### Success criteria (What criteria will consider this ticket closeable?)
Having an endpoint which has at least some of this stuff. Doesn't need to be perfect, and can be under /internal (at least initially) so we aren't bound by API guarantees when evolving it.

**Comment by jaffee** [comment]
see also the `inspect` subcommand

**Comment by travisturner** [comment]
no longer considering this feature.
