### ISSUE TITLE
Pilosa nodes don't load all fragment data on startup sometimes

### ISSUE THREAD

**Issue by dmibor** [pilosa/pilosa#1948]
### What's going wrong?
Trying to shutdown Pilosa cluster gracefully with kill \<pid\>, then trying to start all nodes back up again - some of the nodes dont load any fragment data at all (in the log below opening holder takes no time, it should take about 15 mins in normal startup), some of the nodes load some but not everything (diagnosed by seeing that load of fragments takes significantly less time than usual)
And final Count() numbers returned by Pilosa are incorrect, lower than should be by 20-50% in different restarts.

For example, full log for one of that kind of restart merged from all 7 nodes of my cluster (every line in file is annotated with "[<node_id>]")- [merged.log](https://github.com/pilosa/pilosa/files/3093776/merged.log) 

There node 3 doesn't load any fragment data and total Counts() queries results are about 20% lower than they should be:
```
[3] 2019/04/18 09:36:01 open holder path: /opt/pilosa/pilosa-data/
[3] 2019/04/18 09:36:01 opening index: month
[3] 2019/04/18 09:36:01 open holder: complete
```
almost instant load when there are 300GBs of fragment data on that box.

This started to happen after tried to do same thing - stop and start Pilosa processes - but 3 out of 7 nodes failed to startup due to errors :
```
Error: running server: opening server: opening Holder: open index: name=month, err=opening fields: open field: name=field6, err=opening views: opening view: view=standard, err=opening fragments: open fragment: shard=3480, err=opening storage: flock: resource      temporarily unavailable 

Error: running server: opening server: opening Holder: open index: name=month, err=opening fields: open field: name=field3, err=opening views: opening view: view=standard, err=opening fragments: open fragment: shard=4577, err=opening storage: flock: resourc     e temporarily unavailable

Error: running server: opening server: opening Holder: open index: name=month, err=opening fields: open field: name=_exists, err=opening attrstore: opening storage: timeout
```
full merged log of that event from all 7 nodes - [7nodes_merged.log](https://github.com/pilosa/pilosa/files/3093665/7nodes_merged.log)

### What was expected?
Pilosa always loads all data properly - or reports corrupted data and fails to startup. Should not startup and silently return faulty data
### Steps to reproduce the behavior

Tried to reproduce the issue locally on single node - no success. Struggling to understand what data to provide to help diagnose this issue - maybe some ideas what more I can do? Can jaeger help with that?

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
commit https://github.com/pilosa/pilosa/commit/ffec2696c8d8773f5f653a9c612ae59013bbe8a3

**Comment by travisturner** [comment]
I submitted PR #1950 to get some more debug information (requires config option `verbose = true`).

In digging into why an index would open with no data as in your example of node [3] above, I'm wondering if it might have something to do with the logic in `shardValidator` in `view.go`: https://github.com/pilosa/pilosa/blob/master/view.go#L138

This seems to be the only place where a shard file could be silently skipped during open. I'm going to dig into the `shardValidator` logic next, but I think having the debug info in #1950 will help give us some insight.

**Comment by dmibor** [comment]
seems like removals in https://github.com/pilosa/pilosa/pull/1951 fixed the issue
