### ISSUE TITLE
typo in getting started doc

### ISSUE THREAD

**Issue by tam5** [pilosa/pilosa#1960]
For bugs, please provide the following:

### What's going wrong?
typo in docs here: https://github.com/pilosa/pilosa/blob/v1.3.0/docs/getting-started.md#create-the-schema

> Since our data contains time stamps **whcih** represent the time users starred repos, we set the field type to time. Time quantum is the resolution of the time we want to use, and we set it to YMD (year, month, day) for stargazer.

### What was expected?

> Since our data contains time stamps **which** represent the time users starred repos, we set the field type to time. Time quantum is the resolution of the time we want to use, and we set it to YMD (year, month, day) for stargazer.

**Comment by alanbernstein** [comment]
Thanks for reporting this! Fixed in https://github.com/pilosa/pilosa/pull/1961
