### ISSUE TITLE
Group by filter doesn't work with field string keys

### ISSUE THREAD

**Issue by janstenpickle** [pilosa/pilosa#1967]
### What's going wrong?
When running a group by query with a filter expression providing a string key for in the field returns the following error:

`{"error":"executing: executing group by filter for shard 0: Row() error with arg for row: could not convert x of type string to uint64 in Call.UintArg"}`

### What was expected?

A normal group count response with the results filtered based on the supplied expression, similar to:

`{"results":[[{"group":[{"field":"test","rowKey":"y"},{"field":"test2","rowKey":"y"}],"count":1}]]}`

### Steps to reproduce the behavior

1. Create an index with string keys
1. Create a couple of fields with string keys
1. Add some rows
1. Run a group by query similar to  `GroupBy(Rows(field='test'),Rows(field='test2'), filter=Row(test='x'))`

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Version 1.2.0

Solo server on Docker in MacOS

**Comment by jaffee** [comment]
looks like `executor.translateGroupByCall` doesn't take the filter argument into account. Should be a pretty easy fix.

Thanks for the bug report @janstenpickle !!!

**Comment by janstenpickle** [comment]
No problem, thanks for all the hard work!
