### ISSUE TITLE
PQL panics when int64 max is exceeded

### ISSUE THREAD

**Issue by hackskills** [pilosa/pilosa#1971]
### What's going wrong?
Values above (int64 max value) `9223372036854775807` causes PQL to panic. e.g. 
`TopN(language, n=9223372036854775807)`
`Row(stargazer=9223372036854775808)`

### What was expected?
Error message, instead of a panic.

### Steps to reproduce the behavior
See above.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
N/A

**Comment by jaffee** [comment]
good issue. What is the stacktrace? Does Pilosa panic and crash completely, or just the HTTP handler (e.g. it prints the stacktrace, but keeps running?).

**Comment by hackskills** [comment]
It produces the following:
`PANIC: interface conversion: interface {} is *strconv.NumError, not string
goroutine 891 [running]:
runtime/debug.Stack(0xc0014b6000, 0x1f4, 0xc0014a88a0)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/pilosa/pilosa/http.(*Handler).ServeHTTP.func1(0x4b1fb40, 0xc0014b6000, 0xc00028e0f0)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/src/github.com/pilosa/pilosa/http/handler.go:286 +0x91
panic(0x48f9000, 0xc0014a88a0)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522 +0x1b5
github.com/pilosa/pilosa/pql.(*parser).Parse(0xc00035a800, 0xc00035a800, 0x0, 0x0)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/src/github.com/pilosa/pilosa/pql/parser.go:74 +0x3dd
github.com/pilosa/pilosa.(*API).Query(0xc0000a87b0, 0x4b22cc0, 0xc0014a8240, 0xc00149c300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/src/github.com/pilosa/pilosa/api.go:111 +0x1ce
github.com/pilosa/pilosa/http.(*Handler).handlePostQuery(0xc00028e0f0, 0x4b1fb40, 0xc0014b6000, 0xc0000e3200)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/src/github.com/pilosa/pilosa/http/handler.go:472 +0x343
net/http.HandlerFunc.ServeHTTP(0xc0000a6ea0, 0x4b1fb40, 0xc0014b6000, 0xc0000e3200)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1995 +0x44
github.com/pilosa/pilosa/http.(*Handler).extractTracing.func1(0x4b1fb40, 0xc0014b6000, 0xc0000e2d00)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/src/github.com/pilosa/pilosa/http/handler.go:231 +0x154
net/http.HandlerFunc.ServeHTTP(0xc000dc0580, 0x4b1fb40, 0xc0014b6000, 0xc0000e2d00)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1995 +0x44
github.com/pilosa/pilosa/http.(*Handler).queryArgValidator.func1(0x4b1fb40, 0xc0014b6000, 0xc0000e2d00)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/src/github.com/pilosa/pilosa/http/handler.go:222 +0xca
net/http.HandlerFunc.ServeHTTP(0xc000dc05a0, 0x4b1fb40, 0xc0014b6000, 0xc0000e2d00)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00029c180, 0x4b1fb40, 0xc0014b6000, 0xc0000e2300)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc0002f6d80, 0x4b1fb40, 0xc0014b6000, 0xc0000e2300)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/pkg/mod/github.com/gorilla/handlers@v1.3.0/cors.go:51 +0x102b
github.com/pilosa/pilosa/http.(*Handler).ServeHTTP(0xc00028e0f0, 0x4b1fb40, 0xc0014b6000, 0xc0000e2300)
	/private/tmp/pilosa-20190416-47377-1rwdvcs/pilosa-1.3.0/src/github.com/pilosa/pilosa/http/handler.go:294 +0xe1
net/http.serverHandler.ServeHTTP(0xc0000b2820, 0x4b1fb40, 0xc0014b6000, 0xc0000e2300)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00038e460, 0x4b22c00, 0xc00149c040)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:2884 +0x2f4`
