### ISSUE TITLE
get DISTINCT values for an int (BSI) field

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#2018]
### Description
A question was posed by @brucenan here: https://github.com/travisturner/bit-slice-index/issues/1 about getting the set of distinct values for a BSI field.

We can currently get the value for a single column, but I don't believe we have anything that scans the BSI fragment data and collects multiple values.

I wonder if a solution might have multiple row scanners (one for each BSI row), which synchronously scan across the columns to determine each column's value. That value can then be added to a set, which would be the fragment's return value for the distinct query. The aggregator would have to merge the sets from all fragments. Each fragment would have to scan up to 2^20 columns (at standard shardWidth).

### Success criteria (What criteria will consider this ticket closeable?)
Once can get the set of distinct values from an int field.

**Comment by jaffee** [comment]
this is probably a subtask of #1752

**Comment by travisturner** [comment]
in addition to some solution that perhaps scans the roaring fragment file to compile a list of distinct values, it may also be worth considering/benchmarking a data structure which keeps a columnID-to-value mapping as part of the field data. in that case, getting distinct would be a matter of performing the normal BSI query, and then passing the results of that query to a lookup step which gets the values from the columnID-to-value map.

**Comment by brucenan** [comment]
From pilosa side, it means map all values from one Fragment to one Slice. The Slice's each available column equals to original Fragment's each value. 

Loop is a easy way, but it's not efficient. Maybe divide it into several sub-part and use recursion or multi-thread is a better way.

**Comment by brucenan** [comment]
This is my sample codes by Java:
```
for(int i = start;i<end;i++) {
  int s = 0;
  for (int j = 0,len = mrbs.length; j < len; j++) {
  if (mrbs[j].contains(i))
     s = s | (1 << j);
  }
  s1.setBit(s);
}
```
But performance is too low. For 10,000,000 times loop, it spends nearly 7000ms, most of times spends on RoaringBitmap's contains() function. It is unacceptable. Is there any better solution to improve the performance?

**Comment by travisturner** [comment]
@brucenan we don't currently have plans to merge this PR. The code in #2052 is a first pass at an implementation in case you want to reference that.
