### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by bitrise-tom** [pilosa/pilosa#2027]
### Description
I see from #1113 that Pilosa is now supported as running in Kubernetes, and I hate to have to ask this, but I can find no Helm resources for it. Rather than reopening #1113 I thought it better to make a new ticket.

### Success criteria (What criteria will consider this ticket closeable?)
Link to, or documentation for Helm and/or kubernetes manifest files.

**Comment by yuce** [comment]
Hi @bitrise-tom! Sorry for the late response. Our helm repo is now public at: https://github.com/pilosa/helm Note that it wasn't thoroughly tested and not currently ready for production. We are looking for feedback, let us know if there are any issues.
