### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by dshikhaleev** [pilosa/pilosa#2066]
### What's going wrong?
Client receives the following error. Pilosa cluster falls apart.
com.pilosa.client.exceptions.PilosaException: Server error (500): {"success":false,"error":{"message":"sending CreateField message: executing request: getting response: Post http://10.4.7.2:10101/internal/cluster/message: EOF"}}

### What was expected?
The same test works on single instance Pilosa server. Expected it to work with clustered setup.

### Steps to reproduce the behavior
Create 10 000 integer fields with range 0-100 in an index.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Google Kubernetes cluster with container optimized OS. Tried with 1-32 cores, 1-30 GB RAM. Solo works. Cluster with 3 nodes fails.

Pilosa 1.4.0, Java client 1.3.5.

Attaching log extract with concurrent map read and map write [pilosa__logs__2019-09-20T01-44.txt]

**Comment by dshikhaleev** [comment]
[pilosa__logs__2019-09-20T01-44.txt](https://github.com/pilosa/pilosa/files/3637850/pilosa__logs__2019-09-20T01-44.txt)

the logs

**Comment by jaffee** [comment]
Thank you for reporting this, I see the problem.

We have an unlocked access to Index.createField at line 604 of server.go, should be a straightforward fix.

As a side note, would love to hear more about what you're doing with Pilosa. Currently I don't expect Pilosa to behave very well with 10s of thousands of fields, though this is a use case which has popped up more than once and we have some possible solutions. Would be great to get your input if you don't mind getting in touch, either on gopher slack, or via email jaffee at pilosa.com

**Comment by dshikhaleev** [comment]
Thank you for the fix. It doesn't fail now.
