### ISSUE TITLE
Incorrect intersect query results with multithreaded java client

### ISSUE THREAD

**Issue by dshikhaleev** [pilosa/pilosa#2071]
### What's going wrong?
About 10% of intersect queries return wrong result when executed via multithreaded java client.
After a query failed, repeating it via REST returns correct result.
Issue is not reproduced if client is single-threaded. 
### What was expected?
All results are correct.
### Steps to reproduce the behavior
Create 10k integer fields with range 0-100, 10k columns with random 100 fields set to random value. 
Run intersect of 100 row queries with equal-to condition in multiple threads (6 is enough) via java client.
### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Reproduced in Docker with 8 cores, 16GB RAM PC. 
Reproduced with Pilosa v1.3.1 and Pilosa v1.4.0 + patch for #2066

**Comment by yuce** [comment]
Hi @dshikhaleev. Can you post/paste your test code so we can check? If you are running the test on a Pilosa cluster, can you also include your Pilosa config?

Btw, the Java client has its repo at: https://github.com/pilosa/java-pilosa

**Comment by dshikhaleev** [comment]
Issue is reproducible with stand-alone Pilosa.

**Comment by jaffee** [comment]
@dshikhaleev can you post steps to reproduce the issue? (if it can be done without the Java client, it would be ideal to see those steps). 

Or if you can share some Pilosa index data which demonstrates the issue, and the queries you ran to go with it.

**Comment by dshikhaleev** [comment]
I found mistake in test data generation. I'm sorry for the confusion.

**Comment by jaffee** [comment]
no problem, thanks for following up!
