### ISSUE TITLE
Should I worry about the memory usage?

### ISSUE THREAD

**Issue by young118** [pilosa/pilosa#2093]
As data grows, there will be more rows and columns, will pilosa run out of memory. As I see, there is only api for setting data, not deleting data, except remove the whole index.

**Comment by travisturner** [comment]
@young118 you will definitely need to consider memory usage as data grows.
Currently there are a couple of options, but both require down time.
1. You can add nodes to the cluster to increase the amount of memory available
2. You can stop pilosa, remove data files, restart pilosa. This option gives you greater granularity than deleting an entire index; you can delete fields, or event specific shards within a field.

I'll see if we currently have an issue open pertaining to more granular data deletion. If not, we can track that request here.

**Comment by young118** [comment]
@travisturner So in option 2, in my case, I hava some time fileds and some int fields.I see a standard file and a lot of standard_YMDH files in each time field, and a bsi_xxx file in each int filed.How can I remove the shard 0 data? Is the 0 file in each fragments the shard 0 data?Do I have to delete all the 0 files in each directory or I just have to delete some "base" 0 file and the others will be delete automatically?

**Comment by travisturner** [comment]
@young118 yes, the 0 file in each fragments directory is the data file for shard 0 for that field. so if you wanted to delete shard 0 for all fields, you would have to delete all of the 0 files.

**Comment by young118** [comment]
@travisturner thanks very much.
