### ISSUE TITLE
Roaring MarshalBinary

### ISSUE THREAD

**Issue by jtorvald** [pilosa/pilosa#2094]
I'd like to use the implementation of Roaring Bitmaps from Pilosa in my project but I would need to marshal the Bitmap to []byte. I see that there is an UnmarshalBinary but I can't find the MarshalBinary. Is there such a function for Bitmap? Is there a specific reason that it is not implemented?

**Comment by tgruben** [comment]
I believe you are looking for
https://github.com/pilosa/pilosa/blob/master/roaring/roaring.go#L1046

**Comment by jtorvald** [comment]
@tgruben Thanks! I guess so, but I get really weird results. Maybe because I don't understand it correctly or there are some bugs in the library  (or I'm too tired). I made a playground example:

https://play.golang.org/p/7JfR8Zq70TU

A) When I use WriteTo with small numbers, I don't even get bytes even though it says it has written bytes.  Bug?
B) When I use large ints it kind of works but then I get weird panics when comparing bitmaps
C) When I finally get bytes from WriteTo it seems to add a lot of overhead compared to writing full 8byte ints to a byte array.
D) With line 19 commented out it shows me that all bitmaps are equal even though they aren't. When I add more higher numbers it's shows that they are not equal. Seems also to be a bug?

**Comment by jaffee** [comment]
You're using a buffered writer and I don't think you're flushing it. Try getting rid of bufio and just using bytes.Buffer directly.

**Comment by tgruben** [comment]
https://play.golang.org/p/bZbMAS7OmhK

**Comment by jtorvald** [comment]
Rookie mistake 🙈 I had the feeling I was missing something. Not getting enough sleep lately. Thanks @jaffee  and @tgruben 
Besides that, isn't it weird that it shows that all three bitmaps are equal to testBItmap with BitwiseEqual while the bitmaps are different?
