### ISSUE TITLE
What's the difference between `Field` and `Frame`

### ISSUE THREAD

**Issue by sundy-li** [pilosa/pilosa#2102]
I have read some blogs about pilosa, but some articles are using some queries not refer to [PQL](https://www.pilosa.com/docs/latest/query-language).

Eg, in this [article](https://www.pilosa.com/use-cases/retail-analytics/), there are queries like 

```
Bitmap(frame=lo_year, rowID=1993)
```

Is it equal to `Row(lo_year=1993)` ? In pilosa old version `Field`  is named to `Frame` ?

**Comment by sundy-li** [comment]
I found the ChangeLog.

**Comment by jaffee** [comment]
yep, you got it 👍
