### ISSUE TITLE
Pilosa 2.0 errors after some time of normal operation

### ISSUE THREAD

**Issue by baaa** [pilosa/pilosa#2108]
Starting fresh with a clean storage and cluster after about a day give or take a few hours we start seeing errors that stops importing data completely with the message:
```Caused by: java.util.concurrent.ExecutionException: com.pilosa.client.exceptions.PilosaException: Server error (500): translating rows: key required```

The system running this at the moment has continuous imports and since the product is in close beta there are fewer reads than writes.

While this is happening there is nothing to indicate that there is something wrong going on with the server. (in the server logs)

When this error starts happening it starts happening on all indices/schemas at once for all import fields.

Can you please give us some pointers for investigating/resolving this issue further or ways to debug it?

**Comment by travisturner** [comment]
Hi @baaa 
That error is coming from the embedded boltdb k/v store, and it's triggered when inserting a zero-length key:
```
// ErrKeyRequired is returned when inserting a zero-length key.
	ErrKeyRequired = errors.New("key required")
```
It's possible that `java-pilosa` is sending a corrupted import request, but you might also look at the data that is being imported when the error starts to occur. Look for any empty or invalid  row keys.

**Comment by baaa** [comment]
@travisturner thanks for the quick response, it was in fact contaminated data with empty keys somehow someway.
