### ISSUE TITLE
How to deal with float number in BSI Range-Encoding?

### ISSUE THREAD

**Issue by yingfeng** [pilosa/pilosa#2109]
BSI Range-Encoding could only deal with integers. However, if the attributes are float numbers, how to deal with that? Converting float to integer?

**Comment by travisturner** [comment]
Hi @yingfeng 
Pilosa doesn't have native support for floats. As you suggested, one option is to convert your float to an integer with an associated scale, ensuring that all values within a Pilosa `int` field are derived using the same scale.

So for example, if you have the following float values:
```
123.4567
0.2
0.33333333
876567
```
You might decide to use a scale of `4`, and then insert the following values into the Pilosa `int` field:
```
1234567
2000
3333
8765670000
```
Now obviously you won't be able to represent the full range of values that you can with a float, but this is one way to achieve something like `decimal` support.

**Comment by yingfeng** [comment]
Thank you~
