### ISSUE TITLE
Python client supports protobuf

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#282]
Modify the python client to post queries as `Content-Type: application/x-protobuf`.
Currently the python client sends PQL query strings, but if we can version the client and share the pilosa `internal.proto` definition then we can bypass the parser/lexer in pilosa.

**Comment by yuce** [comment]
Can we close this ?

**Comment by codysoyland** [comment]
For the record, protobuf support was added to python client in https://github.com/pilosa/python-pilosa/commit/1808909e0f228e2c5bd7e2107fc3c3a92bd6279b
