### ISSUE TITLE
Make Python Client Cluster Aware for mutation queries (clear/set)

### ISSUE THREAD

**Issue by tgruben** [pilosa/pilosa#283]
The python client should ask the cluster for information about the consistent hash used to figure out which node a set or clear bit should be sent to.

Issues with load balancers, or being ssh tunneled into a single cluster node - the client either needs to be smart enough to detect this condition and fall back to single node querying, or this should be an option which defaults to off.

This is blocked by creating an endpoint in pilosa which gives consistent hash information. 
#294

**Comment by jaffee** [comment]
@yuce - we should probably move this ticket to the python client repo and create similar tickets for the other clients - does that make sense? Or do you want to track things like this in a single ticket and not make it specific to any one client?

**Comment by yuce** [comment]
@jaffee Your suggestion of having separate tickets makes sense, it has the advantage of tracking the progress on features for each client. The only problem is, should the ticket/issue reporter create tickets for each client library, or should s/he create a single ticket and the maintainers of client libraries copy them to corresponding repos?

**Comment by jaffee** [comment]
I think your second option makes sense @yuce

**Comment by yuce** [comment]
Moved this ticket to: https://github.com/pilosa/python-pilosa/issues/39
