### ISSUE TITLE
PQL Improvement: Case insensitive or lower case query commands and fields

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#308]
It would be great to have insensitive query commands in order to make it easier and less error-prone to write PQL. If that's technically challenging, can we at least consider making everything lower case?

Before:
```
SetBit(id=1, frame="foo", profileID=5)
```
After
```
setbit(id=1, frame="foo", profileid=5)
```

**Comment by jaffee** [comment]
Closing this unless there are strong objections to the contrary. Reasoning is that any changes to pql at this point need a pretty strong reason to do so, and pql shouldn't be the main interface to pilosa anyway (client libraries and tools should be)
