### ISSUE TITLE
New query type: Sum (generally, aggregation over attributes)

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#317]
For feature requests, please provide the following:

### Description
One of the taxi data benchmarks is something like `SELECT passenger_count, avg(total_amount) from rides GROUP BY passenger_count`. This would be trivial with the ability to compute sum or average over a particular attribute. Other aggregation functions could be supported as well.

### Success criteria (What criteria will consider this ticket closeable?)
Given a database with profile attributes set as:
`SetProfileAttrs(id=10, totalAmount=1225)`,

A sum query might look like this:
`Sum(Bitmap(id=1, frame="passengerCount"), attr="totalAmount")`
or 
`Aggregate(function="sum", Bitmap(id=1, frame="passengerCount"), attr="totalAmount")`

and return the sum of the `totalAmount` attribute across all profiles belonging to bitmap 1.

**Comment by travisturner** [comment]
I'm going to close this ticket because the upcoming range-encoded proposal will handle aggregates; we don't need to use attributes for that.

If there's some specific reason to use attributes, re-open this ticket and explain.

**Comment by alanbernstein** [comment]
In this ticket I meant "aggregation" to include other options (e.g. `function="sum"` could use `max`, `min`, `median`, ...). I think BSI supports more operations than the currently scoped work, but it's probably not as general as what I had in mind. The BSI operations should cover the majority of use-cases, so this should stay closed.

**Comment by travisturner** [comment]
This makes sense. I can see how we could use BSI to determine `min` and `max`, and `mean` is already covered in the new work. I'll have to think about `median`.
