### ISSUE TITLE
Proposal: Cluster resizing

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#332]
# Proposal: Add Node

Author: Michael Baird

Last updated: 2017/02/21

## Abstract 
  Once a Pilosa cluster is in production we will need to ability to add a node while the cluster is live.

## Background
  Growing a cluster is a key feature of any distributed database.  This proposal will describe the steps necessary to accomplish this goal.

## Proposal
  Pilosa's replication strategy distributes data by slice across a cluster using a consistent hash.
  Replica data is verified and maintained through the periodic Fragment Sync process.
  We have two options for facilitating the addition of a node
  1. Consult the Jump Hash map to determine the Slice distribution after adding a node.  Then manually collect and copy the data files to the new node before Joining.
  2. Rely solely on the Fragment Sync process to transfer all data files during the Join process.  This may take too long, and so #1 may be our best option. 
  We can use this Fragment Sync process transfer Slice data to its new node as the consistent hash map changes with the addition of new nodes.
  To accomplish this live we will need several components:
    - Node state management: Normal -> Joining (detailed in separate proposal)
    - Create an API endpoint to Join a new node to a cluster
      - This action will distribute the new cluster config across the cluster. 
      - Set the existing Cluster into the Moving state 
      - Modify the Cluster hash method to return a combined node map of the previous cluster config and new after node joins
    - Create a new API endpoint to force a Fragment Sync across the whole cluster
    - Once this process has completed set each node back to Normal state
    - Cleanup: remove orphaned slice data from nodes it no longer maps to
    - Once all fragments are synced and nodes are in normal state we need to modify the node hash to only include the node map for the current cluster configuration.   (This may require a new intermediate state)

## Compatibility
  This feature requires node state to manage behavior transitions as a new node joins a cluster and data is redistribute.  
  The maintenance Fragment Sync process on the Umbel cluster takes around 5-15 minutes.  We should test how long this would take to re-distribute a node's worth of data.
  If the timeframe is reasonable (we need to determine a reasonable time for this to take) then option #2 is viable.

## Implementation
  Need a new API endpoint /join to join a new node to a cluster.  
  Joining will modify the cluster configuration 
   Use Gossip to distribute cluster configuration data to all nodes in the cluster
  Create a new API endpoint to trigger a cluster wide Fragment Sync.  This operation is currently on a timer, and we need to trigger this asap after a join.

  If we prefer to populate the new node with data files before Joining the we will need:
   - use max slice and width to determine the number of slices
   - use FragmentNodes to get the locations of data by slice
   - Possibly create a new method like Fragment node but with a Cluster Config as input to determine the new Slice locations
   - Expose this slice configurations by cluster config via an API
   - Using this Slice cluster config create a tool to move data files from node to node.

**Comment by travisturner** [comment]
@raskle I expanded on option (1) of your proposal here: #737 
Can we close this issue and continue discussion in the new one?
