### ISSUE TITLE
Consistent Hash Partition size

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#341]
Configure consistent hash Partition size

### Description
The current Consistent hash DefaultPartitionN = 16.   To prepare for future growth this number needs to be >= the max cluster size for the life of a DB.  

1. Make this a parameter within the config
2. Default this to a higher value to prepare for cluster growth i.e. 360

### Success criteria (What criteria will consider this ticket closable?)
 We can create a cluster with more that 16 nodes, and no more that the set partition size.

### Conflicts
 Changing the default partition size will invalidate any current  DB's slice->node mapping.  We should note this breaking change in the version upgrade notes

**Comment by jaffee** [comment]
I'm trying to do this, but it breaks a bunch of tests when you make the change. Some tests are creating slices on nodes which don't own the slice after the change, but that doesn't seem to be the only source of issues, so I'm having to dig further.

**Comment by travisturner** [comment]
I ran into the same thing when I change `database` to `index` along with changing the index name in the tests from `d` to `i`. It was a bit tedious to adjust all the tests so that they worked again.

I'm not sure about the other issue you're having.

**Comment by jaffee** [comment]
@travisturner I'm not sure the test is entirely correct in its current state (although it is passing). 

Do these lines look right to you? given the slices that are being set up above?

https://github.com/pilosa/pilosa/blob/master/client_test.go#L102
