### ISSUE TITLE
TopN cutoff on same count

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#354]
Handle TopN cutoff with similar counts per bitmap

### Description
How should we handle the TopN result set in the case we more than one bitmap have the same count.  Thus resulting is arbitrary cutoff of the result set

### Success criteria
In the example Top 5 result set.  If we requested Top 3 it should either return this same set or truncate the list based on some known criteria.
bitmapID, count
436916,	209
371703,	204
361650,	203
361645,	203
361611,	203

**Comment by jaffee** [comment]
bump @raskle
