### ISSUE TITLE
`pilosa config` should print encoded object

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#366]
### Description
The `pilosa config` command currently just prints a static string. It would be more robust (I think) to create a pilosa.Config object with the default values and then toml encode it, to ensure that it stays up to date.

### Success criteria (What criteria will consider this ticket closeable?)
`pilosa config` prints a toml encoded Config object rather than containing a static string representing the config.

**Comment by travisturner** [comment]
@jaffee do we still need this issue?

**Comment by alanbernstein** [comment]
I think so, if we don't fix this, the hardcoded string will definitely get out of sync with the actual config structure eventually.

**Comment by jaffee** [comment]
yep, I just never got around to it - someone else is certainly welcome to pick it up - I will un-assign for the time being
