### ISSUE TITLE
Database file versioning

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#391]
### Description

Database files should store a version number. This can be used to track changes in the database file format.

In the future, we may use the version stored in this file to alert the user of backwards-incompatible changes or provide ability to migrate data.

### Success criteria (What criteria will consider this ticket closeable?)

- [ ] When creating a database, a file is created inside the database directory called `metadata.toml` containing a field called "version" which is the value of main.Version.

**Comment by travisturner** [comment]
For now, let's write current version to a log file within the data directory on startup.
```
2018-05-17T05:18:34 v0.8.1-g45aeb9
2018-05-17T05:19:54 v0.8.1-g45aeb9
2018-05-17T06:07:21 v0.8.2-g8aafae
```
