### ISSUE TITLE
implement frame cache type "None"

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#399]
### Description

setting a cache of size of zero for Ranked and LRU caches should set the cache type to None.
TopN should respond appropriately when cache type is None (empty list)

### Success criteria (What criteria will consider this ticket closeable?)
None is a valid value for cache type.
The Create Frame endpoint will support all unsigned integer values.
Add TopN test with zero cache that will return an empty set.

**Comment by travisturner** [comment]
I believe the consensus here is that we should add `CacheTypeNone = "none"`.
This would effectively use a no-op implementation of the `Cache` interface (called `NopCache` if we want to stay consistent with other no-op implementations).
No need to worry about `cacheSize`; we should allow the user to set that to whatever they want regardless of `cacheType`.
