### ISSUE TITLE
Node Status

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#433]
### Description
Building on the Node State work in #321 we need a /status endpoint to report current status of all nodes in the cluster.  Status should include the following information
 - Version
 - Replica Number
 - Number of nodes
 - List of Databases
   - name
   - column Label
   - max slice per DB
   - Highest Column ID
   - Time Quantum
   - Frames per Database
     - name
     - Frame type
     - Row Label
     - Row ID range per frame (TDB)
     - cache size per frame
     - List Views per frame
       - View type
- List of nodes with the following info per node:
  - ID of node
  - IP of node
  - Node State
  - Health value (TBD)
  - Slices owned by node from DB
  - Replica Slices owned by node by DB

**Comment by travisturner** [comment]
@raskle I'm closing this because it was sitting in `Review/QA`
Please re-open it (or open a new ticket) if there is still work that needs to be done on this.
