### ISSUE TITLE
Single Value Fields

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#434]
### Description
A single value field (a mutex field from here on) is like a "set" field, but each column can only have one bit set within the field, and this is enforced automatically by Pilosa. If a client sets a bit for column 1 in a mutex field, all other bits in column 1 in that field are automatically cleared. 

The use case for this is basically anything that would be a "normal" string/byte column in SQL. A "set" field that allows multiple values per column is really acting more like a JOIN to another table (a person's interests for example).

The implementation will need to have some way of tracking in a performant way which bit is set in a particular field for a particular column, and clearing that bit if a new bit is set. Perhaps we store it as an attribute?

### Success criteria (What criteria will consider this ticket closeable?)

There is a field type which enforces mutual exclusion on a per-column basis.

**Comment by travisturner** [comment]
I don't think the mutual exclusivity should necessarily be at the frame level. 
#616 describes a frame schema for range-encoded values, but I could see something similar being done for this more general case by defining groups of rows that should be considered mutually exclusive. With all that said, perhaps keeping mutual exclusivity to the frame level would be the simplest approach to start. I'd like to see more discussion around frame schema and groups before committing to one solution.

**Comment by jaffee** [comment]
Iceboxing this as the BSI Epic #615 will contain some functionality similar to this, and we'll let that inform what we need to do here once it's done.
