### ISSUE TITLE
rename datadog to statsd

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#441]
### Proposal 
I propose that we rename the datadog package within Pilosa to statsd.
This code implements the pilosa StatsClient interface and wraps around the datadog client library.
The datadog client library essentially emits events in the StatsD protocol so any service that ingests StatsD could consume these messages.

If we keep this package generic "statsd", then we can add the client address to our configuration settings.
i.e.
statsdhost = "127.0.0.1:8125"

**Comment by jaffee** [comment]
closing since this is wrapped up in the rest of the statsd work
