### ISSUE TITLE
Intermittent TestClient_Import failure

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#451]
This has been observed on multiple branches, but is not easily reproducible.

Running `make test` on messenger-rebase, I got 
```
--- FAIL: TestClient_Import (0.00s)
    client_test.go:186: unexpected bits: []
NOPMessageBroker: Send
NOPMessageBroker: Send
FAIL
FAIL    github.com/pilosa/pilosa    3.114s
```

@travisturner also saw it on an unrelated branch.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Both of us running on OSX.

**Comment by benbjohnson** [comment]
I've seen this error in the past but I tried reproducing it on OS X & Ubuntu without luck. I had the test suite running continuously for hours but no luck. I tried digging in the code but I couldn't find anything either.

It doesn't look like it's occurred on Travis CI for a while either so I'm going to close this assuming that something has fixed this. We can reopen if it occurs again and there's more information to go off of.
