### ISSUE TITLE
column support for range queries

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#494]
### Description

For Bitmap queries, one can either specify the row label, or the column label, and this will determine whether one gets back a bitmap representing a row or column in the index. Range queries are analogous to Bitmap queries, except that one specifies the start and end timestamps for the time range which the returned bits must fall into.

Right now, however, Range queries seem to neither support, nor throw an error, if the column label is given instead of a row label. (The return is always empty).

### Success criteria (What criteria will consider this ticket closeable?)
Come to a decision on whether Range queries should support columns, and make sure that issuing a Range query with the column label either throws an error, or returns correct results based on the outcome of that decision.

**Comment by codysoyland** [comment]
Fixed by #514
