### ISSUE TITLE
WebUI Console syntax hints

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#501]
For feature requests, please provide the following:

### Description
Users are shown an empty text input box, without any information about what it can do. Valid queries include PQL (documented elsewhere) and control commands (undocumented). This would be more user-friendly with some kind of syntax help section. Could be minimal, hidden behind a "?" link, in a modal, side panel, or whatever.

### Success criteria (What criteria will consider this ticket closeable?)
Some sort of information is available on the page to inform the user about the capabilities of the console.

**Comment by joeblew99** [comment]
This sounds useful.

I wonder is we can codegen or reflect of the server to build the query options for the GUI ?

I did allot of gopherjs for GUI tooling on top of golang servers. It's just an idea because it allows a ton of reuse and can be appropriate for internal tooling

**Comment by alanbernstein** [comment]
Something like that would be ideal, but for now I'm just adding a simple static tooltip so newcomers have something helpful to look at.

**Comment by joeblew99** [comment]
baby steps are best. glad we agree on the roadmap as it were.
Will try to help out as this is really great stuff.
The bleve examples are a good basis to get a feel for it. they did it all with JS, but these days gopherjs is pretty solid and quick

**Comment by codysoyland** [comment]
Thanks for your comments, @joeblew99. I think #537 is good enough for this ticket for now, but I agree we should eventually have better integration with the query language and the WebUI to provide such things as syntax highlighting, autocompletion, and perhaps a GUI query builder. For now I think we are wanting to keep things simple as we build out the rest of the WebUI.

I encourage you to check out our [proposal process](https://github.com/pilosa/general/blob/master/proposal.md) if you are interested in contributing to the WebUI. I'm interested in what GopherJS could bring to the table, but I've never tried to use it.

**Comment by joeblew99** [comment]
@codysoyland 
i agree that its best to take baby steps on this. #537 looks like a good start.

gopherjs is very easy to get going with and is great when combined with go generate.
i have been using this, but its broken at the moment as its going through a big refactoring
https://github.com/gu-io/gu

**Comment by joeblew99** [comment]
might be best to use a lib that wraps smtp, etc
I had a look here and these seems pretty good and worth a try.
https://github.com/avelino/awesome-go#email

**Comment by codysoyland** [comment]
Interesting. Will evaluate `gu` at some point. Thanks for the info! Closing this as #537 is merged.
