### ISSUE TITLE
Make "ranked" the default for frames.

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#513]
### Description
Instead of having LRU be the default for frames, let's make it ranked.

There is some performance hit to using ranked frames, but the vast majority of frames in the use cases we have explored need to be ranked rather than LRU, and we have encountered issues and unexpected results multiple times due to forgetting to set the frame as ranked, or setting it incorrectly. 

It seems likely that someone using pilosa for the first time might not remember or know to set a frame as ranked, and if they tried to use TopN functionality later on, they would either have to change it (do we support that?), or worse, they would be getting incorrect results and not realize it.

### Success criteria (What criteria will consider this ticket closeable?)
When creating a frame and not passing a CacheType option, the frame is created with CacheType `ranked`.

**Comment by travisturner** [comment]
@jaffee should we also raise an error (or warning) if a user runs `TopN` on an LRU cache?

**Comment by jaffee** [comment]
If we make ranked the default, I don't think that's necessary - Although it should be noted that TopN on an LRU frame won't return the most recently used bitmaps in any particular order - it just returns N from the cache. (I think - @tgruben please verify), so erroring may be appropriate.

**Comment by yuce** [comment]
@jaffee We can also add cache options to the Index (the default may be ranked), so the frames would default to the cache options of the corresponding index. That allows users to decide whether they want the ranked or lru as the default for frames.

**Comment by jaffee** [comment]
I don't see much point in having multiple places where things can be set - I just think it adds to potential confusion. I know we already do this with time quantum (i think), but I still don't like it.
