### ISSUE TITLE
Remove columnattrs=true query arg and move into PQL

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#523]
Original ticket below - title was changed, read comments for details.
### Description
Currently it is possible to set column attributes on non-inverted frames, but there is no way that I know of to retrieve them. A Bitmap query using the column ID will fail as follows:
```
curl localhost:10101/index/repository/query \
     -X POST \
     -d 'Bitmap(frame="stargazer", repo_id=10)'
{"error":"Bitmap() cannot retrieve columns unless inverse storage enabled"}
```

### Success criteria (What criteria will consider this ticket closeable?)
We need to either disallow SetColumnAttrs if inverse frames is not enabled, or provide some way to retrieve column attrs without the bitmap.

**Comment by yuce** [comment]
@jaffee Adding `?columnAttrs=true` returns column attrs even for frames where inverseEnabled==false:
```
curl -XPOST 'localhost:10101/index/myindex/query?columnAttrs=true' -d 'Bitmap(frame="f1", rowID=1)'
{"results":[{"attrs":{},"bits":[100]}],"columnAttrs":[{"id":100,"attrs":{"a":1,"b":2,"frame":"f1"}}]}
```

**Comment by jaffee** [comment]
ah, good tip, thanks @yuce . Does that seem a bit strange to you? (or anyone?) to use a query arg to change the behavior of PQL?

**Comment by yuce** [comment]
I think we definitely should have another look at PQL.

**Comment by jaffee** [comment]
Let's move the columnAttrs=true arg into PQL and get rid of the query arg.

**Comment by yuce** [comment]
Adding `columnAttrs=true` to PQL directly has the potential to open a can of worms.

- Which PQL calls would support `columnAttrs=true` ? What happens in a nested query? (e.g., the user can specify it in the outmost call or one or more of the inner calls)
- That requires a change in proto files.
- Some client library queries become worse. e.g., we have to change the Go client, so it's like: `frame.Bitmap(5, true)` or `frame.BitmapWithColumns(5)` (if we will support `columnAttrs` for other calls too, then we need to have a lot of similar looking functions).

**Comment by jaffee** [comment]
All good points - sounds like we'll need to put more thought into this. 

Do you think it's ok the way it is @yuce ? How do the client libraries expose this functionality now?

**Comment by yuce** [comment]
We can add a new call, maybe something like: `ReturnProfiles(...)` which can be used at the outermost of bitmap queries: `ReturnProfiles(Bitmap(frame="foo", rowID=5))`. If the innermost query is not a bitmap query, that would return a syntax error (like: `ReturnProfiles(SetBit(...))`)

Currently, the users set `Columns: true` in their `QueryOptions` object, which is used to set the `Columns` field of the protobuf `QueryRequest` object.

**Comment by travisturner** [comment]
closing this and moving discussion to the proposal in #700
