### ISSUE TITLE
Delete attributes

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#534]
For feature requests, please provide the following:

### Description
There is no way to delete row or column attributes. 

`ClearRowAttrs(frame=foo, rowID=4, name, amount)` would clear attributes `name` and `amount`.

or

`SetRowAttrs(frame=foo, rowID=4, name=None, amount=4.3)` would clear attribute `name`.

### Success criteria (What criteria will consider this ticket closeable?)
A PQL command is available to delete attributes.

**Comment by benbjohnson** [comment]
This is already supported by using `SetRowAttrs(frame=foo, rowID=4, name=null)`.

**Comment by alanbernstein** [comment]
Thanks for the info - I'll add that to the docs
