### ISSUE TITLE
Proposal: Input Definition

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#538]
# Input Definition Proposal

## Description

The purpose of the Input Definition is to provide a way for a user to define
a schema based on their data. This allows the user to provide data to Pilosa in 
a more standard format (for example: json or csv) instead of writing custom application
code to do low-level operations like `SetBit()`.

Once a user has provided an Input Definition, then they can send data to Pilosa in
a format that adheres to that definition and Pilosa will internally perform all
of the appropriate mutations.

### /input-definition/<name>

Use this endpoint to get, create, or delete and Import Defintion.

Get an Input Definition:
```
GET /input-definition/taxi-ride

Return: {json}
```

Create an Input Definition:
```
POST /input-definition/taxi-ride -d "<json>"

Return: ??
```

Delete an Input Definition:
```
DELETE /input-definition/taxi-ride

Return: ??
```

### /input

Use this endpoint to send an input payload to Pilosa.

Send data as a json object:
```
POST /input/taxi-ride -d "<json>"
Content-Type: application/json
```

Send data as a csv record:
```
POST /input/taxi-ride -d "<csv>"
Content-Type: text/csv
```

The following two endpoints are optional and really just meant to be available
to help a user construct their payload objects in the correct format.
Retrieve an example input data payload:
```
GET /input/taxi-ride
Content-Type: text/csv

Return: <csv>
```

```
GET /input/taxi-ride
Content-Type: application/json

Return: {json}
```

### Sample Input Definition (json)

```
{
    "frames": {
        "event-time": {
            "timeQuantum": "YMD",
            "inverseEnabled": false,
            "cacheType": "ranked",
        },
        "pickup-year": {
            "inverseEnabled": false,
            "cacheType": "ranked",
        },
        "pickup-month": {
            "inverseEnabled": false,
            "cacheType": "ranked",
        },
        "dropoff-year": {
            "inverseEnabled": false,
            "cacheType": "ranked",
        },
        "dropoff-month": {
            "inverseEnabled": false,
            "cacheType": "ranked",
        },
        "cab-type": {
            "inverseEnabled": false,
            "cacheType": "lru",
        },
        "distance-miles": {
            "inverseEnabled": false,
            "cacheType": "ranked",
        },
        "total-fare": {
            "inverseEnabled": false,
            "cacheType": "ranked",
        },
        "add-ons": {
            "inverseEnabled": false,
            "cacheType": "lru",
        },
    },
    "fields": [
        {
            "name": "id",
            "primaryKey": true,
        },
        {
            "name": "cabType",
            "actions": [
                {
                    "frame": "cab-type",
                    "valueDestination": "mapping",
                    "valueMap": {
                        "Green": 1,
                        "Yellow": 2,
                    }
                },
            ]
        },
        {
            "name": "pickupTime",
            "actions": [
                {
                    "frame": "event-time",
                    "valueDestination": "single-row-boolean",
                    "rowID": 1,
                },
                {
                    "frame": "pickup-year",
                    "valueDestination": "value-to-row",
                    "function": "dateFmt(${pickupTime}, 'YYYY')",
                },
                {
                    "frame": "pickup-month",
                    "valueDestination": "value-to-row",
                    "function": "dateFmt(${pickupTime}, 'MM')",
                },
            ]
        },
        {
            "name": "dropoffTime",
            "actions": [
                {
                    "frame": "event-time",
                    "valueDestination": "single-row-boolean",
                    "rowID": 2,
                },
                {
                    "frame": "dropoff-year",
                    "valueDestination": "value-to-row",
                    "function": "dateFmt(${dropoffTime}, 'YYYY')",
                },
                {
                    "frame": "dropoff-month",
                    "valueDestination": "value-to-row",
                    "function": "dateFmt(${dropoffTime}, 'MM')",
                },
            ]
        },
        {
            "name": "pickupLat",
        },
        {
            "name": "pickupLon",
        },
        {
            "name": "dropoffLat",
        },
        {
            "name": "dropoffLon",
        },
        {
            "name": "numPassengers",
            "actions": [
                {
                    "frame": "num-passengers",
                    "valueDestination": "value-to-row",
                },
            ]
        },
        {
            "name": "distanceMiles",
            "actions": [
                {
                    "frame": "distance-miles",
                    "valueDestination": "value-to-row",
                    "function": "int(${distanceMiles})",
                },
            ]
        },
        {
            "name": "totalFare",
            "actions": [
                {
                    "frame": "total-fare",
                    "valueDestination": "value-to-row",
                    "function": "int(${totalFare})",
                },
            ]
        },
        {
            "name": "withPet",
            "actions": [
                {
                    "frame": "add-ons",
                    "valueDestination": "single-row-boolean",
                    "rowID": 100,
                },
            ]
        },
        {
            "name": "withGroceries",
            "actions": [
                {
                    "frame": "add-ons",
                    "valueDestination": "single-row-boolean",
                    "rowID": 101,
                },
            ]
        },
    ],
    "multiField": [
        {
            "fields": ["pickupTime", "dropoffTime"],
            "function": "${dropoffTime} - ${pickupTime}",
        },
        {
            "fields": ["pickupLat", "pickupLon"],
            "function": "chart(${pickupLat}, ${pickupLon})",
            "actions": [
                {
                    "frame": "pickupGrid",
                }   
            ]
        },
        {
            "fields": ["dropoffLat", "dropoffLon"],
            "function": "chart(${dropoffLat}, ${dropoffLon})",
            "actions": [
                {
                    "frame": "dropoffGrid",
                }   
            ]
        },
    ],
}
```

### Source Data (json)

```
{
    "id": 1,
    "cabType", "Yellow",
    "pickupTime": "2017-05-08 13:00:00",
    "dropoffTime": "2017-05-08 13:37:00",
    "pickupLat": 0.4567777,
    "pickupLon": 0.4567777,
    "dropoffLat": 0.4567777,
    "dropoffLon": 0.4567777,
    "numPassengers": 3,
    "distanceMiles": 14.1,
    "totalFare", 47.25,
    "withPet", true,
    "withGroceries", false,
}
```

### Source Data (csv)
```
1,Yellow,"2017-05-08 13:00:00","2017-05-08 13:37:00",0.4567777,0.4567777,0.4567777,0.4567777,3,14.1,47.25,true,false,
```

## Notes
- All endpoints described above are assumed to  be nested under an `/index/<index>` endpoint.
- The `frames` list should support any `FrameOptions`, and submitting an Input Definition containing frame definitions will create any frames that are defined and do not already exist.
- The `fields` list in the Input Definition are required to be in order for csv payloads. For json payloads, order
doesn't matter as the name of the json attribute will need to match on `field.name`.
- Exactly one field must be marked `"primaryKey": true`.
- `actions` are not required; a field with no `actions` may be ignored, or it may be used in a `multiField` action.
- There are three options for `valueDestination`:
    - `value-to-row`: the value for this field is used as the `rowID`
    - `single-row-boolean`: the value must be a boolean, and this specifies `SetBit()` or `ClearBit()
        - A `rowID` must be specified for this destination type.
    - `mapping`: the value for this field is used to lookup a `rowID` in a map.
        - A `valueMap` is required for this destination type.
- The function support is within scope of this proposal, but as of yet there is no suggestion on how to best
implement this. The examples in this proposal are just placeholders.
- Fields provided in the payload which are not part of the Input Definition are ignored. Of course for csv, because
order matters, this would imply that additional field are appended to the end of the usable payload.
- If the payload does not contain all of the fields specified in the Input Definition, Pilosa can still apply
mutations for fields that it receives. Missing fields that are part of `multiField` actions would be mean those
`multiField` actions would be ignored. If the payload type is csv, then we should probably raise an error.

**Comment by benbjohnson** [comment]
I think that allowing JSON and CSV formats makes a lot of sense. I'm worried about adding a transformation language though. I think it'll either be limited and not useful or it will be extensive and too complicated. What's the benefit to adding our own language versus having users transform their data using the programming language of their choice?

**Comment by yuce** [comment]
Would the proposal be implemented as a core feature or as a plugin? IMO the latter would be much better in order to keep the core server simple.

**Comment by alanbernstein** [comment]
I agree with Ben about the transformation language, but I think there might be a useful middle ground. Supporting arbitrary functions is probably too far; formatting timestamps to integers as a special case is more feasible and more generally useful. For the taxi data, computing `multiField` values on the client would be minimal overhead. More use cases will help understand whether any other transformation support makes sense.

I do think it is appropriate for Pilosa to be aware of these mappings on some level, when they are a critical part of the schema in a use case like this.

**Comment by alanbernstein** [comment]
We could avoid the int casts, with default behavior of rounding any float values. 

The `chart(${dropoffLat}, ${dropoffLon})` function example, in a real application, would probably be some sort of lookup of real-world geographical regions.

**Comment by travisturner** [comment]
closing this proposal and opening a simplified version as Epic #607
