### ISSUE TITLE
Get all rowID for a frame/index

### ISSUE THREAD

**Issue by linhvo** [pilosa/pilosa#547]
### Description
Users are not able to get all bitmap that they import now. We might want to support that to know total of bitmap for each frame or index

### Success criteria (What criteria will consider this ticket closeable?)

Probably create new PQL to get all bitmap or count all bitmap, something like:

For each frame:
`curl -XPOST "http://127.0.0.1:10101/index/foo/query" -d 'GetAll(frame="bar")'` returns all rowID for frame="bar"
`curl -XPOST "http://127.0.0.1:10101/index/foo/query" -d 'CountAll(frame="bar")'` return count of all row ID for frame="bar"

For an index:
`curl -XPOST "http://127.0.0.1:10101/index/foo/query" -d 'GetAll()'` returns all rowID for index="foo"
`curl -XPOST "http://127.0.0.1:10101/index/foo/query" -d 'CountAll()'`returns count of all rowID for index="foo"

**Comment by travisturner** [comment]
I'd like to understand the use case here a little better.

Thoughts in no particular order:
- I don't understand the need to return all rows for an index. I suppose you could return all rows for all frames, but I'm not clear what the use case for that would be.
- We could consider storing rowIDs in something like an in-memory [B-Tree](http://godoc.org/github.com/google/btree), but I don't think every node necessarily has knowledge of every rowID (only the rowIDs which contain data located on the fragment(s) on any particular node), so asking the cluster for all rowIDs would require asking all nodes and doing some kind of merge; or it would require, alternatively, broadcasting the existence of all rowIDs to all nodes.
- we could consider using Pilosa's inverse view to store the existence of a rowID (basically a bitmap that represents not-null for a rowID). I'm not sure how this may affect performance/storage.

**Comment by jaffee** [comment]
I agree that this kind of functionality (getting all rows in a frame) is desirable. I have several concerns.

Having this functionality internally would definitely be good - as would exposing it to plugins. I would hesitate to this to PQL though. This is the kind of thing that a robust query language would support implicitly rather than adding a separate call. This feature also has overlap with TopN which bothers me - the more elegant way to do this is have a single function which returns rows, and filters and sorting can be applied. 

All that said, I hope that however we do this can stream the results in order to support large numbers of rows in a performant way.

**Comment by linhvo** [comment]
I agree that getting all rows in a frame has overlap with TopN. If I want to get all intersection of 1 single rows and all other rows in the frames with cacheSize equals to all rows, TopN actually returns intersection for all rows in the frame. However, if we keep continue import rowID without changing cacheSize, I'm not able to get all the results with TopN since TopN only returns results within cacheSize as I understand. That means this feature doesn't need to be supported if cacheSize is set big enough with growing data.

Also, `count` all rowID in a frame might be helpful when I import 1000 rows, and I would like to know all 1000 rows are imported correctly without exporting them out. 

I also agree that returning all rows for an index is not necessary, because I can have that number if getting all rows in a frame is supported.

**Comment by jaffee** [comment]
Todd's work in #1496 covers this.
