### ISSUE TITLE
Leveled Logging

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#579]
#Proposal: Pilosa Level Logging
Author: Michael Baird
Last updated: 2017/05/24

##Abstract
It would be great to have a standardized level logging system in Pilosa.  

##Background
The are several used cases where it would be convenient to adjust the logging level of Pilosa from testing to production, etc.   There are other packages with more granular levels but I feel these 4 levels would be sufficient:
Info
Warning
Error
Fatal

##Compatibility
There are several leveled logging packages to choose from.  We should evaluate them first before proceeding
 - glog (this seems a great fit for what we need)
 - zap
 - jww

##Implementation:
We will need to decide the logging level for all existing log statements.
Once that is determined replace all existing logging calls with the appropriate level

**Comment by codysoyland** [comment]
Alan brought this up during standup: https://dave.cheney.net/2015/11/05/lets-talk-about-logging

**Comment by raskle** [comment]
After reading through several logging options I'm voting in favor of Google glog
https://github.com/golang/glog
It seems to have everything I'd want is a logging package and support 4 levels:
INFO
WARNING
ERROR
FATAL

**Comment by jaffee** [comment]
glog seems nice and simple - no external dependencies, but I'm concerned that the way it uses flags may be incompatible with Pilosa. It defines flags globally in an init function using Go's `flag` package. I don't know if there is any clean way to bring that configuration under Pilosa's way of doing configuration.

**Comment by jaffee** [comment]
The Dave Cheney post makes a good case for:
- Warn should not exist.
- ERROR/FATAL logs should only happen at the top level (in your main func)
- Really, the only log levels you need are INFO and DEBUG.
- It should only be possible to turn on and off the DEBUG logs.

Cheney has another post: https://dave.cheney.net/2017/01/23/the-package-level-logger-anti-pattern
This one warns about coupling your libraries directly to certain logging packages. Pilosa is an application, but it is composed of a number of libraries which could very well be useful on their own (i.e. github.com/pilosa/pilosa/roaring and github.com/pilosa/pilosa/pql). It would be a shame to force a consumer of these libraries into a particular choice of logging package.

I guess my point is that it seems like the only thing we REALLY desire is a way to turn DEBUG logs on and off (maybe on a granular level i.e. per package). Does anyone have a strong use case for leveled logging other than that?

**Comment by raskle** [comment]
I like the above approach.  Could it be implemented similar to the StatsClient Interface.
With interfaces for:
func Info(args ...interface{})
func Debug(args ...interface{})

Then in server. go the user could determine the logging package they prefer and implement the interface wrapper to the logging levels we require?

**Comment by jaffee** [comment]
I think that's the right track @raskle

**Comment by travisturner** [comment]
@raskle can you open a new issue with detailed specs around this final decision.
