### ISSUE TITLE
BroadcastReceiver Start: Error Handling

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#584]
### Description
We need more test coverage of the BroadcastReceiver Start() error conditions.

### Success criteria (What criteria will consider this ticket closeable?)
This will enable us to confidently exercise the Server.Open() error handling.

**Comment by travisturner** [comment]
We don't actually have any error conditions in any of the `BroadcastReceiver.Start()` implementations. Its only purpose is to wire up the `BroadcastHandler`. In theory we could safely remove `error` from the function signature since it isn't being used.
