### ISSUE TITLE
Proposal: Use Range-Encoded BSI to support range and aggregate queries

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#588]
# Bit-Sliced Index (Range Encoded)

## Description

This proposal describes a method by which one can store multi-bit integers in Pilosa and evaluate
aggregate and range queries on those integers. Integers shall be stored as n-bit, range-encoded
bit-sliced indexes of base-2, plus an additional bitmap indicating "not null". This means that a 16-bit integer will require 17 bitmaps: one for each 0-bit of the 16 bit-slice components (the 1-bit does not need to be stored because with range-encoding the highest bit position is always `1`) and one for the non-null bitmap.

### Need

The following is a high-level list of things Pilosa would need to have in order to allow us to provide support for range-encoded values.

- input support for an integer
    - a received integer is converted to a range-encoded, n-bit value
    - for base-2, this is the FLIP of the binary version of the integer.
        - ex. base-10 integer = 14, 8-bit binary = `0000 1110`, base-2 range-encoded = `1111 0001`
    - store the `1` values in Pilosa (unless of course we are allowing UPDATE, in which case we need to also store the `0` values with `ClearBit()`)
- frame definition
    - define fields and types (or ranges)
        - ex: age int7 (range 0-120)
        - ex: salary int24 (range 0 - 10,000,000)
    - internally Pilosa stores the field, the range (and range size), and the rowID offset 

```
curl -X POST "http://localhost:10101/index/i/frame/f" -d '{"options":{"fields": [("F", int16)]}}'

curl -X POST "http://localhost:10101/index/i/query" -d '
    Set(frame="f", columnID=0, F=970)
    Set(frame="f", columnID=1, F=860)
    Set(frame="f", columnID=2, F=950)
    Set(frame="f", columnID=3, F=41)
    Set(frame="f", columnID=5, F=859)
'
```

|    | base10 | B₁₆⁰ | B₁₅⁰ | B₁₄⁰ | B₁₃⁰ | B₁₂⁰ | B₁₁⁰ | B₁₀⁰ | B₉⁰ | B₈⁰ | B₇⁰ | B₆⁰ | B₅⁰ | B₄⁰ | B₃⁰ | B₂⁰ | B₁⁰ |
|----| ------:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| C₀ |   970  |   1  |   1  |   1  |   1  |   1  |   1  |   0  |  0  |  0  |  0  |  1  |  1  |  0  |  1  |  0  |  1  |
| C₁ |   860  |   1  |   1  |   1  |   1  |   1  |   1  |   0  |  0  |  1  |  0  |  1  |  0  |  0  |  0  |  1  |  1  |
| C₂ |   950  |   1  |   1  |   1  |   1  |   1  |   1  |   0  |  0  |  0  |  1  |  0  |  0  |  1  |  0  |  0  |  1  |
| C₃ |    41  |   1  |   1  |   1  |   1  |   1  |   1  |   1  |  1  |  1  |  1  |  0  |  1  |  0  |  1  |  1  |  0  |
| C₄ |  NULL  |   1  |   1  |   1  |   1  |   1  |   1  |   1  |  1  |  1  |  1  |  1  |  1  |  1  |  1  |  1  |  1  |
| C₅ |   859  |   1  |   1  |   1  |   1  |   1  |   1  |   0  |  0  |  1  |  0  |  1  |  0  |  0  |  1  |  0  |  0  |

#### Frame: f
| field | rowID | C₀ | C₁ | C₂ | C₃ | C₄ | C₅ |
|:------|------:|:--:|:--:|:--:|:--:|:--:|:--:|
|  Fⁿⁿ  |    0  |  1 |  1 |  1 |  1 |  0 |  1 |
|  F₁   |    1  |  1 |  1 |  1 |  0 |  1 |  0 |
|  F₂   |    2  |  0 |  1 |  0 |  1 |  1 |  0 |
|  F₃   |    3  |  1 |  0 |  0 |  1 |  1 |  1 |
|  F₄   |    4  |  1 |  1 |  1 |  1 |  1 |  1 |
|  F₅   |    5  |  0 |  0 |  1 |  0 |  1 |  0 |
|  F₆   |    6  |  1 |  1 |  0 |  0 |  1 |  1 |
|  F₇   |    7  |  0 |  0 |  1 |  1 |  1 |  0 |
|  F₈   |    8  |  0 |  1 |  0 |  1 |  1 |  1 |
|  F₉   |    9  |  0 |  0 |  0 |  1 |  1 |  0 |
|  F₁₀  |   10  |  0 |  0 |  0 |  1 |  1 |  0 |
|  F₁₁  |   11  |  1 |  1 |  1 |  1 |  1 |  1 |
|  F₁₂  |   12  |  1 |  1 |  1 |  1 |  1 |  1 |
|  F₁₃  |   13  |  1 |  1 |  1 |  1 |  1 |  1 |
|  F₁₄  |   14  |  1 |  1 |  1 |  1 |  1 |  1 |
|  F₁₅  |   15  |  1 |  1 |  1 |  1 |  1 |  1 |
|  F₁₆  |   16  |  1 |  1 |  1 |  1 |  1 |  1 |

### Range Query: GT, GTE

```
// Bᵏ represents the bitmap that passes the condition and therefore we want to keep.
// Initialize Bᵏ to the bitmap of all 0's (represented by Bₓ₀).
// Over the iteration we will only add C's to Bᵏ.
Bᵏ = Bₓ₀

// Bᶠ represents the bitmap filter that we want to segment on
// If Bᶠ is not provided, initialize Bᶠ to the bitmap of all 1's (represented by Bₓ₁).
// Over the iteration we will only remove C's from Bᶠ.
if !exists(Bᶠ):
    Bᶠ = Bₓ₁

// Scan Bⁿⁿ for use in filtering
Fⁿⁿ

// Update Bᶠ to only consider non-null values.
Bᶠ = Bᶠ AND Fⁿⁿ

// Z is the comparison value we use to check "greater than"
// In our example, Zⁿ is the nᵗʰ bit of the 16-bit binary representation of Z.
// Zᵢ₀₁ represents the iᵗʰ bit of Z as every bit position in an n-bit value.
// If Zᵢ is 1, then Zᵢ₀₁ = 1111 1111 1111 1111
// Z = 845 is represented as bits 16 to 1 below.
Z = 0000 0011 0100 1101


// Specifies whether the comparison type is "greater than" (GT) or "greater
// than or equal to" (GTE).
comparisonType

// In our example, n = 16
leadingDigits = true
for i = n; i > 0; i--:
    if (leadingDigits) && (Fᵢ == Bₓ₁) && (Zᵢ == 0):
        continue // we can skip the most significant zero valued bit positions
    leadingDigits = false // no longer check for leading digits to skip

    // Add any bit positions (C) that we know we want to keep (Bᵏ) based on the fact
    // that Fᵢ for C is greater than Zᵢ. Only consider those C that we haven't 
    // already determined to be excluded (Bᶠ).
    Bᵏ = (Bᵏ OR (Fᵢ NOR Zᵢ₀₁)) AND Bᶠ

    // The only difference between > and >= is in the comparison on the final bit
    // position. Based on the comparison type, we may be able to return early.
    if i == 1 && comparisonType == "GT":
        return Bᵏ

    // Remove any bit positions (C) that we have determined do not satisfy
    // the comparison with Z.
    // Note: an XOR in place of the NAND should logically give the same result
    // because we have already included the NOR (0-0) case in Bᵏ.
    Bᶠ = (Bᶠ AND (Fᵢ NAND Zᵢ₀₁)) OR Bᵏ

// The final return value
return Bᶠ
```

### Range Query: LT, LTE

```
// Bᵏ represents the bitmap that passes the condition and therefore we want to keep.
// Initialize Bᵏ to the bitmap of all 0's (represented by Bₓ₀).
// Over the iteration we will only add C's to Bᵏ.
Bᵏ = Bₓ₀

// Bᶠ represents the bitmap filter that we want to segment on
// If Bᶠ is not provided, initialize Bᶠ to the bitmap of all 1's (represented by Bₓ₁).
// Over the iteration we will only remove C's from Bᶠ.
if !exists(Bᶠ):
    Bᶠ = Bₓ₁

// Scan Bⁿⁿ for use in filtering
Fⁿⁿ

// Update Bᶠ to only consider non-null values.
Bᶠ = Bᶠ AND Fⁿⁿ

// Z is the comparison value we use to check "greater than"
// In our example, Zⁿ is the nᵗʰ bit of the 16-bit binary representation of Z.
// Zᵢ₀₁ represents the iᵗʰ bit of Z as every bit position in an n-bit value.
// If Zᵢ is 1, then Zᵢ₀₁ = 1111 1111 1111 1111
// Z = 845 is represented as bits 16 to 1 below.
Z = 0000 0011 0100 1101


// Specifies whether the comparison type is "less than" (LT) or "less
// than or equal to" (LTE).
comparisonType

// In our example, n = 16
leadingDigits = true
for i = n; i > 0; i--:
    if (leadingDigits) && (Fᵢ == Bₓ₁) && (Zᵢ == 0):
        continue // we can skip the most significant zero valued bit positions
    leadingDigits = false // no longer check for leading digits to skip

    // Treat < and <= differently on the final bit position.
    if i == 1:
        if comparisonType == "LT":
            Bᶠ = (Bᶠ AND (Fᵢ AND Zᵢ₀₁)) OR Bᵏ
        elif comparisonType == "LTE":
            Bᶠ = (Bᶠ AND (Fᵢ OR Zᵢ₀₁)) OR Bᵏ
    else:
        // Add any bit positions (C) that we know we want to keep (Bᵏ) based on the fact
        // that Fᵢ for C is greater than Zᵢ. Only consider those C that we haven't
        // already determined to be excluded (Bᶠ).
        Bᵏ = (Bᵏ OR (Fᵢ AND Zᵢ₀₁)) AND Bᶠ

        // Remove any bit positions (C) that we have determined do not satisfy
        // the comparison with Z.
        // Note: an XOR in place of the OR should logically give the same result
        // because we have already included the AND (1-1) case in Bᵏ.
        Bᶠ = (Bᶠ AND (Fᵢ OR Zᵢ₀₁)) OR Bᵏ

// The final return value
return Bᶠ
```

### Range Query: EQ

```
// Bᵏ represents the bitmap that passes the condition and therefore we want to keep.
// Initialize Bᵏ to the bitmap of all 0's (represented by Bₓ₀).
// Over the iteration we will only add C's to Bᵏ.
Bᵏ = Bₓ₀

// Bᶠ represents the bitmap filter that we want to segment on
// If Bᶠ is not provided, initialize Bᶠ to the bitmap of all 1's (represented by Bₓ₁).
// Over the iteration we will only remove C's from Bᶠ.
if !exists(Bᶠ):
    Bᶠ = Bₓ₁

// Scan Bⁿⁿ for use in filtering
Fⁿⁿ

// Update Bᶠ to only consider non-null values.
Bᶠ = Bᶠ AND Fⁿⁿ

// Z is the comparison value we use to check "greater than"
// In our example, Zⁿ is the nᵗʰ bit of the 16-bit binary representation of Z.
// Zᵢ₀₁ represents the iᵗʰ bit of Z as every bit position in an n-bit value.
// If Zᵢ is 1, then Zᵢ₀₁ = 1111 1111 1111 1111
// Z = 845 is represented as bits 16 to 1 below.
Z = 0000 0011 0100 1101


// Specifies whether the comparison type is "equal to" (EQ)
comparisonType

// In our example, n = 16
leadingDigits = true
for i = n; i > 0; i--:
    if (leadingDigits) && (Fᵢ == Bₓ₁) && (Zᵢ == 0):
        continue // we can skip the most significant zero valued bit positions
    leadingDigits = false // no longer check for leading digits to skip

    Bᶠ = (Bᶠ AND (Fᵢ XOR Zᵢ₀₁))

// The final return value
return Bᶠ
```

### Aggregation Query: Sum

```
// Bᶠ represents the bitmap filter that we want to segment on
Bᶠ

// Scan Bⁿⁿ for use in filtering
Fⁿⁿ

// Update Bᶠ to only consider non-null values.
Bᶠ = Bᶠ AND Fⁿⁿ

// CNT represents the total number of items in the filter.
CNT = Count(Bᶠ)

// SUM, initialized to 0, holds the return value
SUM = 0


// In our example, n = 16
for i = n; i > 0; i--:
    if (Fᵢ == Bₓ₁):
        continue // we can skip any row that is all 1's (i.e. all 0 values)
    SUM += 2^(i-1) * (CNT - Count(Fᵢ AND Bᶠ))

// The final return value
return SUM
```

**Comment by tgruben** [comment]
Will the format of the result of the range query be a list of "field bitmaps"  that satisfy that range @travisturner ?

**Comment by travisturner** [comment]
@tgruben The result of the range query would be a bitmap with a bit set for any column that satisfies the range. With that being the case, one could use a `Range()` query anywhere that a `Bitmap` query is used; ex: `Intersect(Range(), Bitmap())`

**Comment by alanbernstein** [comment]
The logic makes sense. Some questions about the interface:

In `{"fields": [("F", int16)]}`, is `"F"` an arbitrary name, and chosen to be short for brevity?

Will we support changing the bit width of a field, in the first version, or later, or never?

How difficult will it be to integrate an integer range query into the TopN filter syntax? I think that could be done independently, but if we want to support that, this proposal is a good place to mention it.

I wonder if an `Increment` command would be useful, or expected.

**Comment by alanbernstein** [comment]
There is no way to retrieve the value of field F for column C, right? Should we support retrieving single field values by columnID, full lists of field values, filtered lists?

**Comment by alanbernstein** [comment]
`int16` suggests signed type, which is not directly supported here. We should change that to `uintN`. Signed can also be supported, one approach is to apply an offset of ±(2**N)/2, but maybe there is a smarter way.

**Comment by travisturner** [comment]
@alanbernstein 
Yes `"F"` was arbitrary and chosen for brevity.
Good point about `int` vs `uint`; I was thinking that the user might not actually specify a type or size, but rather only specify a valid range of positive integers (I haven't considered negative, but your offset suggestion seems reasonable). For example `{"fields": [("F", min=100, max=2000)]}` which we could represent with an 11-bit integer.
I think both `FieldList` and `FieldValue` could be implemented although I can't speak to how performant it would be.

**Comment by travisturner** [comment]
@alanbernstein @tgruben I added the logic for `LT`, `LTE`, and `EQ`

**Comment by travisturner** [comment]
I'm closing this discussion. Further discussion can happen on tickets found under Epic #615
