### ISSUE TITLE
Runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by jarutis** [pilosa/pilosa#591]
Hi,

I tried to use pilosa with uint64 values, however it seems that the server stops working after I index a large value. I followed getting started tutorial with the following steps:

```
$ curl localhost:10101/index/repository  -X POST  -d '{"options": {"columnLabel": "repo_id"}}'
{}
$ curl localhost:10101/index/repository/frame/stargazer  -X POST -d '{"options": {"rowLabel": "stargazer_id",  "timeQuantum": "YMD", "inverseEnabled": true}}'
{}
$ curl localhost:10101/index/repository/frame/language  -X POST -d '{"options": {"rowLabel": "language_id", "inverseEnabled": true}}'
{}
```

Imported data from the tutorial, played with all works fine. But if I run:

```
$ curl localhost:10101/index/repository/query -X POST -d 'SetBit(frame="stargazer", repo_id=77777, stargazer_id=6018148517796380732)'
{"results":[true]}
$ curl localhost:10101/index/repository/query -X POST -d 'Bitmap(frame="stargazer", stargazer_id=6018148517796380732)'
curl: (52) Empty reply from server
```

And the server prints the following error:

```
2017/05/31 10:18:51 http: panic serving 127.0.0.1:46892: runtime error: makeslice: len out of range
goroutine 16 [running]:
net/http.(*conn).serve.func1(0xc420e51b80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xa41ae0, 0xc428682d00)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/pilosa/pilosa.(*Executor).Execute(0xc420258690, 0xde71c0, 0xc420876840, 0xc4208766fc, 0xa, 0xc4254dd860, 0xc428682cf8, 0x1, 0x1, 0xc428682c20, ...)
	/Users/cody/gopath/src/github.com/pilosa/pilosa/executor.go:97 +0x1ba
github.com/pilosa/pilosa.(*Handler).handlePostQuery(0xc4201dc100, 0xde62c0, 0xc420ad7930, 0xc4208f1950)
	/Users/cody/gopath/src/github.com/pilosa/pilosa/handler.go:204 +0x34b
github.com/pilosa/pilosa.(*Handler).(github.com/pilosa/pilosa.handlePostQuery)-fm(0xde62c0, 0xc420ad7930, 0xc4208f1950)
	/Users/cody/gopath/src/github.com/pilosa/pilosa/handler.go:93 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4201d9ef0, 0xde62c0, 0xc420ad7930, 0xc4208f1950)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/pilosa/pilosa/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201f00a0, 0xde62c0, 0xc420ad7930, 0xc4208f1950)
	/Users/cody/gopath/src/github.com/pilosa/pilosa/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
github.com/pilosa/pilosa.(*Handler).ServeHTTP(0xc4201dc100, 0xde62c0, 0xc420ad7930, 0xc4208f1770)
	/Users/cody/gopath/src/github.com/pilosa/pilosa/handler.go:129 +0x4d
net/http.serverHandler.ServeHTTP(0xc42011e700, 0xde62c0, 0xc420ad7930, 0xc4208f1770)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420e51b80, 0xde7100, 0xc4253b8400)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

And all consecutive Bitmap queries fail with the same error.
### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

I tried this on solo version on OS X using binary release, Docker, Amazon AWS instance with Amazon Linux AMI release 2017.03, 4.4.35-33.55.amzn1.x86_64, 16GB ram using binary release. Same result everywhere.

P.S. It seems like an awesome product! Thanks.

**Comment by jaffee** [comment]
In any case, we should guard against this condition and fail gracefully if we decide we can't handle it - returning a reasonable error to the client. I'm going to make this ticket for catching the immediate bug, and break out another for longer term work.

Incidentally @jarutis do you have a use case which requires setting arbitrary integers in the entire 64 bit range? How important is this behavior for you? We'd be very interested to better understand how you're using Pilosa.

**Comment by jarutis** [comment]
I work in the adtech area and user IDs are usually stored as uint64 (in our case we get them from external systems). Uint32 would likely be enough, but we would have to store additional mapping, which brings a more complexity. I planned to developed something similar like you have done for calculating overlaps between various user segments before stumbling upon this project :)

**Comment by alanbernstein** [comment]
@jarutis Note that the query endpoint accepts a `slices` parameter which can be used as a rough workaround for this issue, depending on your use case.

https://www.pilosa.com/docs/api-reference/ will soon be updated to reflect this.

**Comment by jaffee** [comment]
I believe we can close this now via https://github.com/pilosa/pilosa/pull/741
