### ISSUE TITLE
Tutorial/docs for standing up a Pilosa cluster

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#595]
I think our docs don't sufficiently cover standing up and configuring a cluster - the various intra-cluster communication options are a bit arcane right now.

**Comment by travisturner** [comment]
Let's leave this until the gossip work is merged.

**Comment by yuce** [comment]
@jaffee @travisturner Can we close this? The docs at https://www.pilosa.com/docs/latest/configuration/#example-cluster-configuration and https://www.pilosa.com/docs/latest/tutorials/#how-to-setup-a-secure-cluster seem to cover this.

**Comment by jaffee** [comment]
yea I think we can close this - I think it has gotten simpler and the docs have improved. do we still have cluster.type and/or is that going away in the near future?

**Comment by yuce** [comment]
We have `cluster.type=gossip` which is the default and `cluster.type=static` which turns off clustering. `cluster.type=static` may be the default later: https://github.com/pilosa/pilosa/issues/870

**Comment by jaffee** [comment]
I think it would be better to remove the cluster.type option entirely, and just make pilosa smarter about how it chooses a gossip port to bind.

**Comment by travisturner** [comment]
@jaffee we have essentially done this, but the `cluster.type` is still present primarily for tests which run against a basic, single-node cluster and don't need to do anything with memberlist.

**Comment by jaffee** [comment]
I don't think we need to do this now (unless it's pretty easy), but I think we should change it to `cluster.disabled` and make it a boolean. That way it's more clear that this is specifically for single node deployments and not general usage. Having it called `type` and a `string` leaves open the option for many kinds of clusters and may be confusing.

**Comment by travisturner** [comment]
I implemented `cluster.disabled` in #1099.
