### ISSUE TITLE
Investigate container resizing strategy for diverse data sets

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#598]
### Description
This is at the top of roaring.go:
```
// manual allocation size tuned to our average client data
manualAlloc = 524288
```
This is a parameter for linear array resizing behavior, tuned to a specific expected index width. We should be aware of its impact on other data sets.

### Success criteria (What criteria will consider this ticket closeable?)
Support configuring this parameter, or other resizing options (exponential?); or explicitly accept this parameter as sufficient for general use.

**Comment by tgruben** [comment]
By default, Go slices grow by doubling until size 1024, after which they grow by 25% each time.  The manual  Go slice sizing scheme implemented currently was based on the average audience size of the original use case of pilosa in an attempt to decrease the number of times a costly  Go slice reallocation occurs. It should be noted that this is resizing of the go slice that maintains a collection of containers and not a specific container itself. This was an oversight on my part, and now that I have a better understanding of the roaring container's purpose, I believe we could achieve a more efficient method with a small initial capacity on bitmap creation.

**Comment by jaffee** [comment]
Sounds like someone is going to need to dive into this and investigate - let's move to backlog, and we can open up to wider discussion of tradeoffs when there is a better understanding of what's going on, and someone has enough understanding to make a recommendation.

**Comment by travisturner** [comment]
It appears that this was removed in d7272f46a231d289a81b006b1a21e58e0ce875c4 and 28d590c5751f2342ae5906d947a7aca3f650e473.
Is there any reason to keep this open @alanbernstein?

**Comment by jaffee** [comment]
this is probably obsolete as of the btree work anyway

**Comment by alanbernstein** [comment]
It's not clear to me why this was removed in d7272f4, but since it's gone we can close this. Agreed this is probably obsolete with btree, but if that ends up being an enterprise feature then we may need to revisit this.
