### ISSUE TITLE
Input Definition: input data endpoint

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#609]
Create an endpoint to accept an Input data in JSON or CSV format. This is part of the proposal described in #538. For phase one, we will be very strict on data format; if the data does not match the input definition exactly then we raise an error.

### /index/_idx_/input/_input-definition_

`idx` is the name of the index that the Input Definition is applied to
`input-definition` should match an Input Definition already registered with the cluster. If the Input Definition specified does not exist we should return an error.

Send data as a json object:
```
POST /index/idx/input/taxi-ride -d "<json>"
Content-Type: application/json
```

Send data as a csv record:
```
POST /index/idx/input/taxi-ride -d "<csv>"
Content-Type: text/csv
```

**Comment by raskle** [comment]
Only handle JSON data in the ticket.
