### ISSUE TITLE
Provide an API for deleting views

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#613]
### Description
This feature is particularly useful for time-based frames which can have a number of views growing over time. An example is a frame with `timeQuantum = "D"` where the user is interested in a rolling window of time like "that last 30 days". In this case, it would be useful to provide the ability for views older than 30 days to be deleted while the server is still running.

### Success criteria (What criteria will consider this ticket closeable?)
An endpoint exists that will delete a view:
```
curl -X DELETE localhost:10101/index/i/frame/f/view/standard_20170601
```
All directories and files associated to the view are removed.
I don't think it makes sense to delete anything other than time-based views at this point, so we could be very strict and return an error if the view is not time-based.

**Comment by alanbernstein** [comment]
To simplify the rolling window case, perhaps a frame option could be set to delete views automatically?

**Comment by jarutis** [comment]
That would be amazing :)

**Comment by raskle** [comment]
While planning this task I see that the Frame SetBit and ClearBit functions implicitly create Views with CreateViewIfNotExists.  This could be an issue while streaming in time data, and Pilose were processing time views that were recently truncated.  Resulting in new empty Views being created.  I think we should handle that and auto truncating Views with a rolling window in a separate ticket.

**Comment by raskle** [comment]
@travisturner in the case where we have inverse views setup should the Delete View API explicitly name the standard or inverse view to delete them?  Or should Pilosa automatically delete the inverse view?

**Comment by travisturner** [comment]
@raskle I think it should be explicit.
Also, I'm not sure I follow your example regarding the `CreateViewIfNotExists` issue you mention above. Do you mean that if you receive a timestamp represented by a view that does not exists, instead of creating it we should verify that the timestamp falls within a defined window. If it does, then we proceed with creating the view. If it does not, then we discard the data as out of bounds?
