### ISSUE TITLE
BSI Range-Encoding: PQL support for aggregate queries

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#622]
Calls the internal function created in #622.

```
Sum(Bitmap, frame="f", field="age")
Average(Bitmap, frame="f", field="age")
```
Like `TopN`, the `Bitmap` acts as a filter when provided and is optional.

Returns an `int` (or possibly `float` in the case of average?)

**Comment by benbjohnson** [comment]
Fixed via #778.
