### ISSUE TITLE
import data with input definition

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#628]
### Description
We need an api endpoint to ingest raw csv/json data described by an existing import definition.  This endpoint will need the definition name and raw data as a payload.  
I think we need to make a decision on whether to create a new /input to handle ingesting raw data tied to a definition or could we instead extend the existing /import API to support this functionality

### Implementation
/input API description

Send data as a json object:
```
POST /input/taxi-ride -d "<json>"
Content-Type: application/json
```

Send data as a csv record:
```
POST /input/taxi-ride -d "<csv>"
Content-Type: text/csv
```

The following two endpoints are optional and really just meant to be available
to help a user construct their payload objects in the correct format.
Retrieve an example input data payload:

```
GET /input/taxi-ride
Content-Type: text/csv

Return: <csv>
```
```
GET /input/taxi-ride
Content-Type: application/json

Return: {json}
```

### Compatibility
To reduce confusion we may consider combining the existing /import endpoint and cmd with the /input functionality.  There will be significant overlap in functionality and this could reduce user confusion with one method to ingest data.

The existing /import API ImportRequest Protobuf described a specific data structure with rows, columns and timestamps per index, frame, slice.
I am proposing that this existing format could represent a default import definition.
There will be overlap with the existing import command and ingesting raw data.
 - Both will need to be chunked into appropriate sizes before being sent to the api
 - Once the mapping is decoded we may want to sort the data by slice and by row for faster ingestion.

**Comment by travisturner** [comment]
I understand the urge to combine `input` with the existing `import`, but I would personally like to keep them separate for now. To me it will be more confusing if we try to make `import` do too many things at this stage. I can see us eventually adding support to the `import` that will be able to handle bulk data based on input definitions, but I would like to prove out a very strict version of `input` and learn from that first before we try to add complexity to `import`.

**Comment by raskle** [comment]
duplicate
