### ISSUE TITLE
Get RowAttrs without returning bit vector

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#632]
### Description
Currently, in order to get `RowAttrs` for a row, you have to perform the query:
```
Bitmap(frame="f", row=1)
```
This query returns something like:
```
{"results":[{"attrs":{"name":"row-one"},"bits":[101]}]}
```
There may be cases where a user wants to get the `attrs` for a `Bitmap()` query, but doesn't need the `bits` portion of the return.

### Success criteria (What criteria will consider this ticket closeable?)
A user has the ability to lookup `RowAttrs` for a `row_id`. To be decided is whether this is a new endpoint specific to this functionality, or if we add a query argument (similar to `columnAttrs`) that will alter the return of a query.

**Comment by travisturner** [comment]
Let's create a `BitmapAttrs()` function that performs the same action as `Bitmap()` except that it doesn't actually return the bits (i.e. it only returns the rowAttrs).

**Comment by yuce** [comment]
Does it make sense to remove attributes from the `Bitmap` result? So if a user is interested in bits, they can call `Bitmap`. If they are interested in attributes they can call `BitmapAttrs`.
