### ISSUE TITLE
Add support for literal positional arguments in PQL calls

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#640]
### Description

Currently, PQL supports only PQL calls as positional arguments, e.g.: `Union(Bitmap(frame='foo', rowID=1), Bitmap(frame='foo', rowID=2))` has two positional arguments which are calls.

It would be beneficial to allow other types, such as integers as positional arguments. See: https://github.com/pilosa/pilosa/issues/604

If we allowed integers as positional arguments, we could define a `Bits` call which would define an arbitrary bitmap for a frame:
```
Union(Bits(frame='foo', 5, 10, 100, 200), Bitmap(frame='foo', rowID=2))
```

### Success criteria (What criteria will consider this ticket closeable?)

Types mentioned in https://github.com/pilosa/pilosa/issues/604 can be passed to a PQL call.

**Comment by travisturner** [comment]
Let's have a larger discussion in #604, but closing this since we aren't wanting to devote a lot of resources to enhancing PQL right now. I think there will be other ways of interacting with Pilosa that are preferable and more performant.
