### ISSUE TITLE
Sending query request through php

### ISSUE THREAD

**Issue by vivekkumar159** [pilosa/pilosa#653]
I wanted to know is there a way to send the query request like this
curl localhost:10101/index/user/query -X POST -d 'Bitmap(frame="language", id=5)'.
through php ?

**Comment by yuce** [comment]
We don't have a PHP client library for Pilosa yet, but you may have a look at our documentation for our HTTP API at: https://www.pilosa.com/docs/api-reference/ It seems PHP has a curl module: http://php.net/manual/en/function.curl-exec.php. It should be pretty straightforward to use Pilosa API reference and that curl module to make queries.

**Comment by travisturner** [comment]
Hi @vivekkumar159 
If you don't have the php curl libraries available to you, you can query pilosa with php's `file_get_contents` which is part of core php. The following php script should perform your example query:

```
<?php

$url = 'http://localhost:10101/index/user/query';
$data = 'Bitmap(frame="language", id=5)';

$options = array(
    'http' => array(
        'method'  => 'POST',
        'content' => $data
    )
);
$context  = stream_context_create($options);
$result = file_get_contents($url, false, $context);

var_dump($result);

?>
```

**Comment by vivekkumar159** [comment]
Thanks for the help;

**Comment by travisturner** [comment]
No problem! Let us know if you have any other questions.
