### ISSUE TITLE
Input JSON data parser

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#654]
### Description
Write a parser for the input JSON data handler API.  
The parser will evaluate each field in the json file.  
Process the fields that match the string of a field specified in the input definition.
Use the defined action in the input definition to process this field value.
Construct a SetBit call with the processed values for the given Index and Frame.
Return an error if any field cannot be processed
Ignore fields that are not mapped to the input definition.

### Success criteria (What criteria will consider this ticket closeable?)
Parse an input json data object from the API, and construct a series of SetBit calls with the rules from the associated inputDefinition.

**Comment by travisturner** [comment]
@raskle I think we should raise an error if the input contains fields not defined in the input-definition. I'm less concerned with an input payload that does not contain the complete list of fields, but we could be very strict in that case as well if you think it makes sense.
