### ISSUE TITLE
Streaming Ingest improvements

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#666]
### Description

Ingestion via repeated or batched `SetBit` calls is fairly slow and inefficient. The bulk import functionality is fairly performant, but is batch based, under-documented, doesn't support clear bits, and could be more flexible, and possibly more performant.

The purpose of this ticket is to kick off a discussion and do some PoCs around streaming ingest support. Things to think about:

- Server side buffering and sorting.
- Setting an entire row at a time - perhaps by specifying runs or bitmaps rather than ints?
- Streaming rather than batching on the client side.

### Success criteria (What criteria will consider this ticket closeable?)
- streaming support for both sets and clears
- very good performance
- good client support

**Comment by jaffee** [comment]
There was some good discussion in #742 about whether clearing bits belongs in an import-like endpoint. Let's continue that here if needed.

**Comment by tgruben** [comment]
We should explore building grpc streaming endpoint for mutations,  one for set and one for clear.  This would allow a less resource intensive method for very large imports

**Comment by jaffee** [comment]
todd has done some work on ingesting roaring data in #1548

**Comment by jaffee** [comment]
A lot of work has happened since this ticket was written, and it no longer is a very accurate representation of the state of ingest performance.
