### ISSUE TITLE
Getting only first 100 bits as output.

### ISSUE THREAD

**Issue by vivekkumar159** [pilosa/pilosa#684]
Query "Bitmap(frame=' ',id=' ')" returns all the bits in the bitmap. But is there a way to get only first 100 bits as an output ?

**Comment by yuce** [comment]
Limiting the number of bits in the result is not supported yet, but there's another ticket which is related: https://github.com/pilosa/pilosa/issues/641

**Comment by ramasLTU** [comment]
we ended up patching pilosa to skip bits altogether. there are two contracts for Bitmap file: json (used by pilosa UI) and protobuf, usually used in integrations. you could potentially play around that, i.e. patching a single contract as a really nasty workaround

**Comment by jaffee** [comment]
Closing since this functionality appears to be covered by #641 - please feel free to re-open or open a new ticket if that isn't satisfactory.
