### ISSUE TITLE
Performance of parallel request.

### ISSUE THREAD

**Issue by vivekkumar159** [pilosa/pilosa#690]
I had to make 20 queries on pilosa at a time. When i made sequential and parallel http request respectively, i got the following result.
Parallel Time is : 0.76404500007629
Sequential Time is : 0.92865610122681 

I want to ask why is the time difference so low. Shouldn't parallel be more fast. Am i missing any thing or internally pilosa runs queries sequentially?
I'm running pilosa server on my local machine on single node.

Thanks

**Comment by jaffee** [comment]
Hi @vivekkumar159
Pilosa can make use of all the processing power on a cluster to perform a single query - the unit of parallelism is a "slice" of columns which is set to 10^20 (about 1 million). So if you're running Pilosa on a machine with 4 CPU cores and you have about 4 million columns (or more), each query could be using all available cores and you wouldn't gain much performance by executing multiple queries in parallel.

If you had a machine (or cluster) with 64 CPU cores and about 4 million columns of data, you should see a significant speed up by running multiple queries in parallel - if Pilosa were internally running queries sequentially we would consider that a bug.

**Comment by vivekkumar159** [comment]
ok, since my number of columns is about 10 million and my machine has 8 cores, so each query itself is using all cores and so even if i make parallel requests they will still be processed sequentially.

**Comment by jaffee** [comment]
This may not matter, but technically, they won't be processed sequentially, you just won't gain much performance by running them in parallel. 

That is to say - Pilosa will be processing all the requests concurrently, but there aren't any extra cpu cycles to take advantage of, so the total run time remains about the same.

**Comment by vivekkumar159** [comment]
So i guess i need to shift to my server to cluster with more number of cpu cores to get a better performance.

**Comment by yuce** [comment]
@vivekkumar159 It would be great to know more about how did you run the test:
* By *sequentially* do you mean you've ran the queries one after the other or in a batch (altogether)?
* How did you run the queries in parallel?
* What's the size of the data you've tested (number of bits)?
* What queries did you run? (e.g., were they `Bitmap` queries, `SetBit`, `Union`, etc?)
* Do you use one of the client libraries or use the HTTP API directly (e.g., curl)?
* Do you run the Pilosa binary or a docker image? What's the version of the Pilosa server?

**Comment by vivekkumar159** [comment]
By sequentially i mean i ran each query one by one.
For running in parallel i used curl library(curl_multi) for sending multiple requests.
My database has 10 million columns and about 100 rows.
Queries were several Unions followed by intersection of Bitmaps.
I used pilosa binary  and Version: v0.3.1

**Comment by yuce** [comment]
Thank you! As far as I've read, `curl_multi_exec` returns when all requests in the batch completes, so I think the time you've measured for the parallel case is the slowest request in the batch: https://www.onlineaspect.com/2009/01/26/how-to-use-curl_multi-without-blocking/ and also: https://stackoverflow.com/questions/21514342/no-difference-between-curl-easy-and-curl-multi

Btw, the latest Pilosa is 0.4.0. Is there any reason you use an older version? Like any breaking change in later versions or any other problem?

**Comment by vivekkumar159** [comment]
Actually i installed pilosa using brew and this is was default version i got. I think i should update to new one.
Also can you tell some other way of sending parallel requests ? I have already tried Guzzle library for Http and the performance was  same..
Thanks

**Comment by yuce** [comment]
I don't use PHP, so can't say anything about running parallel jobs with it; but if the queries you are running have very different execution times, you won't get a very different result, since the time you measure will always be for the slowest query.

Here are two trivial bash scripts which runs the same query 20 times:

```bash
# sequential.sh
for i in `seq 1 20`; do
    curl -XPOST localhost:10101/index/foo/query -d 'Bitmap(frame="bar", rowID=100)'
done
```

```bash
# parallel.sh
for i in `seq 1 20`; do
    curl -XPOST localhost:10101/index/foo/query -d 'Bitmap(frame="bar", rowID=100)' &
done

for job in `jobs -p`
do
    wait $job || exit 1
done
```

The scripts assume there's index `foo` with frame `bar`. This is what I get on my computer (ran on Linux):
```
$ time bash sequential.sh 
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}

real	0m0.359s
user	0m0.164s
sys	0m0.048s

$ time bash parallel.sh 
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}
{"results":[{"attrs":{},"bits":[1000]}]}

real	0m0.038s
user	0m0.128s
sys	0m0.012s
```

You can see there is 10x difference between the sequential and the parallel case.

**Comment by vivekkumar159** [comment]
Seems good but what is the size of your column ?

**Comment by yuce** [comment]
My answer above just demonstrates the difference between sequential and parallel cases. You can change the query in the scripts and there should be a noticeable difference between the parallel and sequential case.

**Comment by vivekkumar159** [comment]
thats true but it may be possible that when the number of column are less then there is only 1 slice and so more number of queries can be handled simultaneously as compared to the case when number of slices are more.

This is [Link](https://pastebin.com/4w1C17t9) to the php script i used for above testing.

**Comment by yuce** [comment]
@vivekkumar159 I'm closing this issue, since we now have a Google group to discuss Pilosa related topics which are not bug reports: https://groups.google.com/forum/#!forum/pilosa If you believe there's a bug with Pilosa, please open a new Github issue; otherwise let's continue the discussion in the Google group.
