### ISSUE TITLE
PQL Query() Function to support query options

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#700]
## Overview

To date, query options have been provided as HTTP query parameters. For example,
to return `columnAttrs` for a given Bitmap result, one would perform a query like:
```
curl -X POST "http://localhost:10101/index/i/query?columnAttrs=true" -d 'Bitmap(frame="f", row=1)'
```
There have been several cases where it would useful to expand on the query options
that are currently supported. Short of introducing an entirely different query interface (which
we don't want to undertake right now), it seems we have a couple of options:

 1. Continue to use HTTP query parameters, adding more as needed.
 2. Explore simple modifications to PQL that would allow support for query options.

We decided that it would be reasonable to move forward with option (2), with the
understanding that if it seems like the work required is going to become too
large, we will back off and resort to option (1).

## Details

Currently there are only two query options supported by Pilosa: `columnAttrs` and `slices`.
The following issues may require additional query options:
 - #632 - Get RowAttrs without returning bit vector
 - #633 - Return RowAttrs in TopN queries
 - #684 - Getting only first 100 bits as output

## Proposal

Introduce a wrapper called `Query()` that wraps existing PQL statements such that the wrapper
function takes one or more arguments: a PQL query (required) and zero or more query options.
```
Query(Bitmap())
Query(Intersect(Bitmap(), Bitmap()), columnAttrs=true, slices=[1,2])
Query(TopN(Bitmap(), n=10), rowAttrs=true)
```
One thing to consider is how different result types should be handled. Note how the queries in
the example above have different return types.

Changes should be backward compatible with existing PQL queries, meaning that the following
query would still be valid:
```
Intersect(Bitmap(), Bitmap())
```

A successful implementation of this proposal would also remove all existing support for HTTP
query parameters.

## Initial Requirements

Explore and report back on the feasibility and difficulty of adding a `Query()` wrapper
around exising PQL statements.

**Comment by codysoyland** [comment]
Nice! I think this is a step in the right direction. Would it make sense to replace `Count([...])` with `Query([...], output="count")` or something similar?

**Comment by yuce** [comment]
Not that I have a better name, but naming the call `Query` is a bit strange.

**Comment by codysoyland** [comment]
I don't have a strong opinion on naming, but one option would be to use `Select()` for read-only queries and something like `Insert()` or `Update()` for attributes and bit flips.

**Comment by jaffee** [comment]
I like that idea @codysoyland - more generally, could we just do `Read(...)` and `Write(...)`?

**Comment by alanbernstein** [comment]
I like the idea of `Read()` and `Write()`. What would you use for a query that does both?

**Comment by jaffee** [comment]
What query does both?

**Comment by alanbernstein** [comment]
Nothing right now I don't think. This would: https://github.com/pilosa/pilosa/issues/637

**Comment by jaffee** [comment]
it's ok, we'll just add a third: `Wread(...)`

**Comment by jaffee** [comment]
More seriously, I think if a query is doing any kind of write, it would be considered a `Write`

**Comment by travisturner** [comment]
Moving to icebox for now until we have a better reason to do this; as it stands it's a lot of work for not much gain.

**Comment by jaffee** [comment]
Now that we've rewritten the parser, this would be pretty straightforward - and probably a good idea to have these options supported outside of HTTP. We have to decide what we want to call it `Query`, `Do`, `Options`... or something separating reads and writes which I'm not sure is necessary at the moment.

**Comment by jaffee** [comment]
@yuce and I discussed the naming - current implementation has `Query`, but he's going to change it to `Opt`. `Query` becomes very confusing to talk about since it's an overloaded word. Any feedback or other suggestions are welcome.

**Comment by travisturner** [comment]
I prefer `Options` over `Opt` (but I also prefer `column` over `col` and look how that turned out). It seems to me the only argument is that you save parsing four additional characters.

**Comment by jaffee** [comment]
I'm fine with `Options`
