### ISSUE TITLE
Pilosa locks up during import with buffer-size set to 1

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#711]
### Expected behavior

Import runs (probably pretty slowly), but everything works.

### Actual behavior

Running the (soon to be released) `pi bench import-zipf` with buffer-size=1 can cause a single node Pilosa to enter a strange deadlocked state after about 4000 bits. 

### Steps to reproduce the behavior

The client-go-pilosa branch in the tools repo (not yet open source) has the client code which can reproduce this. Run pilosa locally with default args, and then run `pi bench import-zipf --buffer-size=1` - you should get an EOF error, and Pilosa will no longer respond to requests. (If you get the error and Pilosa continues being able to serve requests, running the import again should stop it - that's what I've seen anyway).

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Macbook Pro

**Comment by tgruben** [comment]
The source of the crash is pilosa is running out of file handles.  I see two parts to completely solving this issue, enhancing pilosa to protect against too many connections (#760) and modifying the client to handle multiple requests more efficiently and improved cleanup.
