### ISSUE TITLE
Explain gossip-seed in Configuration Documentation

### ISSUE THREAD

**Issue by tclass** [pilosa/pilosa#717]
For feature requests, please provide the following:

### Description
There is a gossip-seed entry in the standard configuration with an empty gossip-seed Paramter.
### Success criteria (What criteria will consider this ticket closeable?)
There should be a description an example values for the gossip-seed value here https://www.pilosa.com/docs/configuration/

**Comment by travisturner** [comment]
@tclass I updated the documentation in #720 which is now on master. We'll get the updates deployed to the website shortly. Thanks for catching this omission! Let me know if you have any other questions or feedback.

**Comment by tclass** [comment]
thanks 👍
