### ISSUE TITLE
TopN works only for cached data?

### ISSUE THREAD

**Issue by ramasLTU** [pilosa/pilosa#723]
### Expected behavior
Let's say we have `stargazer` frame, with `ranked` cache type and size of `500`. Let's also assume, that we've added an attribute for each `stargazer` row named `name` and containing value `name_#`, where `#` corresponds the row id. 

When calling:
```
Bitmap(frame="stargazer", stargazer_id=4)
```
We're getting back:
```
{"results":[{"attrs":{"name":"name_4"},"bits":[2,408]}]}
```

I am then expecting that query:
```
TopN(frame="stargazer", field="name", filters=["name_4"])
```
would actually return the same bitmap.

### Actual behavior
Actually `TopN` query returns empty result:
```
{"results":[[]]}
```
It works only with rows, that are actually present in `TopN` query without filter actions. For example:
```
TopN(frame="stargazer")
```
Returns 500-ish results, similar to:
```
{"results":[[
   {"id":1240,"count":102},
   {"id":4734,"count":100},
   {"id":12709,"count":93},
   ... ]]}
```
When calling any of these queries:
```
TopN(frame="stargazer", field="name", filters=["name_1240"])
TopN(frame="stargazer", field="name", filters=["name_4734"])
TopN(frame="stargazer", field="name", filters=["name_12709"])
```
We're getting valid response:
```
{"results":[[{"id":1240,"count":102}],[{"id":4734,"count":100}],[{"id":12709,"count":93}]]}
```
It looks like `TopN` query runs only on cached (max `500` rows) data and only then applies filters. I can reproduce the same situation, when index is recreated with even smaller cache size. Is that intended?

### Steps to reproduce the behavior

Create index with corresponding cache values and load sample values:
```bash
curl localhost:10101/index/repository/frame/stargazer \ 
    -X POST \
    -d '{"options": {
                "rowLabel": "stargazer_id", 
                "cacheType": "ranked", 
                "cacheSize": 500}}'

pilosa import -i repository -f stargazer stargazer.csv
```
Populate attributes with simple python script:
```python
qurl = 'http://localhost:10101/index/repository/query'
with open("stargazer.csv") as f:
    with requests.Session() as session:
        for line in f:
            id = line.split(",")[0]
            data = "SetRowAttrs(frame='stargazer', stargazer_id=%s, name='name_%s')" % (id,id)
            r = session.post(qurl, data=data)
            r.raise_for_status()
```
Run queries:
```
TopN(frame="stargazer", field="name", filters=["name_4"])
TopN(frame="stargazer", field="name", filters=["name_1240"])
```

**Comment by raskle** [comment]
Thanks for your thorough analysis of TopN behavior.  In short you are correct, the TopN filter only operates on the frame cache.  I agree that this caveat of the frame cache is not obvious and we are clarifying it in our documentation.  You can review that here #731 .  This tradeoff was made for performance and memory usage considerations based on our previous use case.  

Depending the source data there are other schemas that can work within this limitation through breaking rows into multiple frames by attribute instead of many attributes per frame. Let me know if you have further question and we would be happy help you work through them.

**Comment by ramasLTU** [comment]
Thanks for clarification. I have a follow-up question for someone with intricate knowledge of Pilosa internals :)

Our use case requires a possibility to find *any* row by multiple attributes. I know that it is not supported and probably - not intended for Pilosa. We can surround it with complimentary services and achieve required, however.. Could it work by introducing new Pilosa query language actions to access BoltDB? Would it make sense submit feature request / develop a suggestion PR with something in that direction?

**Comment by raskle** [comment]
Yes, I would encourage you to submit your proposal so that we can all discuss it first.  As described your issue would require changes to the Attribute model and PQL, so I would like to review all of the details before making a recommendation.
