### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by ramasLTU** [pilosa/pilosa#724]
This crash is occurring on my own fork, which was made from `7f17b379` commit on `master`. My fork does not have any significant changes and the code under the gun has not changed since.

There are multiple ways to crash the pilosa server, but I've managed to do it 100% with a simple query:
```
TopN(frame="domain", field="domain", filters=["autobild.de"])
```
which immediately results in:
```
Pilosa v0.4.0-18-g7f17b37, build time 2017-06-15T11:53:28+0000
Using data from: /Users/ru/.pilosa
2017/07/11 13:41:27 opening index: user
Listening as http://:10101
2017/07/11 13:41:57 holder sync monitor initializing (10m0s interval)
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 100 [running]:
runtime.throw(0x175eddc, 0x15)
	/usr/local/opt/go/libexec/src/runtime/panic.go:596 +0x95 fp=0xc4cfd73958 sp=0xc4cfd73938
runtime.mapassign(0x169b1e0, 0xc437f422a0, 0xc4cfd73a18, 0x0)
	/usr/local/opt/go/libexec/src/runtime/hashmap.go:499 +0x667 fp=0xc4cfd739f8 sp=0xc4cfd73958
github.com/pilosa/pilosa.(*AttrStore).Attrs(0xc437f40180, 0x43a5, 0xc4a1504210, 0x0, 0x0)
	/Users/ru/.go/src/github.com/pilosa/pilosa/attr.go:115 +0x159 fp=0xc4cfd73a50 sp=0xc4cfd739f8
github.com/pilosa/pilosa.(*Fragment).Top(0xc4468a5c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc464e62210, 0x6, 0xc464e62990, ...)
	/Users/ru/.go/src/github.com/pilosa/pilosa/fragment.go:561 +0x796 fp=0xc4cfd73c40 sp=0xc4cfd73a50
github.com/pilosa/pilosa.(*Executor).executeTopNSlice(0xc495794930, 0x1a6ab20, 0xc495794ae0, 0xc460a1c08c, 0x4, 0xc495794b70, 0x13, 0x0, 0x0, 0x0, ...)
	/Users/ru/.go/src/github.com/pilosa/pilosa/executor.go:413 +0x884 fp=0xc4cfd73e00 sp=0xc4cfd73c40
github.com/pilosa/pilosa.(*Executor).executeTopNSlices.func1(0x13, 0x0, 0x0, 0x0, 0x0)
	/Users/ru/.go/src/github.com/pilosa/pilosa/executor.go:326 +0x76 fp=0xc4cfd73e98 sp=0xc4cfd73e00
github.com/pilosa/pilosa.(*Executor).mapperLocal.func1(0xc4a2981240, 0x1a6aa60, 0xc4a2981280, 0xc495635e00, 0x13)
	/Users/ru/.go/src/github.com/pilosa/pilosa/executor.go:1252 +0x4b fp=0xc4cfd73fb8 sp=0xc4cfd73e98
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4cfd73fc0 sp=0xc4cfd73fb8
created by github.com/pilosa/pilosa.(*Executor).mapperLocal
	/Users/ru/.go/src/github.com/pilosa/pilosa/executor.go:1259 +0xc6
```

### Expected behavior

I expect that application would not crash, when cache is being modified. 

### Actual behavior

The described error occurs.

The problem (imho) lies in the [attr.go#L43](https://github.com/pilosa/pilosa/blob/master/attr.go#L43), `AttrStore` struct. It has `db` field for working with BoltDB and companion 'mu' mutex to synchronise writes and reads. 

The `attrs` map however is not concurrent safe. The panic happens on concurrent writes reach [attr.go#115](https://github.com/pilosa/pilosa/blob/master/attr.go#L115) line, where cache is being updated. 

### Steps to reproduce the behavior

I've tried to reproduce this crash with sample data, but could not make it work. I can reproduce this on our actual data 100% though. I will try to describe our structure as much as possible. We have index, created with:
```
curl localhost:10101/index/$INDEX -X POST -d '{"options": {"columnLabel": "'$INDEX'_id"}}'
```
and multiple frames (e.g. `domain`, `segment`, etc), each created similarly:
```
curl localhost:10101/index/$INDEX/frame/$FRAME \ 
    -X POST \
    -d '{"options": {
                "rowLabel": "'$FRAME'_id", 
                "timeQuantum": "D", 
                "cacheType": "ranked", 
                "cacheSize": 50000}}'
```
The bit amount in the frames reach 32M, the biggest frame row count reaches 110k.

As I mentioned, I can reproduce the problem with regular `TopN` query. It's really easy, especially when you run it against the biggest frame.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
OS X El Capitan, Version 10.11.6, 2.2 GHz i7, 16GB, solo server

### Possible solutions
I've been able to solve this problem by two (both ugly) solutions:

1. Change (promote) the `RLock` to `Lock` in [attr.go#95](https://github.com/pilosa/pilosa/blob/master/attr.go#L95). This is the worst solution (imho), since the mutex is meant for BoltDB syncs. I don't think it's a good "reuse" of the lock and might hinder performance.

2. Introduce a second mutex for cache interaction. That produces pretty ugly code (imho). 

I think **the best scenario** is to use concurrent [Map](https://github.com/golang/go/blob/master/src/sync/map.go), which was introduced fairly freshly to golang. I don't have a working solution yet however, since I would require some go practice before I would propose any official changes to your product.

**Comment by codysoyland** [comment]
Thanks for your (very) detailed bug report, ramasLTU! I agree that reusing the AttrStore mutex would be a poor choice, and I am hesitant to use the concurrent Map (even though it could be vendored from golang.org/x/sync) due to the fact that it uses `interface{}` which could hinder performance. [My patch](https://github.com/codysoyland/pilosa/commit/efda80485177d2c030313eb99c544efa66e3373e) implements a new struct, AttrCache, with its own mutex. I think separating the cache struct should satisfy your code ugliness concern. Let me know if you have any comments! Thanks!

**Comment by ramasLTU** [comment]
I really like your patch. I was considering something similar, when I found out about concurrent Map. I did not consider possible performance implications of interface casting however, but I am really glad you had. It definitely looks nicer than my current hack and I will apply it to my fork. Thanks!
