### ISSUE TITLE
Replace custom bit functions with standard go functions (go 1.9 feature)

### ISSUE THREAD

**Issue by tgruben** [pilosa/pilosa#726]
### Description
With the release of go 1.9, there will be no longer a need for our custom bit functions. We should replace the following functions with the ones provided in the standard package.  

popcount -> OnesCount64 
trailingZeroN -> TrailingZeros64

### Success criteria (What criteria will consider this ticket closeable?)
No reference to the popcount or trailingzeroN function should be found and tests should still pass

**Comment by jaffee** [comment]
This is ready to be worked on using the latest Go 1.9 release candidate. It can't be merge, however until Go 1.9 is in homebrew and actually released.
