### ISSUE TITLE
Config: internal-port should be at top level - not under cluster

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#730]
### Description
The `internal-port` setting in the config file is a per-node setting, and not the same across the whole cluster. It should be at the top level rather than nested under `[cluster]` since it can be different for each node.

### Success criteria (What criteria will consider this ticket closeable?)
`internal-port` is at top level of config - flags, env vars, and the config file all respect this. 
Documentation is updated to reflect the change.

**Comment by travisturner** [comment]
Good catch. It used to be cluster-wide before we added `internal-hosts`. I'll take this ticket and move `internal-port` out of `[cluster]`.
