### ISSUE TITLE
Create Go compiler benchmark

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#735]
Met @TocarIP at Gophercon who suggested we submit a Pilosa benchmark to the Go compiler team.

From him:
Basic requirements are pretty simple:
1)  Bench output must be in the same format as “go test –bench”. Using go test is nice, but  as long as bench outputs same
`“BenchmarkFOO       200000          10457 ns/op     97.92 MB/s”` lines other build options are ok
2) It should be runnable on 1  machine
3) Benchmark should be Cpu  bound
4) It should be relatively stable with preferably <3% swings in consecutive runs
5) Runtime should be in the order of 10 seconds
6) Hotspots should be in Go code and not in some cgo library

**Comment by TocarIP** [comment]
Quick grep shows some benchmarks in roaring/, is this something worth looking at?

**Comment by jaffee** [comment]
Hey @TocarIP - sorry we've let this hang for so long. The benchmarks in `roaring/roaring_test.go` are definitely worth looking into. I think the ones currently in there are all pretty relevant to Pilosa's performance, but I'll let @tgruben chime in, particularly on the Container* ones as I think he wrote a lot of them.

We could (and should) definitely expand this suite as well. There are several fundamental bitmap operations, and we've really only benchmarked IntersectionCount in there. There are also more combinations of bitmap formats that we could benchmark on. I think ideally we would have:
```
for op in [Intersect, Union, Xor, Difference, IntersectionCount]
    for pairing in [BitmapBitmap, ArrayArray, RunRun, BitmapRun, BitmapArray, ArrayRun]
        Benchmark op(pairing)
```
plus difference is not commutative, so we'd need difference(run, bitmap), difference(array, bitmap), and difference(run, array).

**Comment by TocarIP** [comment]
I've spent some time looking into current benchmarks.
Looking at Bitmap_IntersectionCount_ArrayRun/Bitmap_IntersectionCount_ArrayBitmap shows some possibilities for optimiaztion. I've sent PR with those optimization implemented by hand, so if you want you receive benefits, without waiting for go1.11/1.12/etc
ContainerLinear/ContainerReverse are more of a gc/memory allocator benchmark and are not that interesting.
ContainerColumn/ContainerOutsideIn/ContainerInsideOut  spend 99% in memmove, so they don't provide any new info relative to simple memmove benchmark.
SliceAscending/SliceDescending/Bitmap_IntersectionCount_BitmapRun look interesting, but I haven't looked into possible optimizations.
Overall there are 5 good benchmarks, that should probably be added to https://github.com/golang/go/wiki/Benchmarks

**Comment by jaffee** [comment]
Adding this to the Sept sprint - timeboxed to 8 hrs. Let's add what we have, and come up with any more that we can within that time.

**Comment by seebs** [comment]
This took a while to clean up, but I've added the IntersectionCount bitmaps to the wiki. Rather than make them separate entries, I just gave the name `BenchmarkBitmap_IntersectionCount`, since that runs quite a few interesting ones. I haven't evaluated SliceAscending/SliceDescending more carefully yet, but I think this is a good starting point. We can come back to this again later.
