### ISSUE TITLE
Cluster Resizing Proposal

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#737]
## Description

Phase one of cluster management provides the ability to adjust the size of the cluster
(by adding or removing one or more nodes) even if it requires us to implement a
cluster-wide lock that is in place while the resizing occurs.

## Scenario

We have a 4-node cluster with a replication factor of `2` made up of hosts:
```
[
    "192.168.0.1:10101",
    "192.168.0.2:10101",
    "192.168.0.3:10101",
    "192.168.0.4:10101"
]
```

The cluster contains the following indexes:
```
idx0  (maxSlice = 10)
idx1  (maxSlice = 17)
```

Based on the Pilosa hash algorithm, the slice-to-node allocation looks like the
following (with the slices in parenthesis representing replicas):
```
node0: idx0 [3, 7, (2, 6, 10)]
node1: idx0 [0, 4, 8, (3, 7)]
node2: idx0 [1, 5, 9, (0, 4, 8)]
node3: idx0 [2, 6, 10, (1, 5, 9)]

node0: idx1 [0, 4, 8, 12, 16, (1, 5, 9, 13, 17)]
node1: idx1 [3, 7, 11, 15, (0, 4, 8, 12, 16)]
node2: idx1 [2, 6, 10, 14, (3, 7, 11, 15)]
node3: idx1 [1, 5, 9, 13, 17, (2, 6, 10, 14)]
```

We want to add two nodes to the cluster. To do so, we perform the following steps:
- launch two new Pilosa servers with the correct configuration (i.e. the hosts list should contain the original 4 nodes followed by the 2 new nodes) with a `bootstrap` flag. 
    - The `bootstrap` flag is currently not supported, so we need to implement it. Starting a node in `bootstrap` mode will immediately put the node into state `maintenance`. The nodes will need to join the gossip pool, but they shouldn't respond to any mutation messages (like add index/frame).
- on the existing cluster, call the following endpoint: `/manage/cluster/add-nodes -d '{hosts: ["192.168.0.5:10101", "192.168.0.6:10101"]}'`
- the node that receives the `add-nodes` call is now the coordinator of this request and will ensure that the following steps occur:
    - broadcast to the cluster that we are in maintenance mode (effectively locking the cluster). put all nodes into a state of `maintenance`
        - the operation should fail (and revert back to "available") if we can't get a confirmation that all nodes are locked
        - anti-entropy process should be paused while in `maintenance`
    - force anti-entropy to run once to be sure that replica data are in sync with primary data
    - trigger a flush method prior to file transfer (possibly call snapshot)
    - calculate the **resize plan**
    - broadcast the plan to all nodes (including the new nodes)
        - upon receiving the **resize plan**, each node should start requesting the fragments that it needs
        - when each node has successfully gotten its data, it needs to respond back to the coordinator that it has all the data.
    - add nodes 5 and 6 to the cluster (in memory)
        - broadcast a message to all nodes with the updated cluster node list
    - we can now safely delete the unused data files
    - remove the cluster lock (i.e. change node states back to `available`)

The new slice-to-node allocation will look like this (with the slices in parenthesis representing replicas):
```
node0: idx0 [1, (0, 2)]
node1: idx0 [10, (1)]
node2: idx0 [7, 9, (10)]
node3: idx0 [4, 6, 8, (7, 9)]
node4: idx0 [3, 5, (4, 6, 8)]
node5: idx0 [0, 2, (3, 5)]

node0: idx1 [4, 8, 10, (9, 15)]
node1: idx1 [5, 7, 11, (4, 8, 10)]
node2: idx1 [0, 6, 16, (5, 7, 11)]
node3: idx1 [1, 3, 13, 17, (0, 6, 16)]
node4: idx1 [2, 12, 14, (1, 3, 13, 17)]
node5: idx1 [9, 15, (2, 12, 14)]
```

### /manage/cluster/add-nodes

Use this endpoint to add nodes to an existing cluster. This will put all nodes in the cluster into
state `maintenance` until the entire resize is complete.

Add Nodes:
```
POST /manage/cluster/add-nodes -d "{hosts: ["192.168.0.5:10101", "192.168.0.6:10101"]}"

Return: ??
```

### /manage/cluster/remove-nodes

Use this endpoint to remove nodes from an existing cluster. This will put all nodes in the cluster into
state `maintenance` until the entire resize is complete.

Remove Nodes:
```
POST /manage/cluster/add-nodes -d "{hosts: ["192.168.0.1:10101", "192.168.0.2:10101"]}"

Return: ??
```

## Broadcast Messages

We need to add support for the following broadcast messages:
- SetNodeStateMessage: put all nodes into `maintenance` mode
- TriggerAntiEntropyMessage: force anti-entropy to run
- TriggerFlushMessage: trigger a flush (or call snapshot)
- ResizePlanMessage: contains the **resize plan**
- NodeResizeCompleteMessage: node signals that it has completed all of its resize operations (and has all the data files that it needs)
- ClusterNodesMessage: broadcase the updated list of nodes in the cluster (based on this, each node should update their Nodes list that is registered in memory)
- SetNodeStateMessage: put all nodes back to `available` (at the same time, we could delete any data files that are no longer used, or we could make that a completely separate message)

**Comment by raskle** [comment]
Enforce that the replication factor is >= 2 on all clusters, or display a warning on startup.
I wanted to clarify the joining cluster state.  When adding a node the new node in the a joining state while existing nodes are in a maintenance state.  Thus the existing nodes can still respond to some requests.
We should define functional access groups for our API endpoints.  
  - Maintenance can read but not write
  - Bootstrap/Joining can neither read or write
  - The Query will be a special case and will need to be evaluated after handling the request
During the joining process we also need to transfer
 - Attribute date
 - Input definitions

**Comment by travisturner** [comment]
I will break this out into an Epic with issues.
