### ISSUE TITLE
BSI Range-Encoding: add documentation

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#740]
- All new PQL functionality should be described in the query language section.
- A brief overview of range encoding storage and operations should be added to the data model section.
- A brief usage example should be added to the tutorial section (taxi data could work for this).

**Comment by yuce** [comment]
Documentation for SetFieldValue, Average and Sum are in PR https://github.com/pilosa/pilosa/pull/816 but there's no docs for the Xor call.

**Comment by travisturner** [comment]
I created #853 to address `Xor` documentation.

**Comment by travisturner** [comment]
fixed by #816
