### ISSUE TITLE
Import clearbits

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#742]
For feature requests, please provide the following:

### Description
`pilosa import` only sets bits, so it can't be used for clearing bits in bulk.

### Success criteria (What criteria will consider this ticket closeable?)
Pilosa supports a new subcommand or new import format that allows clearing bits.

**Comment by yuce** [comment]
Not sure whether importing data is the best way of clearing bits. It would be great if you could include more detail on the use case. I can think of two, which would be better solved with other approaches:
1) Import data into an already existing frame so it contains the exact bits in the import. This could be solved by deleting the frame, re-creating it with the same options and do the import.
2) Delete/Reset a row or column so it doesn't contain any 1 bit. I think it would be better to have specialized PQL calls, like `DeleteRow`, `DeleteColumn`.

**Comment by raskle** [comment]
This could facilitate faster imports in a data pipeline that periodically updates the Pilosa index from another datastore.  Especially if this data is the delta from the last sync.  Then it will be faster to just clear and/or set the bits that have changed in bulk.

**Comment by jaffee** [comment]
This is actually mentioned in #666 as well - I think supporting bulk clear bits is worthwhile, but it should be supported in conjunction with whatever changes are made in that ticket.

**Comment by jaffee** [comment]
I'm going to close this and reference the discussion from #666 - let me know if there is any problem with that.
