### ISSUE TITLE
Use monotonic time for timing

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#756]
`time.Now()` returns real time, which can jump occasionally. https://github.com/gavv/monotime, for example, provides a monotonic `Now()` function, which is preferable for timing measurements.

Searching the codebase for `time.Now` and `time.Since` shows a handful of locations where this would make sense to do.

### Expected behavior
Timing any event should result in a reasonable approximation to the elapsed event time.

### Actual behavior
Incorrect values can be returned in rare circumstances, including negative values when computing elapsed time like
```
start := time.Now()
doSomethingQuick()
elapsed := time.Since(start)
```

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

**Comment by jaffee** [comment]
Closing this - solved by go1.9 https://golang.org/doc/go1.9#monotonic-time
