### ISSUE TITLE
TopN queries return no results if you have 1 column with all set bits

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#771]
Using a ranked frame with a cache size of 10000, and millions of rows, but only one column.

### Expected behavior
A TopN query will return `n` rows each with a count of 1.

### Actual behavior
TopN query returns no results.

### Steps to reproduce the behavior
I haven't verified this, but you can probably use `pi bench` to import 1000 rows, with just one column, and set every bit. Make sure you've created the frame with CacheType: ranked, and CacheSize: 500 (something less than 1000). Then perform a TopN query on that frame.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Mid 2014 Macbook Pro 16 GB single node.

**Comment by travisturner** [comment]
fixed by #795
