### ISSUE TITLE
Diagnostics send metrics

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#800]
### Description
Create an hourly process to send the diagnostics payload to the Pilosa diagnostics processing service.

### Success criteria (What criteria will consider this ticket closeable?)
Metrics are delivered every hour from server start.
Only the first or seed server in the cluster sends metrics.
The hourly service will ignore transmission failures since it may not be connected to the internet.

**Comment by codysoyland** [comment]
#895 includes implementation. Closing.
