### ISSUE TITLE
Bitmap.WriteTo performs unecessary allocations

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#805]
### Description
The purpose of `Bitmap.WriteTo` is to serialize the `roaring.Bitmap` to an `io.Writer`. Currently it allocates a byte slice, populates the byte slice, and then writes it to the `io.Writer`. It should be possible to directly write bytes to the `io.Writer` rather than going through a byte slice first.

This conversion will involve using the `binary.Write(w io.Writer, order ByteOrder, data interface{}) error` function instead of the `binary.LittleEndian.Put*` methods.

### Success criteria (What criteria will consider this ticket closeable?)
Bitmap.WriteTo should no longer allocate additional memory and performance should be improved.

**Comment by tgruben** [comment]
Going to explore further the binary.Write appears to do allocations as well,
`810.51MB     1.52GB    550:			binary.Write(w, binary.LittleEndian, uint64(key))
         .          .    551:			//binary.LittleEndian.PutUint64(buf[headerSize+(i-empty)*12:], uint64(key))
  799.51MB     1.50GB    552:			binary.Write(w, binary.LittleEndian, uint16(c.container_type))
         .          .    553:			//				binary.LittleEndian.PutUint16(buf[headerSize+(i-empty)*12+8:], uint16(c.container_type))
  783.51MB     1.52GB    554:			binary.Write(w, binary.LittleEndian, uint16(c.n-1))
         .          .    555:			//				binary.LittleEndian.PutUint16(buf[headerSize+(i-empty)*12+8+2:], uint16(c.n-1))`

**Comment by jaffee** [comment]
I guess we need a buffered writer that re-uses its buffer between invocations of WriteTo?

**Comment by tgruben** [comment]
I've managed to remove all of the of allocations.  Though the performance is still about 3x (11minutes vs 34 minutes) longer for the 100million bitmap test.  Gonna let that simmer for a bit.

**Comment by jaffee** [comment]
can you open a PR? I'd love to take a look
