### ISSUE TITLE
/status endpoint doesn't return rangeEnabled nor range fields

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#819]
For bugs, please provide the following:

### Expected behavior

`/status` endpoint returns `rangeEnabled` field and range fields.

### Actual behavior

`/status` endpoint doesn't return `rangeEnabled` field and range fields.

### Steps to reproduce the behavior

* Create index `i1`
* `curl localhost:10101/index/i1/frame/foo -d '{"options":{"rangeEnabled":true, "fields":[{"name":"ff", "type":"int", "min": 10, "max": 100}]}}'`
* `curl localhost:10101/status` returns:
```
{"status":{"Nodes":[{"Host":"localhost:10101","State":"UP","Indexes":[{"Name":"i1","Meta":{"ColumnLabel":"columnID"},"Frames":[{"Name":"foo","Meta":{"RowLabel":"rowID","CacheType":"ranked","CacheSize":50000}}],"Slices":[0]}]}]}}
```

**Comment by travisturner** [comment]
In working on the cluster resizing code, I have found and noted several places where we are not considering the full set of frame options. I'll assign this to me because I'll likely address them in the work I'm doing.

**Comment by travisturner** [comment]
@yuce this will be addresses by #902 (to be committed to #904) on the `cluster-resize` branch.
all `FrameOptions` (including `rangeEnabled`) will be available at the `/schema` endpoint.
I'll close this, but add any more feedback you have to #902.
