### ISSUE TITLE
Use a single `data` field in roaring.container instead of 3 slices.

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#826]
### Description
Continuing the theme from #824 and #825 - it may be possible to save significant memory without affecting performance in the roaring.container struct. It currently has 3 slices of different types - each of which consumes 24 bytes of memory. Only one of these is in use at a time while the other two are nil (except during conversions). The proposal is to use a single field `data interface{}`, and use type switches or type assertion like so:
```
func (c *container) array() []uint16 {
    if r, ok := c.data.([]uint16); ok {
        return r
    }
    return nil // or panic?
}
```

Basic benchmarking seems to indicate that this will be similar to, or even better than the previous solution in terms of performance, and it will save (I think) 32 bytes of memory per container. Reasoning here is we're getting rid of two slices which saves 24*2=48 bytes, but we're adding an interface{} value which points to a slice, and the interface costs 16 bytes, so 48-16=32.

### Success criteria (What criteria will consider this ticket closeable?)
Refactor roaring to use a single field for container data - confirm memory savings and minimal performance impact.

**Comment by seebs** [comment]
and before i forget: this might conceivably imply that a bitmap struct would be [8192]uint64 instead of []uint64, saving us a valuable allocation.

**Comment by travisturner** [comment]
wouldn't it be `[1024]uint64`?

**Comment by seebs** [comment]
Well, sure, if you wanted to be *correct*.

I remembered that it was "8K", and there was too much blood in my caffeine stream.

**Comment by jaffee** [comment]
we went a different direction on this, but the container shrinking work is in
