### ISSUE TITLE
Convert the examples in Docs->Tutorials to use the client libraries

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#838]
### Description

The examples in Docs->Tutorials should use client libraries.

### Success criteria (What criteria will consider this ticket closeable?)

The examples in Docs->Tutorials use client libraries.

**Comment by codysoyland** [comment]
In general I like the idea, but in the interest of getting people rolling quickly, and not assuming the language preference of the reader, I wonder if it would make sense to have all the PQL examples have tabs so you can see the queries in each language (including curl). But I don't know how you would do that in markdown. Maybe with [shortcodes](https://gohugo.io/templates/shortcode-templates/)?

**Comment by travisturner** [comment]
closing this as low priority.
