### ISSUE TITLE
Add documentation for Xor call.

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#853]
### Description
`Xor` is a new function call, and we have yet to provide documentation and examples.

### Success criteria (What criteria will consider this ticket closeable?)
`Xor` is represented in the docs.

**Comment by yuce** [comment]
I think @raskle 's PR https://github.com/pilosa/pilosa/pull/816 includes docs for `Xor`.

**Comment by travisturner** [comment]
Thanks, I associated that PR to this issue.

**Comment by codysoyland** [comment]
Since #816 is merged, this can be closed.
