### ISSUE TITLE
review intersectBitmapRun() logic, specifically the return container type.

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#854]
### Description
in `roaring/roaring.go`, the comment for `intersectBitmapRun()` says:

```
// intersectBitmapRun returns an array container if the run container's
// cardinality is < ArrayMaxSize. Otherwise it returns a bitmap container.
```
Based on the code, however, it appears that it may return an array (not a bitmap) in the second case with this code:
```
if output.n < ArrayMaxSize {
    output.bitmapToArray()
}
```
I tried changing this to:
```
output.Optimize()
```
but this caused one of the tests to fail. Which makes me think that the test is expecting this function to return an array, when it should, optimized, return a different type.

### Success criteria (What criteria will consider this ticket closeable?)
Tests pass and we can correctly optimize `intersectBitmapRun()`.

**Comment by travisturner** [comment]
Same goes for `differenceBitmapArray()`
I'm not sure if the correct thing to do is to call `optimize()` before returning in these functions, or to remove the conversion to array (and assume `Optimize()` is being called later).

**Comment by seebs** [comment]
I guess the first question is: Is the goal to return the most convenient container to compute, or the most efficient container to store, or what? We can make it return any type we want, the question is whether we should be regarding the comment's statement as a *goal*, or merely a description of the original intent.

**Comment by travisturner** [comment]
It's unclear to me whether these container-container functions should return an optimized container type, or if the assumption is that `Optimize()` may be called later (after further operations), and therefore calling it within every container-container function would be premature and/or unnecessary.

**Comment by jaffee** [comment]
I don't think that the container-container methods should always return an optimized container type. In many cases the optimized container would probably not be significantly more efficient for continued processing, and the process of optimizing would not be worth it. Ideally, I think we'd be informing these decisions with benchmarks on a case by case basis, this issue's status as being blocked on the benchmarking work is valid. The comment's statement should definitely not be regarded as a goal.

Containers are definitely optimized before being written to disk.

**Comment by seebs** [comment]
So the reason that using optimize breaks one of the tests is that, in one case, optimize picks runlength because the number of runs is very small so that's even more optimized than array.

It depends, in part, on what the continued processing is is likely to look like. My intuition is that the even-more naive solution of "return an array if the maximum number of results is definitely <= ArrayMaxSize, otherwise return a bitmap" is probably better. I don't think being able to predict the return type is as important as avoiding conversions when we don't know whether we're about to just convert back.
