### ISSUE TITLE
How to run more than one Pilosa instance on the same machine should be more obvious

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#870]
How to run 2 separate (non-clustered) Pilosa instances with different ports on the same server isn't very obvious:

First server runs OK as expected:
```
$ ./pilosa server -b :10501 -d dir1
```

Running the second server fails with `error running server: server.Open: opening NodeSet: Failed to start TCP listener. Err: listen tcp :14000: bind: address already in use`:
```
$ ./pilosa server -d dir2
```

Currently, the workaround is setting `cluster.type` to `static` or assigning different `gossip-port`s work.

An easy solution would be setting `cluster.type` to `static` by default and only enable gossip if cluster/gossip related configuration is provided.

**Comment by travisturner** [comment]
Let's hold off on addressing this until the cluster resize work in #896 is complete.

**Comment by jaffee** [comment]
no longer relevant due to changes in clustering and config
