### ISSUE TITLE
StatsD tag per Node

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#891]
Server.Open is setting a StatsD NodeID tag for every node in the cluster in the current holder.
It seems this should just set the current Node's tag.  Investigate this code and the impact on the collected stats.

for i, n := range s.Cluster.Nodes {
		if s.Cluster.NodeByHost(n.Host) != nil {
			s.Holder.Stats = s.Holder.Stats.WithTags(fmt.Sprintf("NodeID:%d", i))
		}
	}

### Expected behavior
all metrics are tagged with the current Node ID

### Actual behavior
unknown behavior

**Comment by travisturner** [comment]
fixed by #932
