### ISSUE TITLE
Temporary Store

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#910]
### Description
We need the ability to temporarily store a bitmap result for later use.
These results can be stored, retrieved and purged.  
We should discuss if there should be an implicit or explicit TTL for stored bitmaps
Also what should happen we attempting to overwrite an existing stored result
Stored bitmaps are not persisted after restart, but the values should persist through Cluster resizing.

#### Storage
```
Bind(<id=STRING>, [BITMAP_CALL])
```
#### Retrieval
```
Load(<id=STRING>)
```
Or simply used the previously bound ID name as a bitmap?
#### Delete
```
Purge(<id=STRING>)
```

Example
```
Bind(id=commits, Range(frame="stats", commitactivity > 100))

Intersect(commits, Bitmap(frame="stargazer", stargazer_id=1))
```

### Success criteria (What criteria will consider this ticket closeable?)
Can used the Stored bitmap by name in any PQL operation requiring a bitmap.
Any bitmap can be stored, retrieved, and purged.

**Comment by alanbernstein** [comment]
Previous discussion: https://github.com/pilosa/pilosa/issues/637

**Comment by alanbernstein** [comment]
and I think @tgruben implemented this with a plugin

**Comment by jaffee** [comment]
I think #637 and #1240 will cover this. I don't think it's worth adding features like TTL and not persisting through restarts unless we start to feel a distinct need for them
