### ISSUE TITLE
"too many writes" in monitorAntiEntropy

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#914]
### Expected behavior
Anti-entropy process is aware of max writes per request and does not violate it.

### Actual behavior
Anti-entropy process can make a request which gets rejected because it is too large.

### Steps to reproduce the behavior
Unclear - problem is occurring in a fairly large Pilosa install. 6 large nodes, replication factor of 2. Probably, a node went down, and so it's replicas got very far out of sync, so the anti-entropy process tried to sync too many bits at once.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Pilosa 0.7.1 on Linux 64 bit.

**Comment by raskle** [comment]
example error log:
2017/10/31 10:14:13 holder sync error: err=fragment sync error: index=i132, frame=l_n, slice=6,err=sync block: id=214048, err=too many write commands
