### ISSUE TITLE
add undocumented flags to config docs

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#915]
### Description
The following config options appear to be undocumented in the Configuration section of our documentation:

- long-query-time
- log-path
- max-writes-per-request
- plugins.path (we should probably remove this option?)

### Success criteria (What criteria will consider this ticket closeable?)
Let's get these added.

**Comment by tgruben** [comment]
Plugins.path can be removed.  It is no longer applicable, the current plugin direction is static and there is no need for dynamic loading
