### ISSUE TITLE
MaxShard value incorrect on cluster startup

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#916]
### Description
I'm proposing that we store max slice and inverse max slice with the Index `.meta` file.
Currently thecluster wide `maxslice` value is determined via gossip.  During startup each node's default state is the max slice it contains, and as we grow to more slices there is larger dispersion of slices per node.  Over several gossip iterations the nodes will coalesce on the correct value, but the time to achieve this grows with the number nodes, number of slices, and the `memberlistConfig.PushPullInterval`.  I would like to see the cluster at startup achieve agreement on this value sooner.   

### Success criteria (What criteria will consider this ticket closeable?)
Max Slice is stored and retrievable from the index `.meta` file.  Cluster starts up immediately with correct max slice value.

**Comment by codysoyland** [comment]
Still running into this problem. I clarified the title and tagged as a bug which I think is more accurate. We should get this fixed soon.

**Comment by travisturner** [comment]
@codysoyland I believe the work currently being done in #593 will address this, but we should confirm once that's in review.

**Comment by jaffee** [comment]
@travisturner how does that fit together with #1008 - are these three tickets basically all the same?

**Comment by travisturner** [comment]
@jaffee I believe they're all basically the same thing. #1008 seems to be a summary of the issue and represents the current work better than just #593. This issue (#916) is a specific part of the implementation.

**Comment by codysoyland** [comment]
Fixed in #1600

**Comment by travisturner** [comment]
@codysoyland I left this open because I wasn't 100% sure that #1600 addressed this. Can you make sure that there's a test covering this case?

**Comment by travisturner** [comment]
fixed by #1663
