### ISSUE TITLE
Test failures when running tests in Docker (exit status 127)

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#944]
### Expected behavior

All tests pass in Docker.

### Actual behavior

Tests from `server` and `cmd` packages fail when run in Docker.

### Steps to reproduce the behavior

Run `server` and `cmd` in Docker:

`docker run --rm -v $GOPATH/src/github.com/pilosa/pilosa:/go/src/github.com/pilosa/pilosa -w /go/src/github.com/pilosa/pilosa golang:latest go test github.com/pilosa/pilosa/server github.com/pilosa/pilosa/cmd
`

The output I get is this:

```
2017/11/09 22:28:40 exit status 127
FAIL	github.com/pilosa/pilosa/server	0.013s
2017/11/09 22:28:41 exit status 127
FAIL	github.com/pilosa/pilosa/cmd	0.055s
```

The failure messages are terse (exit status 127). Running `go test` with `-v` produces no output relevant to the failure.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

I reproduced this on Docker for Mac with both the `golang:latest` and `ubuntu:latest` Docker images (`ubuntu:latest` requires additional setup).

**Comment by jaffee** [comment]
I traced this failure to an fdatasync system call from boltdb... not sure where to go from there, but it may not be worth spending time on.

**Comment by ps23** [comment]
Any progress? This is quite a bumper for our test suite.

**Comment by jaffee** [comment]
@ps23 unfortunately there is no update on this - when I tried to track it down last year, it didn't seem to be an issue with Pilosa, but rather something to do with docker's interaction with fdatasync. Unless you're able to dig into this, I'd suggest trying to find a workaround as I don't think we'll be able to dedicate resources to this issue in the near term.

**Comment by yuce** [comment]
The command in this ticket runs just fine for Pilosa master with the following configuration:
* Ubuntu 18.04
* Docker 17.12

**Comment by yuce** [comment]
@ps23 Could you give some information about your OS, Docker version if you are still having an issue?

**Comment by yuce** [comment]
Closing this, since the issue seems to be resolved. Please reopen this in case there are problems.
