### ISSUE TITLE
Importing to a field that does not exist

### ISSUE THREAD

**Issue by raskle** [pilosa/pilosa#948]
### Expected behavior
using the Import command on a `field` that does not exist should throw an error.
pilosa import -i project -f stargazer --field star_count project-stargazer-counts.csv

### Actual behavior
The import command will run and silently fail to import those values to a field.  It will not create a field that does not yet exist.

### Steps to reproduce the behavior
Create a single node cluster with `index` project and `frame` stargazer.

### Success criteria (What criteria will consider this ticket closeable?)
Import returns an error when importing BSI data to a field that does not exist
i.e.
fragment error: index=project, frame=stargazer, slice=0, err=field not found

**Comment by yuce** [comment]
This seems to be fixed in the latest master. When I try to import a non-existent field, I get: `import error: index=i1, frame=f1, slice=0, field=r2, bits=3, err=Field does not exist: r2`. Closing.

**Comment by travisturner** [comment]
@yuce thanks for reviewing this. It's odd that Michael created this issue well after the commit that returns that error was added. I'm wondering if his intention was to raise errors if any of the data being imported is invalid. For example, if an import contains data that is outside the range of valid values for the field, should we raise an error? I'm not sure the best approach for that scenario, but it may be worth exploring in another issue.

**Comment by yuce** [comment]
@travisturner Trying to import a field with out of range values seem to return an error. I've created a frame with a field in range [0,10] and the following data:
```
$ cat import.csv 
10,1
20,2
30,30
```
returns: `import error: index=i1, frame=f1, slice=0, field=r1, bits=3, err=field value too high, columnID=30, value=30`

**Comment by travisturner** [comment]
@yuce thanks for checking that. I can't think of any other reason why this issue was created.
