### ISSUE TITLE
Clean up TestMain_SendReceiveMessage

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#951]
`TestMain_SendReceiveMessage` needs to be modified to some extent. I ran into test failures from `availablePorts` returning ports that were not available. Assigning to Travis to add more detail per our conversation.

**Comment by travisturner** [comment]
`TestMain_SendReceiveMessage` is calling `Server.Open()` via `Main.Run()` in `test.MustRunMain()`. This is fine except that the new diagnostics background job is expecting the `NodeSet` (memberlist gossip) to be configured and available upon `Open()`. In this test scenario, the `Cluster.NodeSet` has not been defined by this point; in face, it is directly setup in the test and `NodeSet.Open()` is called again. This results in a panic from the diagnostics code path.
The other problem with this test is that it is specifying two gossip ports, but sometimes those ports are no longer available in the test environment. It seems to a race condition between the time the ports are checked, and the time they are used by memberlist.
