### ISSUE TITLE
Pilosa server binds to localhost in Docker image

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#977]
### Expected behavior

Pilosa server used to bind to all interfaces by default with default bind parameter `:10101`. This would let you access Pilosa from another server. Now that the default is to bind only to localhost, the Docker image is broken by default because the server can't be reached outside of the container.

### Actual behavior

Pilosa listens only on localhost when running the official Docker image.

### Steps to reproduce the behavior

1. Run Pilosa in a container: `docker run -it --rm --name pilosa -p 10101:10101 pilosa/pilosa:latest server`
2. Attempt an http request to Pilosa from outside the container. eg. `curl localhost:10101`
3. In my case the output of `curl` is `curl: (52) Empty reply from server`

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Mac OS with latest Docker.

**Comment by yuce** [comment]
The host is `127.0.0.1` (or `localhost`) by design: https://github.com/pilosa/general/blob/master/proposal/configuration-proposal.md . I think modifying the docker image so it binds to `0.0.0.0:10101` would be the correct way to solve the problem.

**Comment by yuce** [comment]
Proabably it's best to set the docker URI to `http://0.0.0.0:10101` would be the best, so the we don't rely on defaults.

**Comment by codysoyland** [comment]
After thinking about it some, binding to localhost seems like a sensible default, and we can override the Dockerfile default to bind to 0.0.0.0. I will modify the ticket to reflect this decision.
