### ISSUE TITLE
Diagnostics: Add Cluster ID field

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#987]
### Description

Add field to diagnostics payload that represents the Cluster ID. This would be a GUID that will have to be generated on startup and agreed on among cluster nodes.

### Success criteria (What criteria will consider this ticket closeable?)

Diagnostics payload includes Cluster ID field

**Comment by yuce** [comment]
implemented by https://github.com/pilosa/pilosa/pull/1013, closing.
